use zeroize::Zeroize;

use crate::{
    CryptoKeystoreError, CryptoKeystoreResult, Transaction,
    entities::helpers::{count_helper, count_helper_tx, delete_helper, get_helper, load_all_helper},
    traits::{Entity, EntityDatabaseMutation, FetchFromDatabase, PrimaryKey},
};

#[derive(core_crypto_macros::Debug, Clone, Zeroize, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
pub struct ProteusPrekey {
    pub id: u16,
    #[sensitive]
    pub prekey: Vec<u8>,
}

impl ProteusPrekey {
    pub fn from_raw(id: u16, prekey: Vec<u8>) -> Self {
        Self { id, prekey }
    }

    pub async fn get_free_id(db: &impl FetchFromDatabase) -> crate::CryptoKeystoreResult<u16> {
        // TODO: now that database unification is accomplished, we can replace this silly loop
        // with something more efficient which just queries the database directly.
        let mut id = 1u16;
        let limit = u16::MAX;
        while id <= limit {
            if id == limit {
                return Err(crate::CryptoKeystoreError::NoFreePrekeyId);
            }
            if db.get::<Self>(&id).await?.is_none() {
                break;
            }
            id += 1;
        }

        Ok(id)
    }
}

impl PrimaryKey for ProteusPrekey {
    type PrimaryKey = u16;

    fn primary_key(&self) -> u16 {
        self.id
    }
}

impl Entity for ProteusPrekey {
    const TABLE_NAME: &'static str = "proteus_prekeys";

    fn get(conn: &rusqlite::Connection, key: &u16) -> CryptoKeystoreResult<Option<Self>> {
        get_helper(conn, "id", *key, |row| {
            Ok(Self::from_raw(row.get("id")?, row.get("key")?))
        })
    }

    fn count(conn: &rusqlite::Connection) -> CryptoKeystoreResult<u32> {
        count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> CryptoKeystoreResult<Vec<Self>> {
        load_all_helper(conn, |row| Ok(Self::from_raw(row.get("id")?, row.get("key")?)))
    }
}

impl EntityDatabaseMutation for ProteusPrekey {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached("INSERT OR REPLACE INTO proteus_prekeys (id, key) VALUES (?, ?)")?;
        stmt.execute(rusqlite::params![self.id, self.prekey])?;
        Ok(())
    }

    fn count(tx: &rusqlite::Transaction) -> CryptoKeystoreResult<u32> {
        count_helper_tx::<Self>(tx)
    }

    fn delete(tx: &rusqlite::Transaction, id: &u16) -> CryptoKeystoreResult<bool> {
        delete_helper::<Self>(tx, "id", *id)
    }
}
