use zeroize::Zeroize;

#[derive(core_crypto_macros::Debug, Clone, Zeroize, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
pub struct ProteusPrekey {
    pub id: u16,
    id_bytes: Vec<u8>,
    #[sensitive]
    pub prekey: Vec<u8>,
}

impl ProteusPrekey {
    pub fn from_raw(id: u16, prekey: Vec<u8>) -> Self {
        Self {
            id_bytes: id.to_le_bytes().into(),
            id,
            prekey,
        }
    }

    pub fn id_bytes(&self) -> &[u8] {
        &self.id_bytes
    }

    pub fn id_from_slice(slice: &[u8]) -> u16 {
        if slice.len() < 2 {
            panic!("Oops, Proteus Prekey id slice is too small!");
        }

        let mut id_buf = [0u8; 2];
        id_buf.copy_from_slice(&slice[..2]);
        let id: u16 = u16::from_le_bytes(id_buf);
        id
    }

    pub fn set_id(&mut self, id: u16) {
        self.id = id;
        self.id_bytes = self.id.to_le_bytes().into();
    }

    pub async fn get_free_id(conn: &crate::Database) -> crate::CryptoKeystoreResult<u16> {
        use crate::traits::FetchFromDatabase as _;
        let mut id = 1u16;
        let limit = u16::MAX;
        while id <= limit {
            if id == limit {
                return Err(crate::CryptoKeystoreError::NoFreePrekeyId);
            }
            if conn.get::<Self>(&id).await?.is_none() {
                break;
            }
            id += 1;
        }

        Ok(id)
    }
}

impl crate::traits::UnifiedEntity for ProteusPrekey {
    const COLLECTION_NAME: &'static str = "proteus_prekeys";

    fn get(conn: &rusqlite::Connection, key: &u16) -> crate::CryptoKeystoreResult<Option<Self>> {
        crate::entities::helpers::get_helper(conn, "id", *key, |row| {
            Ok(Self::from_raw(row.get("id")?, row.get("key")?))
        })
    }

    fn count(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<Vec<Self>> {
        crate::entities::helpers::load_all_helper(conn, |row| Ok(Self::from_raw(row.get("id")?, row.get("key")?)))
    }
}

impl crate::traits::UnifiedEntityDatabaseMutation for ProteusPrekey {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached("INSERT INTO proteus_prekeys (id, key) VALUES (?, ?)")?;
        stmt.execute(rusqlite::params![self.id, self.prekey])?;
        Ok(())
    }

    fn count(tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper_tx::<Self>(tx)
    }

    fn delete(tx: &rusqlite::Transaction, id: &u16) -> crate::CryptoKeystoreResult<bool> {
        crate::entities::helpers::delete_helper::<Self>(tx, "id", *id)
    }
}
