[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.check]
command = "cargo"
args = ["check"]

##################################### WASM ####################################

[tasks.wasm]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-emscripten", "${@}"]

[tasks.wasm-xargo]
command = "rustup"
args = ["run", "nightly", "xargo", "build", "-Zbuild-std", "--target", "wasm32-unknown-emscripten", "${@}"]

# [tasks.wasm-debug]
# private = true
# command = "cargo"
# args = ["build", "--target", "wasm32-unknown-emscripten"]
# env = { EMCC_CFLAGS = "--bind" }

# [tasks.wasm-release]
# private = true
# command = "cargo"
# args = ["build", "--target", "wasm32-unknown-emscripten", "--release"]
# env = { EMCC_CFLAGS = "--bind -O3" }

##################################### iOS #####################################

[tasks.ios-env]
plugin = "detect-release"

[tasks.ios-device-internal]
private = true
command = "cargo"
args = ["build", "--target", "aarch64-apple-ios", "--features", "mobile", "${@}"]
# dependencies = ["ios-env"]

[tasks.ios-device]
dependencies = ["ios-device-internal"]
# run_task = "call-swiftc"

[tasks.ios-simulator-internal]
private = true
command = "cargo"
args = ["build", "--target", "x86_64-apple-ios", "--features", "mobile", "${@}"]
# dependencies = ["ios-env"]

[tasks.ios-simulator]
dependencies = ["ios-simulator-internal"]
# run_task = "create-framework"
# run_task = "call-swiftc"

# [tasks.ios-simulator-arm-internal]
# private = true
# command = "cargo"
# args = ["build", "--target", "aarch64-apple-ios-sim", "--features", "mobile", "${@}"]
# dependencies = ["ios-env"]

# [tasks.ios-simulator-arm]
# dependencies = ["ios-simulator-arm-internal"]
# run_task = "call-swiftc"

[tasks.create-framework]
script = '''
    cd bindings/swift

    rm -rf ./out/CoreCrypto.xcframework

    cp ../../../target/x86_64-apple-ios/release/libcore_crypto_ffi.a ./out/libcore_crypto_ffi_iossimulator.a
    xcodebuild -create-xcframework \
        -library ../../../target/aarch64-apple-ios/release/libcore_crypto_ffi.a \
        -headers ./include \
        -library ./out/libcore_crypto_ffi_iossimulator.a \
        -headers ./include \
        -output ./out/CoreCrypto.xcframework

    rm ./out/libcore_crypto_ffi_iossimulator.a
'''

[tasks.call-swiftc]
private = false
command = "swiftc"
args = [
    "-module-name", "CoreCrypto",
    "-emit-library", "-o", "./bindings/swift/out/CoreCrypto.dylib",
    "-emit-module", "-emit-module-path", "./bindings/swift/out/CoreCrypto",
    "-parse-as-library",
    "-L", "../target/aarch64-apple-ios/release",
    "-lcore_crypto_ffi",
    "-L", "../target/x86_64-apple-ios/release",
    "-lcore_crypto_ffi",
    "-Xcc", "-fmodule-map-file=./bindings/swift/include/core_cryptoFFI.modulemap",
    "./bindings/swift/Sources/CoreCrypto/CoreCrypto.swift",
]

[tasks.ios]
dependencies = ["ios-device", "ios-simulator"]

################################### Android ###################################

[tasks.android-env]
plugin = "android-env"

[tasks.android-armv7]
command = "cargo"
args = ["build", "--target", "armv7-linux-androideabi", "--features", "mobile", "${@}"]
dependencies = ["android-env"]

[tasks.android-armv8]
command = "cargo"
args = ["build", "--target", "aarch64-linux-android", "--features", "mobile", "${@}"]
dependencies = ["android-env"]

[tasks.android-x86]
command = "cargo"
args = ["build", "--target", "x86_64-linux-android", "--features", "mobile", "${@}"]
dependencies = ["android-env"]

[tasks.android-i686]
command = "cargo"
args = ["build", "--target", "i686-linux-android", "--features", "mobile", "${@}"]
dependencies = ["android-env"]

[tasks.android]
dependencies = ["android-armv7", "android-armv8", "android-x86", "android-i686"]

[tasks.setup-sample-project]
dependencies = ["android"]
script_runner = "@duckscript"
script = '''
handle = map
map_put ${handle} "i686-linux-android" "x86"
map_put ${handle} "x86_64-linux-android" "x86_64"
map_put ${handle} "aarch64-linux-android" "arm64-v8a"
map_put ${handle} "armv7-linux-androideabi" "armeabi-v7a"
keys = map_keys ${handle}
libname = set "libcore_crypto_ffi.so"
for rust_target in ${keys}
    android_target = map_get ${handle} ${rust_target}
    println -c bright_blue "cp rust-${rust_target}/${libname} -> android-jniLibs/${android_target}/${libname}"
    from = canonicalize "../target/${rust_target}/debug/${libname}"
    to = canonicalize "../sample-projects/android/CoreCryptoTestApp/app/src/main/jniLibs/${android_target}/${libname}"
    mkdir dirname ${to}
    cp ${from} ${to}
end
'''

#################################### Mobile ###################################
[tasks.mobile]
dependencies = ["android", "ios"]

####################################  all  ####################################
[tasks.all]
dependencies = ["mobile", "wasm"]

################################### Plugins ###################################
[plugins.impl.detect-release]
script = '''
index = array_contains ${task.args} "--release"
if index
    set_env IS_RELEASE_BUILD "release"
    println -c bright_blue "Release mode detected!"
end

release_path = set IS_RELEASE_BUILD or "debug"

# index_target = array_contains ${task.args} "--target"
# if index_target
#     target = array_get ${task.args} ${${index_target} + 1}
#     set_env CORECRYPTO_TARGET_FOLDER "../target/${target}/${release_path}"
# else
#     set_env CORECRYPTO_TARGET_FOLDER "../target/${release_path}"
# end
'''

[plugins.impl.android-env]
script = '''
exit_on_error true

fn update_android_env
    android_ndk_path = set "${1}/toolchains/llvm/prebuilt/linux-x86_64/bin"
    new_path = set "${PATH}:${android_ndk_path}"
    print -c bright_blue "Updating PATH to include ${android_ndk_path}\n"
    set_env PATH "${new_path}"
end

fn autodetect_android_env
    if not is_empty ${ANDROID_NDK_HOME}
        return ${ANDROID_NDK_HOME}
    elseif not is_empty ${NDK_HOME}
        return ${NDK_HOME}
    else
        platform = os_family
        if eq ${platform} "windows"
            platform_dir = set "${get_home_dir}/AppData/Local"
        elseif eq ${platform} "linux"
            platform_dir = get_home_dir
        elseif eq ${platform} "mac"
            platform_dir = set "${get_home_dir}/Library"
        else
            trigger_error "Unsupported host platform"
        end

        ndk_versions_hwnd = glob_array "${platform_dir}/Android/Sdk/ndk/*"
        for path in ${ndk_versions_hwnd}
            ndk_latest_version = set ${path}
        end
        print -c bright_blue "Autodetected NDK: host:${platform} @ v${ndk_latest_version}\n"
        return ${ndk_latest_version}
    end
end

if starts_with ${task.name} "android"
    ndk_home_dir = autodetect_android_env
    print -c bright_blue "NDK Home Dir: ${ndk_home_dir}\n"
    if is_empty ${ndk_home_dir}
        trigger_error "$ANDROID_NDK_HOME/$NDK_HOME haven't been set and/or NDK couldn't be found in the Android Studio directories.\nPlease set it correctly to target your NDK installation"
    else
        update_android_env ${ndk_home_dir}
    end
end
'''
