[bindings.kotlin]
android = true
android_cleaner = true

[bindings.kotlin.custom_types.KotlinInstant]
imports = [
  "kotlin.time.Instant",
  "kotlin.time.toKotlinInstant",
  "kotlin.time.toJavaInstant",
]
type_name = "Instant"
lift = "{}.toKotlinInstant()"
lower = "{}.toJavaInstant()"
