use zeroize::Zeroize;

use crate::traits::{KeyType, OwnedKeyType, PrimaryKey};

/// Typesafe reference to a conversation id.
///
/// [`MlsPendingMessage`]s have no distinct primary key; they must always be accessed via
/// collective accessors. This type makes that possible.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, derive_more::AsRef, derive_more::Deref, derive_more::From,
)]
pub struct ConversationId<'a>(&'a [u8]);

impl<'a> KeyType for ConversationId<'a> {
    fn bytes(&self) -> std::borrow::Cow<'_, [u8]> {
        self.0.into()
    }
}

/// [`MlsPendingMessage`]s have no distinct primary key;
/// they must always be accessed via the [`SearchableEntity`][crate::traits::SearchableEntity] and
/// [`DeletableBySearchKey`][crate::traits::DeletableBySearchKey] traits.
///
/// However the keystore's support of internal transactions demands a primary key:
/// ultimately that structure boils down to `Map<CollectionName, Map<PrimaryKey, Entity>>`, so anything other
/// than a full primary key just breaks things.
///
/// We use `xxhash3` as a fast hash implementation, and take 128 bits of hash to ensure
/// that the chance of a collision is effectively 0.
pub struct MlsPendingMessagePrimaryKey(u128);

impl From<&MlsPendingMessage> for MlsPendingMessagePrimaryKey {
    fn from(value: &MlsPendingMessage) -> Self {
        let mut hasher = twox_hash::xxhash3_128::Hasher::new();
        hasher.write(&value.foreign_id);
        hasher.write(&value.message);
        Self(hasher.finish_128())
    }
}

impl KeyType for MlsPendingMessagePrimaryKey {
    fn bytes(&self) -> std::borrow::Cow<'_, [u8]> {
        self.0.to_be_bytes().as_slice().to_owned().into()
    }
}

impl OwnedKeyType for MlsPendingMessagePrimaryKey {
    fn from_bytes(bytes: &[u8]) -> Option<Self> {
        let array = bytes.try_into().ok()?;
        Some(Self(u128::from_be_bytes(array)))
    }
}

/// Entity representing a buffered message
#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, Zeroize, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
pub struct MlsPendingMessage {
    #[sensitive]
    pub foreign_id: Vec<u8>,
    pub message: Vec<u8>,
}

impl PrimaryKey for MlsPendingMessage {
    type PrimaryKey = MlsPendingMessagePrimaryKey;
    fn primary_key(&self) -> Self::PrimaryKey {
        self.into()
    }
}

impl crate::traits::UnifiedEntity for MlsPendingMessage {
    const COLLECTION_NAME: &'static str = "mls_pending_messages";

    fn get(
        _conn: &rusqlite::Connection,
        _key: &MlsPendingMessagePrimaryKey,
    ) -> crate::CryptoKeystoreResult<Option<Self>> {
        panic!("cannot get `MlsPendingMessage` by primary key as it has no distinct primary key")
    }

    fn count(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<Vec<Self>> {
        crate::entities::helpers::load_all_helper(conn, |row| {
            Ok(Self {
                foreign_id: row.get("id")?,
                message: row.get("message")?,
            })
        })
    }
}

impl crate::traits::UnifiedEntityDatabaseMutation for MlsPendingMessage {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached("INSERT INTO mls_pending_messages (id, message) VALUES (?, ?)")?;
        stmt.execute(rusqlite::params![self.foreign_id, self.message])?;
        Ok(())
    }

    fn count(tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper_tx::<Self>(tx)
    }

    fn delete(_tx: &rusqlite::Transaction, _id: &MlsPendingMessagePrimaryKey) -> crate::CryptoKeystoreResult<bool> {
        panic!("cannot delete `MlsPendingMessage` by primary key as it has no distinct primary key")
    }
}

impl<'a> crate::traits::UnifiedSearchableEntity<ConversationId<'a>> for MlsPendingMessage {
    fn find_all_matching(
        conn: &rusqlite::Connection,
        conversation_id: &ConversationId<'a>,
    ) -> crate::CryptoKeystoreResult<Vec<Self>> {
        let conversation_id = *conversation_id.as_ref();
        let mut stmt = conn.prepare_cached("SELECT * FROM mls_pending_messages WHERE id = ?")?;
        stmt.query_map([conversation_id], |row| {
            Ok(Self {
                foreign_id: row.get("id")?,
                message: row.get("message")?,
            })
        })?
        .collect::<Result<_, _>>()
        .map_err(Into::into)
    }

    fn matches(&self, conversation_id: &ConversationId<'a>) -> bool {
        *conversation_id.as_ref() == self.foreign_id.as_slice()
    }
}

impl<'a> crate::traits::UnifiedDeletableBySearchKey<ConversationId<'a>> for MlsPendingMessage {
    fn delete_all_matching(
        tx: &rusqlite::Transaction,
        conversation_id: &ConversationId<'a>,
    ) -> crate::CryptoKeystoreResult<()> {
        crate::entities::helpers::delete_helper::<Self>(tx, "id", *conversation_id.as_ref())?;
        Ok(())
    }
}
