use zeroize::Zeroize;

use crate::{
    Sha256Hash,
    entities::{
        ConversationId,
        helpers::{count_helper, delete_helper, get_helper, load_all_helper},
    },
    traits::PrimaryKey,
};

/// Entity representing a buffered message
///
/// A message is buffered when it cannot be decrypted yet, which happens in two unrelated situations: the
/// conversation was joined by external commit and that join has not been merged, or the conversation is
/// fully established but the message belongs to epoch `n + 1` while we are still in epoch `n`. The first
/// kind of conversation is stored in `mls_pending_groups` and the second in `mls_groups`, so
/// `conversation_id` carries no foreign key — there is no single parent table for it to reference.
///
/// This entity cannot be updated in the DB: the primary key is formed of a hash of all the rest
/// of the data, so duplicate save attempts silently succeed without changing anything.
#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, Zeroize, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
pub struct MlsPendingMessage {
    pub conversation_id: Vec<u8>,
    #[sensitive]
    pub message: Vec<u8>,
}

impl MlsPendingMessage {
    const PRIMARY_KEY_COLUMN_NAME: &str = "hash_sha256";

    fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            conversation_id: row.get("conversation_id")?,
            message: row.get("message")?,
        })
    }
}

impl PrimaryKey for MlsPendingMessage {
    type PrimaryKey = Sha256Hash;
    fn primary_key(&self) -> Self::PrimaryKey {
        // Hashing the fields in sequence is equivalent to hashing their concatenation, so without a
        // delimiter the boundary between them is ambiguous: `("ab", "c")` and `("a", "bc")` would
        // share a primary key. A big-endian `u64` length prefix on the conversation id fixes the
        // boundary. The message needs no prefix, as nothing follows it.
        let conversation_id_len = (self.conversation_id.len() as u64).to_be_bytes();
        Sha256Hash::hash_from_many([conversation_id_len.as_slice(), &self.conversation_id, &self.message])
    }
}

impl crate::traits::Entity for MlsPendingMessage {
    const TABLE_NAME: &'static str = "mls_pending_messages";

    fn get(conn: &rusqlite::Connection, key: &Sha256Hash) -> crate::CryptoKeystoreResult<Option<Self>> {
        get_helper(conn, Self::PRIMARY_KEY_COLUMN_NAME, key, Self::from_row)
    }

    fn count(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<u32> {
        count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<Vec<Self>> {
        load_all_helper(conn, |row| {
            Ok(Self {
                conversation_id: row.get("conversation_id")?,
                message: row.get("message")?,
            })
        })
    }
}

impl crate::traits::EntityDatabaseMutation for MlsPendingMessage {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<()> {
        // The primary key is a hash of the other two columns, so a conflict means this exact row
        // already exists and there is nothing to write. `IGNORE` rather than `REPLACE` because
        // replacing would delete and reinsert an identical row to no purpose.
        let mut stmt = tx.prepare_cached(
            "INSERT OR IGNORE INTO mls_pending_messages (hash_sha256, conversation_id, message) VALUES (?, ?, ?)",
        )?;
        stmt.execute(rusqlite::params![
            self.primary_key(),
            self.conversation_id,
            self.message
        ])?;
        Ok(())
    }

    fn delete(tx: &rusqlite::Transaction, primary_key: &Sha256Hash) -> crate::CryptoKeystoreResult<bool> {
        delete_helper::<Self>(tx, Self::PRIMARY_KEY_COLUMN_NAME, primary_key)
    }
}

impl crate::traits::SearchableEntity<ConversationId> for MlsPendingMessage {
    fn find_all_matching(
        conn: &rusqlite::Connection,
        conversation_id: &ConversationId,
    ) -> crate::CryptoKeystoreResult<Vec<Self>> {
        let mut stmt = conn.prepare_cached("SELECT * FROM mls_pending_messages WHERE conversation_id = ?")?;
        stmt.query_map([&**conversation_id], Self::from_row)?
            .collect::<Result<_, _>>()
            .map_err(Into::into)
    }

    fn matches(&self, conversation_id: &ConversationId) -> bool {
        &**conversation_id == self.conversation_id.as_slice()
    }
}

impl crate::traits::DeletableBySearchKey<ConversationId> for MlsPendingMessage {
    fn delete_all_matching(
        tx: &rusqlite::Transaction,
        conversation_id: &ConversationId,
    ) -> crate::CryptoKeystoreResult<()> {
        delete_helper::<Self>(tx, "conversation_id", &**conversation_id)?;
        Ok(())
    }
}

#[cfg(all(test, not(target_os = "unknown")))]
mod tests {
    use futures_lite::future;

    use super::*;
    use crate::{Database, traits::FetchFromDatabase as _};

    const CONVERSATION_ID: &[u8] = b"conversation which buffers a message";
    const MESSAGE: &[u8] = b"a message which arrived before we could decrypt it";

    fn pending_message() -> MlsPendingMessage {
        MlsPendingMessage {
            conversation_id: CONVERSATION_ID.to_owned(),
            message: MESSAGE.to_owned(),
        }
    }

    /// A buffered message can be committed for a conversation which is not a pending group.
    ///
    /// This table serves two unrelated callers. One is a conversation joined by external commit and not
    /// yet merged, which lives in `mls_pending_groups`; the other is a fully established conversation
    /// buffering a message from epoch `n + 1`, which lives in `mls_groups` and has no pending group row at
    /// all. Up to and including V30 the table carried a foreign key onto `mls_pending_groups`, which the
    /// second caller could never satisfy, so its saves failed at commit with `FOREIGN KEY constraint
    /// failed`. V31 drops that constraint, and its comment explains why at length.
    ///
    /// Every other test here now exercises the same conversation shape, so this property is covered
    /// several times over. It gets a test of its own regardless: nothing in the schema records the
    /// relationship between a buffered message and its conversation any more, so this is the only place
    /// which states that a conversation absent from `mls_pending_groups` is legitimate.
    #[test]
    fn can_save_a_pending_message_for_a_conversation_which_is_not_a_pending_group() {
        future::block_on(async {
            let store = Database::open_in_memory().unwrap();
            let primary_key = pending_message().primary_key();

            let tx = store.new_transaction().await.unwrap();
            tx.save(pending_message()).await.unwrap();
            tx.commit().await.unwrap();

            assert_eq!(
                store.get::<MlsPendingMessage>(&primary_key).await.unwrap().as_deref(),
                Some(&pending_message()),
                "a buffered message must survive commit even though its conversation is not a pending group"
            );
        });
    }

    /// A saved pending message can be read back by the primary key derived from its own fields.
    ///
    /// This is the property the `hash_sha256` primary key exists to provide: before it, the table
    /// had no primary key at all and pending messages could only be reached collectively, via
    /// [`ConversationId`].
    #[test]
    fn can_get_a_saved_pending_message_by_primary_key() {
        future::block_on(async {
            let store = Database::open_in_memory().unwrap();
            let expected = pending_message();
            let primary_key = expected.primary_key();

            let tx = store.new_transaction().await.unwrap();
            tx.save(pending_message()).await.unwrap();
            tx.commit().await.unwrap();

            let fetched = store
                .get::<MlsPendingMessage>(&primary_key)
                .await
                .unwrap()
                .expect("the pending message was committed, so it must be gettable by primary key");
            assert_eq!(*fetched, expected);
        });
    }

    /// Deleting by primary key removes exactly that pending message and leaves its siblings alone.
    ///
    /// The second message shares a conversation id with the first, so a deletion which fell back to
    /// the [`ConversationId`] search key would take both rows with it.
    #[test]
    fn can_delete_a_pending_message_by_primary_key() {
        future::block_on(async {
            let store = Database::open_in_memory().unwrap();
            let sibling = MlsPendingMessage {
                conversation_id: CONVERSATION_ID.to_owned(),
                message: b"a second buffered message in the same conversation".to_vec(),
            };
            let doomed_key = pending_message().primary_key();
            let sibling_key = sibling.primary_key();

            let tx = store.new_transaction().await.unwrap();
            tx.save(pending_message()).await.unwrap();
            tx.save(sibling).await.unwrap();
            tx.commit().await.unwrap();
            assert_eq!(store.count::<MlsPendingMessage>().await.unwrap(), 2);

            let tx = store.new_transaction().await.unwrap();
            tx.remove::<MlsPendingMessage>(&doomed_key).await.unwrap();
            tx.commit().await.unwrap();

            assert!(
                store.get::<MlsPendingMessage>(&doomed_key).await.unwrap().is_none(),
                "the message deleted by primary key must be gone"
            );
            assert!(
                store.get::<MlsPendingMessage>(&sibling_key).await.unwrap().is_some(),
                "deleting by primary key must not touch other messages in the same conversation"
            );
            assert_eq!(store.count::<MlsPendingMessage>().await.unwrap(), 1);
        });
    }

    /// Deleting collectively by [`ConversationId`] still takes out every message in the conversation.
    ///
    /// Deletion by primary key and deletion by conversation id reach the database by different
    /// routes, so exercising one says nothing about the other.
    #[test]
    fn can_delete_all_pending_messages_of_a_conversation() {
        future::block_on(async {
            let store = Database::open_in_memory().unwrap();

            let tx = store.new_transaction().await.unwrap();
            tx.save(pending_message()).await.unwrap();
            tx.save(MlsPendingMessage {
                conversation_id: CONVERSATION_ID.to_owned(),
                message: b"a second buffered message in the same conversation".to_vec(),
            })
            .await
            .unwrap();
            tx.commit().await.unwrap();
            assert_eq!(store.count::<MlsPendingMessage>().await.unwrap(), 2);

            let tx = store.new_transaction().await.unwrap();
            tx.bulk_remove::<MlsPendingMessage, _>(CONVERSATION_ID.into()).await;
            tx.commit().await.unwrap();

            assert_eq!(store.count::<MlsPendingMessage>().await.unwrap(), 0);
        });
    }

    /// A bulk deletion cancels a save which preceded it in the same transaction.
    ///
    /// Saves and bulk deletions are buffered in disjoint structures within the transaction, so
    /// nothing about the buffering enforces their relative order; only their composition does. A
    /// caller who saves and then clears the conversation has expressed the same intent as one who
    /// did both against the database directly, and must get the same result: nothing.
    #[test]
    fn bulk_deletion_removes_a_pending_message_saved_earlier_in_the_transaction() {
        future::block_on(async {
            let store = Database::open_in_memory().unwrap();
            let primary_key = pending_message().primary_key();

            let tx = store.new_transaction().await.unwrap();
            tx.save(pending_message()).await.unwrap();
            tx.bulk_remove::<MlsPendingMessage, _>(CONVERSATION_ID.into()).await;
            tx.commit().await.unwrap();

            assert!(
                store.get::<MlsPendingMessage>(&primary_key).await.unwrap().is_none(),
                "the save was cancelled by the later bulk deletion, so nothing should have been committed"
            );
            assert_eq!(store.count::<MlsPendingMessage>().await.unwrap(), 0);
        });
    }

    /// A save survives a bulk deletion which preceded it in the same transaction.
    ///
    /// This is the mirror image of
    /// [`bulk_deletion_removes_a_pending_message_saved_earlier_in_the_transaction`]: clearing a
    /// conversation and then buffering a new message for it is a perfectly ordinary sequence, and
    /// the new message is not one of the messages the caller asked to clear.
    #[test]
    fn a_pending_message_saved_after_a_bulk_deletion_survives_it() {
        future::block_on(async {
            let store = Database::open_in_memory().unwrap();
            let stale = pending_message();
            let stale_key = stale.primary_key();
            let fresh = MlsPendingMessage {
                conversation_id: CONVERSATION_ID.to_owned(),
                message: b"a message buffered after the conversation was cleared".to_vec(),
            };
            let fresh_key = fresh.primary_key();

            // persist a message in an earlier transaction, so the bulk deletion has something to do
            let tx = store.new_transaction().await.unwrap();
            tx.save(stale).await.unwrap();
            tx.commit().await.unwrap();

            let tx = store.new_transaction().await.unwrap();
            tx.bulk_remove::<MlsPendingMessage, _>(CONVERSATION_ID.into()).await;
            tx.save(fresh).await.unwrap();
            tx.commit().await.unwrap();

            assert!(
                store.get::<MlsPendingMessage>(&fresh_key).await.unwrap().is_some(),
                "the save came after the bulk deletion, so it must not have been swept up by it"
            );
            assert!(
                store.get::<MlsPendingMessage>(&stale_key).await.unwrap().is_none(),
                "the message which predated the bulk deletion must still be gone"
            );
            assert_eq!(store.count::<MlsPendingMessage>().await.unwrap(), 1);
        });
    }

    /// A bulk deletion masks already-persisted messages from reads within the same transaction.
    ///
    /// The write side of this composes correctly: a bulk deletion drops matching saves from the
    /// cache. The read side has to match, or the transaction reports rows it is about to delete.
    /// Reads consult the set of entities deleted by primary key, which a bulk deletion by
    /// conversation id never populates, so a persisted message is masked by neither route.
    #[test]
    fn bulk_deletion_hides_persisted_messages_from_reads_in_the_same_transaction() {
        future::block_on(async {
            let store = Database::open_in_memory().unwrap();
            let primary_key = pending_message().primary_key();

            // persist the message in an earlier transaction, so it is on disk rather than cached
            let tx = store.new_transaction().await.unwrap();
            tx.save(pending_message()).await.unwrap();
            tx.commit().await.unwrap();

            let tx = store.new_transaction().await.unwrap();
            tx.bulk_remove::<MlsPendingMessage, _>(CONVERSATION_ID.into()).await;

            let found = store
                .search::<MlsPendingMessage, _>(&CONVERSATION_ID.into())
                .await
                .unwrap();
            assert!(
                found.is_empty(),
                "the conversation was cleared in this transaction, so searching it must find nothing"
            );
            assert!(
                store.get::<MlsPendingMessage>(&primary_key).await.unwrap().is_none(),
                "a message the transaction has cleared must not be gettable by its primary key either"
            );

            // and the read must have told the truth about what commit does
            tx.commit().await.unwrap();
            assert_eq!(store.count::<MlsPendingMessage>().await.unwrap(), 0);
        });
    }
}
