use zeroize::Zeroize;

use crate::{
    Sha256Hash,
    entities::helpers::{count_helper, delete_helper, get_helper, load_all_helper},
    traits::{KeyType, PrimaryKey},
};

/// Typesafe reference to a conversation id.
///
/// [`MlsPendingMessage`]s are keyed individually by a hash of their contents, but callers almost
/// always want every buffered message of one conversation at once. This type is the search key
/// which makes that possible.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, derive_more::AsRef, derive_more::Deref, derive_more::From,
)]
pub struct ConversationId<'a>(&'a [u8]);

impl<'a> KeyType for ConversationId<'a> {
    fn bytes(&self) -> std::borrow::Cow<'_, [u8]> {
        self.0.into()
    }
}

/// Entity representing a buffered message
#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, Zeroize, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
pub struct MlsPendingMessage {
    pub conversation_id: Vec<u8>,
    #[sensitive]
    pub message: Vec<u8>,
}

impl MlsPendingMessage {
    const PRIMARY_KEY_COLUMN_NAME: &str = "hash_sha256";

    fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            conversation_id: row.get("conversation_id")?,
            message: row.get("message")?,
        })
    }
}

impl PrimaryKey for MlsPendingMessage {
    type PrimaryKey = Sha256Hash;
    fn primary_key(&self) -> Self::PrimaryKey {
        // Hashing the fields in sequence is equivalent to hashing their concatenation, so without a
        // delimiter the boundary between them is ambiguous: `("ab", "c")` and `("a", "bc")` would
        // share a primary key. A big-endian `u64` length prefix on the conversation id fixes the
        // boundary. The message needs no prefix, as nothing follows it.
        let conversation_id_len = (self.conversation_id.len() as u64).to_be_bytes();
        Sha256Hash::hash_from_many([conversation_id_len.as_slice(), &self.conversation_id, &self.message])
    }
}

impl crate::traits::Entity for MlsPendingMessage {
    const TABLE_NAME: &'static str = "mls_pending_messages";

    fn get(conn: &rusqlite::Connection, key: &Sha256Hash) -> crate::CryptoKeystoreResult<Option<Self>> {
        get_helper(conn, Self::PRIMARY_KEY_COLUMN_NAME, key, Self::from_row)
    }

    fn count(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<u32> {
        count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<Vec<Self>> {
        load_all_helper(conn, |row| {
            Ok(Self {
                conversation_id: row.get("conversation_id")?,
                message: row.get("message")?,
            })
        })
    }
}

impl crate::traits::EntityDatabaseMutation for MlsPendingMessage {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<()> {
        // The primary key is a hash of the other two columns, so a conflict means this exact row
        // already exists and there is nothing to write. `IGNORE` rather than `REPLACE` because
        // replacing would delete and reinsert an identical row to no purpose.
        let mut stmt = tx.prepare_cached(
            "INSERT OR IGNORE INTO mls_pending_messages (hash_sha256, conversation_id, message) VALUES (?, ?, ?)",
        )?;
        stmt.execute(rusqlite::params![
            self.primary_key(),
            self.conversation_id,
            self.message
        ])?;
        Ok(())
    }

    fn delete(tx: &rusqlite::Transaction, primary_key: &Sha256Hash) -> crate::CryptoKeystoreResult<bool> {
        delete_helper::<Self>(tx, Self::PRIMARY_KEY_COLUMN_NAME, primary_key)
    }
}

impl<'a> crate::traits::SearchableEntity<ConversationId<'a>> for MlsPendingMessage {
    fn find_all_matching(
        conn: &rusqlite::Connection,
        conversation_id: &ConversationId<'a>,
    ) -> crate::CryptoKeystoreResult<Vec<Self>> {
        let conversation_id = *conversation_id.as_ref();
        let mut stmt = conn.prepare_cached("SELECT * FROM mls_pending_messages WHERE conversation_id = ?")?;
        stmt.query_map([conversation_id], Self::from_row)?
            .collect::<Result<_, _>>()
            .map_err(Into::into)
    }

    fn matches(&self, conversation_id: &ConversationId<'a>) -> bool {
        *conversation_id.as_ref() == self.conversation_id.as_slice()
    }
}

impl<'a> crate::traits::DeletableBySearchKey<ConversationId<'a>> for MlsPendingMessage {
    fn delete_all_matching(
        tx: &rusqlite::Transaction,
        conversation_id: &ConversationId<'a>,
    ) -> crate::CryptoKeystoreResult<()> {
        delete_helper::<Self>(tx, "conversation_id", *conversation_id.as_ref())?;
        Ok(())
    }
}
