use zeroize::Zeroize;

/// Entity representing a temporarily persisted `MlsGroup`
#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, Zeroize, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
pub struct PersistedMlsPendingGroup {
    #[sensitive]
    pub id: Vec<u8>,
    #[sensitive]
    pub state: Vec<u8>,
    #[sensitive]
    pub parent_id: Option<Vec<u8>>,
    pub custom_configuration: Vec<u8>,
}

impl crate::traits::UnifiedEntity for PersistedMlsPendingGroup {
    const COLLECTION_NAME: &'static str = "mls_pending_groups";

    fn get(conn: &rusqlite::Connection, key: &Vec<u8>) -> crate::CryptoKeystoreResult<Option<Self>> {
        crate::entities::helpers::get_helper(conn, "id", key.as_slice(), |row| {
            Ok(Self {
                id: row.get("id")?,
                state: row.get("state")?,
                parent_id: row.get("parent_id")?,
                custom_configuration: row.get("cfg")?,
            })
        })
    }

    fn count(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<Vec<Self>> {
        crate::entities::helpers::load_all_helper(conn, |row| {
            Ok(Self {
                id: row.get("id")?,
                state: row.get("state")?,
                parent_id: row.get("parent_id")?,
                custom_configuration: row.get("cfg")?,
            })
        })
    }
}

impl crate::traits::UnifiedEntityGetBorrowed for PersistedMlsPendingGroup {
    fn get_borrowed(conn: &rusqlite::Connection, key: &[u8]) -> crate::CryptoKeystoreResult<Option<Self>>
    where
        for<'pk> &'pk [u8]: crate::traits::KeyType,
    {
        crate::entities::helpers::get_helper(conn, "id", key, |row| {
            Ok(Self {
                id: row.get("id")?,
                state: row.get("state")?,
                parent_id: row.get("parent_id")?,
                custom_configuration: row.get("cfg")?,
            })
        })
    }
}

impl crate::traits::UnifiedEntityDatabaseMutation for PersistedMlsPendingGroup {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached(
            "INSERT OR REPLACE INTO mls_pending_groups (id, state, parent_id, cfg) VALUES (?, ?, ?, ?)",
        )?;
        stmt.execute(rusqlite::params![
            self.id,
            self.state,
            self.parent_id,
            self.custom_configuration
        ])?;
        Ok(())
    }

    fn count(tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper_tx::<Self>(tx)
    }

    fn delete(tx: &rusqlite::Transaction, id: &Vec<u8>) -> crate::CryptoKeystoreResult<bool> {
        crate::entities::helpers::delete_helper::<Self>(tx, "id", id.as_slice())
    }
}

impl crate::traits::UnifiedEntityDeleteBorrowed for PersistedMlsPendingGroup {
    fn delete_borrowed(tx: &rusqlite::Transaction, id: &[u8]) -> crate::CryptoKeystoreResult<bool>
    where
        for<'pk> &'pk [u8]: crate::traits::KeyType,
    {
        crate::entities::helpers::delete_helper::<Self>(tx, "id", id)
    }
}
