use zeroize::Zeroize;

/// Entity representing a persisted `HpkePrivateKey` (related to LeafNode Private keys that the client is aware of)
#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, Zeroize, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
#[sensitive]
pub struct StoredHpkePrivateKey {
    pub sk: Vec<u8>,
    pub pk: Vec<u8>,
}

impl crate::traits::UnifiedEntity for StoredHpkePrivateKey {
    const COLLECTION_NAME: &'static str = "mls_hpke_private_keys";

    fn get(conn: &rusqlite::Connection, key: &Vec<u8>) -> crate::CryptoKeystoreResult<Option<Self>> {
        let hash = crate::Sha256Hash::hash_from(key);
        crate::entities::helpers::get_helper(conn, "pk_sha256", hash, |row| {
            Ok(Self {
                pk: row.get("pk")?,
                sk: row.get("sk")?,
            })
        })
    }

    fn count(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<Vec<Self>> {
        crate::entities::helpers::load_all_helper(conn, |row| {
            Ok(Self {
                pk: row.get("pk")?,
                sk: row.get("sk")?,
            })
        })
    }
}

impl crate::traits::UnifiedEntityGetBorrowed for StoredHpkePrivateKey {
    fn get_borrowed(conn: &rusqlite::Connection, key: &[u8]) -> crate::CryptoKeystoreResult<Option<Self>>
    where
        for<'pk> &'pk [u8]: crate::traits::KeyType,
    {
        let hash = crate::Sha256Hash::hash_from(key);
        crate::entities::helpers::get_helper(conn, "pk_sha256", hash, |row| {
            Ok(Self {
                pk: row.get("pk")?,
                sk: row.get("sk")?,
            })
        })
    }
}

impl crate::traits::UnifiedEntityDatabaseMutation for StoredHpkePrivateKey {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<()> {
        let hash = crate::Sha256Hash::hash_from(&self.pk);
        let mut stmt =
            tx.prepare_cached("INSERT OR REPLACE INTO mls_hpke_private_keys (pk_sha256, pk, sk) VALUES (?, ?, ?)")?;
        stmt.execute(rusqlite::params![hash, self.pk, self.sk])?;
        Ok(())
    }

    fn count(tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper_tx::<Self>(tx)
    }

    fn delete(tx: &rusqlite::Transaction, id: &Vec<u8>) -> crate::CryptoKeystoreResult<bool> {
        let hash = crate::Sha256Hash::hash_from(id);
        crate::entities::helpers::delete_helper::<Self>(tx, "pk_sha256", hash)
    }
}

impl crate::traits::UnifiedEntityDeleteBorrowed for StoredHpkePrivateKey {
    fn delete_borrowed(tx: &rusqlite::Transaction, id: &[u8]) -> crate::CryptoKeystoreResult<bool>
    where
        for<'pk> &'pk [u8]: crate::traits::KeyType,
    {
        let hash = crate::Sha256Hash::hash_from(id);
        crate::entities::helpers::delete_helper::<Self>(tx, "pk_sha256", hash)
    }
}
