use zeroize::Zeroize;

/// Entity representing a persisted PSK Bundle
#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, Zeroize, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
#[sensitive]
pub struct StoredPskBundle {
    pub psk_id: Vec<u8>,
    pub psk: Vec<u8>,
}

impl crate::traits::UnifiedEntity for StoredPskBundle {
    const COLLECTION_NAME: &'static str = "mls_psk_bundles";

    fn get(conn: &rusqlite::Connection, key: &Vec<u8>) -> crate::CryptoKeystoreResult<Option<Self>> {
        let hash = crate::Sha256Hash::hash_from(key);
        crate::entities::helpers::get_helper(conn, "id_sha256", hash, |row| {
            Ok(Self {
                psk_id: row.get("psk_id")?,
                psk: row.get("psk")?,
            })
        })
    }

    fn count(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<Vec<Self>> {
        crate::entities::helpers::load_all_helper(conn, |row| {
            Ok(Self {
                psk_id: row.get("psk_id")?,
                psk: row.get("psk")?,
            })
        })
    }
}

impl crate::traits::UnifiedEntityGetBorrowed for StoredPskBundle {
    fn get_borrowed(conn: &rusqlite::Connection, key: &[u8]) -> crate::CryptoKeystoreResult<Option<Self>>
    where
        for<'pk> &'pk [u8]: crate::traits::KeyType,
    {
        let hash = crate::Sha256Hash::hash_from(key);
        crate::entities::helpers::get_helper(conn, "id_sha256", hash, |row| {
            Ok(Self {
                psk_id: row.get("psk_id")?,
                psk: row.get("psk")?,
            })
        })
    }
}

impl crate::traits::UnifiedEntityDatabaseMutation for StoredPskBundle {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<()> {
        let hash = crate::Sha256Hash::hash_from(&self.psk_id);
        let mut stmt =
            tx.prepare_cached("INSERT OR REPLACE INTO mls_psk_bundles (id_sha256, psk_id, psk) VALUES (?, ?, ?)")?;
        stmt.execute(rusqlite::params![hash, self.psk_id, self.psk])?;
        Ok(())
    }

    fn count(tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<u32> {
        crate::entities::helpers::count_helper_tx::<Self>(tx)
    }

    fn delete(tx: &rusqlite::Transaction, id: &Vec<u8>) -> crate::CryptoKeystoreResult<bool> {
        let hash = crate::Sha256Hash::hash_from(id);
        crate::entities::helpers::delete_helper::<Self>(tx, "id_sha256", hash)
    }
}

impl crate::traits::UnifiedEntityDeleteBorrowed for StoredPskBundle {
    fn delete_borrowed(tx: &rusqlite::Transaction, id: &[u8]) -> crate::CryptoKeystoreResult<bool>
    where
        for<'pk> &'pk [u8]: crate::traits::KeyType,
    {
        let hash = crate::Sha256Hash::hash_from(id);
        crate::entities::helpers::delete_helper::<Self>(tx, "id_sha256", hash)
    }
}
