use zeroize::Zeroize;

use crate::{
    entities::{
        ConversationId,
        helpers::{count_helper, get_helper_composite_key, load_all_helper},
    },
    traits::{DeletableBySearchKey, EntityDatabaseMutation, PrimaryKey, SearchableEntity},
};

#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, Zeroize, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
pub struct TargetedMessageRxCounter {
    pub conversation_id: Vec<u8>,
    pub sender: u32,
    pub epoch: u64,
    pub count: u32,
}

#[derive(Clone, Debug, Hash, PartialEq, Eq, derive_more::Constructor)]
pub struct TargetedMessageRxCounterPk {
    conversation_id: Vec<u8>,
    sender_idx: u32,
    epoch: u64,
}

impl TargetedMessageRxCounter {
    const TABLE_NAME: &str = "targeted_message_rx_counters";
    const PRIMARY_KEY_COLUMN_NAMES: [&str; 3] = ["conversation_id", "sender", "epoch"];

    fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            conversation_id: row.get("conversation_id")?,
            sender: row.get("sender")?,
            epoch: row.get("epoch")?,
            count: row.get("count")?,
        })
    }
}

impl PrimaryKey for TargetedMessageRxCounter {
    type PrimaryKey = TargetedMessageRxCounterPk;

    fn primary_key(&self) -> Self::PrimaryKey {
        TargetedMessageRxCounterPk::new(self.conversation_id.clone(), self.sender, self.epoch)
    }
}

impl crate::traits::Entity for TargetedMessageRxCounter {
    const TABLE_NAME: &'static str = Self::TABLE_NAME;

    fn get(conn: &rusqlite::Connection, key: &TargetedMessageRxCounterPk) -> crate::CryptoKeystoreResult<Option<Self>> {
        get_helper_composite_key(
            conn,
            &Self::PRIMARY_KEY_COLUMN_NAMES,
            rusqlite::params![key.conversation_id, key.sender_idx, key.epoch],
            Self::from_row,
        )
    }

    fn count(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<u32> {
        count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<Vec<Self>> {
        load_all_helper(conn, Self::from_row)
    }
}

impl EntityDatabaseMutation for TargetedMessageRxCounter {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached(&format!(
            "INSERT OR REPLACE INTO {} (conversation_id, sender, epoch, count) VALUES (?, ?, ?, ?)",
            Self::TABLE_NAME
        ))?;
        stmt.execute(rusqlite::params![
            self.conversation_id,
            self.sender,
            self.epoch,
            self.count
        ])?;
        Ok(())
    }

    fn delete(
        tx: &rusqlite::Transaction,
        primary_key: &TargetedMessageRxCounterPk,
    ) -> crate::CryptoKeystoreResult<bool> {
        let mut stmt = tx.prepare_cached(&format!(
            "DELETE FROM {} WHERE conversation_id = ? AND sender = ? AND epoch = ?",
            Self::TABLE_NAME
        ))?;
        stmt.execute(rusqlite::params![
            primary_key.conversation_id,
            primary_key.sender_idx,
            primary_key.epoch
        ])
        .map(|affected_rows| affected_rows > 0)
        .map_err(Into::into)
    }
}

impl SearchableEntity<ConversationId> for TargetedMessageRxCounter {
    fn find_all_matching(
        conn: &rusqlite::Connection,
        conversation_id: &ConversationId,
    ) -> crate::CryptoKeystoreResult<Vec<Self>> {
        let mut stmt = conn.prepare_cached(&format!("SELECT * FROM {} WHERE conversation_id = ?", Self::TABLE_NAME))?;
        stmt.query_map([conversation_id.as_ref()], Self::from_row)?
            .collect::<Result<_, _>>()
            .map_err(Into::into)
    }

    fn matches(&self, conversation_id: &ConversationId) -> bool {
        self.conversation_id.as_slice() == conversation_id.as_ref()
    }
}

impl DeletableBySearchKey<ConversationId> for TargetedMessageRxCounter {
    fn delete_all_matching(
        tx: &rusqlite::Transaction,
        conversation_id: &ConversationId,
    ) -> crate::CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached(&format!("DELETE FROM {} WHERE conversation_id = ?", Self::TABLE_NAME))?;
        stmt.execute([conversation_id.as_ref()])?;
        Ok(())
    }
}
