use zeroize::Zeroize;

use crate::{
    CryptoKeystoreResult,
    entities::{
        ConversationEpochsOlderThan,
        helpers::{count_helper, get_helper_composite_key, load_all_helper},
    },
    traits::{
        BorrowPrimaryKey, DeletableBySearchKey, Entity, EntityDatabaseMutation, EntityDeleteBorrowed,
        EntityGetBorrowed, PrimaryKey, SearchableEntity,
    },
};

#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, Zeroize, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
pub struct TargetedMessageRxCounter {
    pub conversation_id: Vec<u8>,
    pub sender: u32,
    pub epoch: u64,
    pub count: u32,
}

#[derive(Clone, Debug, Hash, PartialEq, Eq, derive_more::Constructor)]
pub struct TargetedMessageRxCounterPk {
    conversation_id: Vec<u8>,
    sender_idx: u32,
    epoch: u64,
}

impl TargetedMessageRxCounter {
    const TABLE_NAME: &str = "targeted_message_rx_counters";
    const PRIMARY_KEY_COLUMN_NAMES: [&str; 3] = ["conversation_id", "sender", "epoch"];

    fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            conversation_id: row.get("conversation_id")?,
            sender: row.get("sender")?,
            epoch: row.get("epoch")?,
            count: row.get("count")?,
        })
    }
}

impl PrimaryKey for TargetedMessageRxCounter {
    type PrimaryKey = TargetedMessageRxCounterPk;

    fn primary_key(&self) -> Self::PrimaryKey {
        TargetedMessageRxCounterPk::new(self.conversation_id.clone(), self.sender, self.epoch)
    }
}

impl Entity for TargetedMessageRxCounter {
    const TABLE_NAME: &'static str = Self::TABLE_NAME;

    fn get(conn: &rusqlite::Connection, key: &TargetedMessageRxCounterPk) -> CryptoKeystoreResult<Option<Self>> {
        get_helper_composite_key(
            conn,
            &Self::PRIMARY_KEY_COLUMN_NAMES,
            rusqlite::params![key.conversation_id, key.sender_idx, key.epoch],
            Self::from_row,
        )
    }

    fn count(conn: &rusqlite::Connection) -> CryptoKeystoreResult<u32> {
        count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> CryptoKeystoreResult<Vec<Self>> {
        load_all_helper(conn, Self::from_row)
    }
}

impl EntityDatabaseMutation for TargetedMessageRxCounter {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached(&format!(
            "INSERT OR REPLACE INTO {} (conversation_id, sender, epoch, count) \
             VALUES (:conversation_id, :sender, :epoch, :count)",
            Self::TABLE_NAME
        ))?;
        stmt.execute(rusqlite::named_params! {
            ":conversation_id": self.conversation_id,
            ":sender": self.sender,
            ":epoch": self.epoch,
            ":count": self.count,
        })?;
        Ok(())
    }

    fn delete(tx: &rusqlite::Transaction, primary_key: &TargetedMessageRxCounterPk) -> CryptoKeystoreResult<bool> {
        let mut stmt = tx.prepare_cached(&format!(
            "DELETE FROM {} WHERE conversation_id = ? AND sender = ? AND epoch = ?",
            Self::TABLE_NAME
        ))?;
        stmt.execute(rusqlite::params![
            primary_key.conversation_id,
            primary_key.sender_idx,
            primary_key.epoch
        ])
        .map(|affected_rows| affected_rows > 0)
        .map_err(Into::into)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, derive_more::Constructor)]
pub struct TargetedMessageRxCounterPkRef<'a> {
    conversation_id: &'a [u8],
    sender_idx: u32,
    epoch: u64,
}

impl BorrowPrimaryKey for TargetedMessageRxCounter {
    type BorrowedPrimaryKey<'a> = TargetedMessageRxCounterPkRef<'a>;

    fn borrow_primary_key(&self) -> Self::BorrowedPrimaryKey<'_> {
        TargetedMessageRxCounterPkRef::new(&self.conversation_id, self.sender, self.epoch)
    }
}

impl EntityGetBorrowed for TargetedMessageRxCounter {
    fn get_borrowed(
        conn: &rusqlite::Connection,
        key: Self::BorrowedPrimaryKey<'_>,
    ) -> CryptoKeystoreResult<Option<Self>> {
        get_helper_composite_key(
            conn,
            &Self::PRIMARY_KEY_COLUMN_NAMES,
            rusqlite::params![key.conversation_id, key.sender_idx, key.epoch],
            Self::from_row,
        )
    }
}

impl EntityDeleteBorrowed for TargetedMessageRxCounter {
    fn delete_borrowed(tx: &rusqlite::Transaction, key: Self::BorrowedPrimaryKey<'_>) -> CryptoKeystoreResult<bool> {
        let mut stmt = tx.prepare_cached(&format!(
            "DELETE FROM {} WHERE conversation_id = ? AND sender = ? AND epoch = ?",
            Self::TABLE_NAME
        ))?;
        stmt.execute(rusqlite::params![key.conversation_id, key.sender_idx, key.epoch])
            .map(|affected_rows| affected_rows > 0)
            .map_err(Into::into)
    }
}

impl SearchableEntity<ConversationEpochsOlderThan> for TargetedMessageRxCounter {
    fn find_all_matching(
        conn: &rusqlite::Connection,
        conversation_epoch: &ConversationEpochsOlderThan,
    ) -> CryptoKeystoreResult<Vec<Self>> {
        let mut stmt = conn.prepare_cached(&format!(
            "SELECT * FROM {} WHERE conversation_id = ? AND epoch < ?",
            Self::TABLE_NAME
        ))?;
        stmt.query_map(
            rusqlite::params![conversation_epoch.conversation_id, conversation_epoch.epoch],
            Self::from_row,
        )?
        .collect::<Result<_, _>>()
        .map_err(Into::into)
    }

    fn matches(&self, conversation_epoch: &ConversationEpochsOlderThan) -> bool {
        self.conversation_id.as_slice() == conversation_epoch.conversation_id && self.epoch < conversation_epoch.epoch
    }
}

impl DeletableBySearchKey<ConversationEpochsOlderThan> for TargetedMessageRxCounter {
    fn delete_all_matching(
        tx: &rusqlite::Transaction,
        conversation_epoch: &ConversationEpochsOlderThan,
    ) -> CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached(&format!(
            "DELETE FROM {} WHERE conversation_id = ? AND epoch < ?",
            Self::TABLE_NAME
        ))?;
        stmt.execute(rusqlite::params![
            conversation_epoch.conversation_id,
            conversation_epoch.epoch
        ])?;
        Ok(())
    }
}

impl From<TargetedMessageRxCounterPkRef<'_>> for TargetedMessageRxCounterPk {
    fn from(key: TargetedMessageRxCounterPkRef<'_>) -> Self {
        Self::new(key.conversation_id.to_vec(), key.sender_idx, key.epoch)
    }
}
