use const_format::formatcp;
use zeroize::Zeroize;

use crate::{
    entities::{
        ConversationId, ConversationIdRef,
        helpers::{count_helper, get_helper_composite_key, load_all_helper},
    },
    traits::{DeletableBySearchKey, EntityDatabaseMutation, PrimaryKey, SearchableEntity},
};

#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, Zeroize, serde::Serialize, serde::Deserialize)]
#[zeroize(drop)]
pub struct TargetedMessageTxCounter {
    pub conversation_id: Vec<u8>,
    pub receiver: u32,
    pub count: u32,
}

#[derive(Clone, Debug, Hash, PartialEq, Eq, derive_more::Constructor)]
pub struct TargetedMessageTxCounterPk {
    conversation_id: Vec<u8>,
    receiver_idx: u32,
}

impl TargetedMessageTxCounter {
    const TABLE_NAME: &'static str = "targeted_message_tx_counters";
    const PRIMARY_KEY_COLUMN_NAMES: [&str; 2] = ["conversation_id", "receiver"];

    fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            conversation_id: row.get("conversation_id")?,
            receiver: row.get("receiver")?,
            count: row.get("count")?,
        })
    }
}

impl PrimaryKey for TargetedMessageTxCounter {
    type PrimaryKey = TargetedMessageTxCounterPk;
    fn primary_key(&self) -> Self::PrimaryKey {
        TargetedMessageTxCounterPk::new(self.conversation_id.clone(), self.receiver)
    }
}

impl crate::traits::Entity for TargetedMessageTxCounter {
    const TABLE_NAME: &'static str = Self::TABLE_NAME;

    fn get(conn: &rusqlite::Connection, key: &TargetedMessageTxCounterPk) -> crate::CryptoKeystoreResult<Option<Self>> {
        get_helper_composite_key(
            conn,
            &Self::PRIMARY_KEY_COLUMN_NAMES,
            rusqlite::params![key.conversation_id, key.receiver_idx],
            Self::from_row,
        )
    }

    fn count(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<u32> {
        count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> crate::CryptoKeystoreResult<Vec<Self>> {
        load_all_helper(conn, Self::from_row)
    }
}

impl EntityDatabaseMutation for TargetedMessageTxCounter {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> crate::CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached(formatcp!(
            "INSERT OR REPLACE INTO {} (conversation_id, receiver, count) VALUES (?, ?, ?)",
            TargetedMessageTxCounter::TABLE_NAME
        ))?;
        stmt.execute(rusqlite::params![self.conversation_id, self.receiver, self.count])?;
        Ok(())
    }

    fn delete(
        tx: &rusqlite::Transaction,
        primary_key: &TargetedMessageTxCounterPk,
    ) -> crate::CryptoKeystoreResult<bool> {
        let mut stmt = tx.prepare_cached(formatcp!(
            "DELETE FROM {} WHERE conversation_id = ? AND receiver = ?",
            TargetedMessageTxCounter::TABLE_NAME
        ))?;
        stmt.execute(rusqlite::params![primary_key.conversation_id, primary_key.receiver_idx])
            .map(|affected_rows| affected_rows > 0)
            .map_err(Into::into)
    }
}

impl SearchableEntity<ConversationIdRef> for TargetedMessageTxCounter {
    fn find_all_matching(
        conn: &rusqlite::Connection,
        conversation_id: &ConversationIdRef,
    ) -> crate::CryptoKeystoreResult<Vec<Self>> {
        let mut stmt = conn.prepare_cached(formatcp!(
            "SELECT * FROM {} WHERE conversation_id = ?",
            TargetedMessageTxCounter::TABLE_NAME
        ))?;
        stmt.query_map([conversation_id], Self::from_row)?
            .collect::<Result<_, _>>()
            .map_err(Into::into)
    }

    fn matches(&self, conversation_id: &ConversationIdRef) -> bool {
        self.conversation_id.as_slice() == conversation_id.bytes()
    }
}

impl SearchableEntity<ConversationId> for TargetedMessageTxCounter {
    fn find_all_matching(
        conn: &rusqlite::Connection,
        conversation_id: &ConversationId,
    ) -> crate::CryptoKeystoreResult<Vec<Self>> {
        Self::find_all_matching(conn, ConversationIdRef::new(conversation_id))
    }

    fn matches(&self, conversation_id: &ConversationId) -> bool {
        self.conversation_id.as_slice() == conversation_id.bytes()
    }
}

impl DeletableBySearchKey<ConversationId> for TargetedMessageTxCounter {
    fn delete_all_matching(
        tx: &rusqlite::Transaction,
        conversation_id: &ConversationId,
    ) -> crate::CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached(formatcp!(
            "DELETE FROM {} WHERE conversation_id = ?",
            TargetedMessageTxCounter::TABLE_NAME
        ))?;
        stmt.execute([conversation_id.as_ref()])?;
        Ok(())
    }
}

#[cfg(all(test, not(target_os = "unknown")))]
mod tests {

    use super::*;
    use crate::{Database, entities::PersistedMlsGroup, traits::FetchFromDatabase as _};

    /// Can we do some basic operations on TntMessageCounter - our first entity with a composite primary key?
    #[macro_rules_attribute::apply(smol_macros::test)]
    async fn supports_entity_persistence_with_a_composite_primary_key() {
        let store = Database::open_in_memory().unwrap();
        let conversation_id = b"conversation".to_vec();
        let mut first = TargetedMessageTxCounter {
            conversation_id: conversation_id.clone(),
            receiver: 7,
            count: 11,
        };
        let second = TargetedMessageTxCounter {
            conversation_id: conversation_id.clone(),
            receiver: 8,
            count: 12,
        };
        let other_conversation_id = b"another conversation".to_vec();
        let third = TargetedMessageTxCounter {
            conversation_id: other_conversation_id.clone(),
            receiver: 9,
            count: 13,
        };

        let tx = store.new_transaction().await.unwrap();
        tx.save(PersistedMlsGroup {
            id: conversation_id.clone(),
            state: b"group state".to_vec(),
        })
        .await
        .unwrap();
        tx.save(PersistedMlsGroup {
            id: other_conversation_id.clone(),
            state: b"other group state".to_vec(),
        })
        .await
        .unwrap();
        tx.save(first.clone()).await.unwrap();
        tx.save(second.clone()).await.unwrap();
        tx.save(third.clone()).await.unwrap();
        tx.commit().await.unwrap();

        assert_eq!(
            store
                .get::<TargetedMessageTxCounter>(&first.primary_key())
                .await
                .unwrap(),
            Some(first.clone().into())
        );
        assert_eq!(
            store
                .get::<TargetedMessageTxCounter>(&second.primary_key())
                .await
                .unwrap(),
            Some(second.clone().into())
        );
        assert_eq!(store.count::<TargetedMessageTxCounter>().await.unwrap(), 3);

        let mut counters = store
            .search::<TargetedMessageTxCounter, _>(ConversationIdRef::new(&conversation_id))
            .await
            .unwrap();
        counters.sort_by_key(|counter| counter.receiver);
        assert_eq!(counters, vec![first.clone().into(), second.clone().into()]);

        let counters = store
            .search::<TargetedMessageTxCounter, _>(ConversationIdRef::new(&other_conversation_id))
            .await
            .unwrap();
        assert_eq!(counters, vec![third.into()]);

        first.count += 1;
        let tx = store.new_transaction().await.unwrap();
        tx.save(first.clone()).await.unwrap();
        tx.remove::<TargetedMessageTxCounter>(&second.primary_key())
            .await
            .unwrap();
        tx.commit().await.unwrap();

        assert_eq!(
            store
                .get::<TargetedMessageTxCounter>(&first.primary_key())
                .await
                .unwrap(),
            Some(first.into())
        );
        assert_eq!(
            store
                .get::<TargetedMessageTxCounter>(&second.primary_key())
                .await
                .unwrap(),
            None
        );
    }
}
