use const_format::formatcp;

use crate::{
    CryptoKeystoreResult,
    entities::{
        ConversationId, ConversationIdRef,
        helpers::{count_helper, delete_helper, get_helper, get_helper_composite_key, load_all_helper},
    },
    traits::{BorrowPrimaryKey, Entity, EntityDatabaseMutation, EntityDeleteBorrowed, EntityGetBorrowed, PrimaryKey},
};

#[derive(core_crypto_macros::Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct TransientMessageTxCounter {
    pub conversation_id: ConversationId,
    pub count: u32,
}

impl TransientMessageTxCounter {
    const TABLE_NAME: &str = "transient_message_tx_counters";
    const PRIMARY_KEY_COLUMN_NAME: &str = "conversation_id";

    fn from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            conversation_id: row.get("conversation_id")?,
            count: row.get("count")?,
        })
    }
}

impl PrimaryKey for TransientMessageTxCounter {
    type PrimaryKey = ConversationId;
    fn primary_key(&self) -> Self::PrimaryKey {
        self.conversation_id.clone()
    }
}

impl Entity for TransientMessageTxCounter {
    const TABLE_NAME: &str = Self::TABLE_NAME;

    fn get(conn: &rusqlite::Connection, key: &ConversationId) -> CryptoKeystoreResult<Option<Self>> {
        get_helper_composite_key(
            conn,
            &[Self::PRIMARY_KEY_COLUMN_NAME],
            rusqlite::params![key.bytes()],
            Self::from_row,
        )
    }

    fn count(conn: &rusqlite::Connection) -> CryptoKeystoreResult<u32> {
        count_helper::<Self>(conn)
    }

    fn load_all(conn: &rusqlite::Connection) -> CryptoKeystoreResult<Vec<Self>> {
        load_all_helper(conn, Self::from_row)
    }
}

impl EntityDatabaseMutation for TransientMessageTxCounter {
    type AutoGeneratedFields = ();

    fn save(&self, tx: &rusqlite::Transaction) -> CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached(formatcp!(
            "INSERT OR REPLACE INTO {} (conversation_id, count) VALUES (?, ?)",
            TransientMessageTxCounter::TABLE_NAME
        ))?;
        stmt.execute(rusqlite::params![self.conversation_id, self.count])?;
        Ok(())
    }

    fn delete(tx: &rusqlite::Transaction, primary_key: &Self::PrimaryKey) -> CryptoKeystoreResult<bool> {
        delete_helper::<Self>(tx, Self::PRIMARY_KEY_COLUMN_NAME, primary_key.bytes())
    }
}

impl BorrowPrimaryKey for TransientMessageTxCounter {
    type BorrowedPrimaryKey<'a> = &'a ConversationIdRef;

    fn borrow_primary_key(&self) -> Self::BorrowedPrimaryKey<'_> {
        ConversationIdRef::new(&self.conversation_id)
    }
}

impl EntityGetBorrowed for TransientMessageTxCounter {
    fn get_borrowed(
        conn: &rusqlite::Connection,
        key: Self::BorrowedPrimaryKey<'_>,
    ) -> CryptoKeystoreResult<Option<Self>> {
        get_helper(conn, Self::PRIMARY_KEY_COLUMN_NAME, key, Self::from_row)
    }
}

impl EntityDeleteBorrowed for TransientMessageTxCounter {
    fn delete_borrowed(tx: &rusqlite::Transaction, id: Self::BorrowedPrimaryKey<'_>) -> CryptoKeystoreResult<bool> {
        delete_helper::<Self>(tx, Self::PRIMARY_KEY_COLUMN_NAME, id)
    }
}
