site:
  title: CoreCrypto
  start_page: core-crypto::index.adoc
  url: https://docs.example.org # TODO: set this, this is important for printed docs like pdf
content:
  sources:
  - url: ../
    branches: HEAD
    start_path: cc-book
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
