[book]
title = "CoreCrypto Book"
src = "src"

[preprocessor.langtabs]
command = "mdbook-langtabs"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-css = ["langtabs.css"]
additional-js = ["langtabs.js", "mermaid.min.js", "mermaid-init.js"]
