version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "**"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "bun"
    directory: "crypto-ffi/bindings/js"
    schedule:
      interval: "daily"
    groups:
      js-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directories: # actions have to be listed explicitly
      - "/" # workflows
      - "/.github/actions/**"
    schedule:
      interval: "weekly"
  - package-ecosystem: "rust-toolchain"
    directory: /
    schedule:
      interval: "monthly"
