import type {
    Ciphersuite,
    ClientId,
    CommitBundle,
    CoreCrypto,
    CoreCryptoLogLevel,
    HistorySecret,
    MlsTransport,
    MlsTransportData,
} from "@wireapp/core-crypto/browser";

import { browser } from "@wdio/globals";
import type { local } from "webdriver";

// Logging can be adjusted via the CC_TEST_LOG_LEVEL variable:
// 0 = no logs
// 1 = browser logs
// 2 = browser logs + CoreCrypto logs
const logLevel = Number(process.env["CC_TEST_LOG_LEVEL"] || "0");

export async function shared_setup() {
    if ((await browser.getUrl()) === "about:blank") {
        await browser.url("/html/index.html");
    }

    // Forward browser log events to the console.
    browser.on("log.entryAdded", logEvents);
    await browser.execute(async (logLevel) => {
        if (window.ccModule === undefined) {
            // @ts-expect-error TS2307: Cannot find module ./corecrypto.js or its corresponding type declarations.
            window.ccModule = await import("/corecrypto.js");
            await window.ccModule.initWasmModule(
                "/autogenerated/wasm-bindgen/"
            );

            if (logLevel >= 2) {
                window.ccModule.setLogger({
                    log: (
                        _level: CoreCryptoLogLevel,
                        message: string,
                        context: string | undefined
                    ) => {
                        console.log(message, context);
                    },
                });
                window.ccModule.setMaxLogLevel(
                    window.ccModule.CoreCryptoLogLevel.Debug
                );
            }
        }

        if (window.deliveryService === undefined) {
            window.deliveryService = {
                async sendCommitBundle(commitBundle: CommitBundle) {
                    window._latestCommitBundle = commitBundle;
                },
                async prepareForTransport(
                    secret: HistorySecret
                ): Promise<MlsTransportData> {
                    return Promise.resolve(secret.clientId.copyBytes());
                },
                async getLatestCommitBundle() {
                    return window._latestCommitBundle;
                },
            };
        }

        class Helpers {
            /**
             * Initialize a {@link CoreCrypto} instance.
             *
             * @param clientId The ClientId used to initialize CC.
             * @param withBasicCredential When set (default), adds a basic credential to the CC instance
             * @param cipherSuite Set the cipherSuite to use, if not set the default cipherSuite will be used
             *
             * @returns {Promise<void>}
             */
            static async ccInit(
                clientId?: ClientId,
                withBasicCredential: boolean = false,
                cipherSuite?: Ciphersuite,
            ): Promise<CoreCrypto> {
                if (clientId === undefined) {
                    const clientIdStr = window.crypto.randomUUID();
                    const encoder = new TextEncoder();
                    clientId = new window.ccModule.ClientId(
                        encoder.encode(clientIdStr).buffer
                    );
                }

                const key = new Uint8Array(32);
                crypto.getRandomValues(key);

                const databaseLocation = window.crypto.randomUUID();

                const db = await window.ccModule.Database.open(
                    databaseLocation,
                    new window.ccModule.DatabaseKey(key.buffer)
                );

                const cc = window.ccModule.CoreCrypto.new(db);

                await cc.transaction(async (ctx) => {
                    await ctx.mlsInit(clientId, window.deliveryService);
                    if (withBasicCredential) {
                        if (cipherSuite === undefined) {
                            cipherSuite = window.defaultCipherSuite
                        }
                        await ctx.addCredential(
                            window.ccModule.Credential.basic(cipherSuite, clientId)
                        );
                    }
                });
                return cc;
            }
        }
        window.helpers = Helpers;
    }, logLevel);
}

export async function teardown() {
    browser.off("log.entryAdded", logEvents);
}

export interface DeliveryService extends MlsTransport {
    getLatestCommitBundle: () => Promise<CommitBundle>;
}

export interface Helpers {
    ccInit: (
        clientId?: ClientId,
        withBasicCredential?: boolean,
        cipherSuite?: Ciphersuite,
    ) => Promise<CoreCrypto>;
}

function logEvents(entry: local.LogEntry) {
    if (logLevel >= 1) {
        console.log(`[${entry.level}] ${entry.text}`);
    }
}
