import { browser } from "@wdio/globals";
import type { local } from "webdriver";
import { logLevel } from "../../../shared/shared/utils";
import { type PlatformHelpers } from "../../../shared/shared/utils";
import type { Database } from "@wireapp/core-crypto/browser";

export async function sharedSetup() {
    if ((await browser.getUrl()) === "about:blank") {
        await browser.url("/html/index.html");
    }

    // Forward browser log events to the console.
    browser.on("log.entryAdded", logEvents);
    await browser.execute(async () => {
        if (globalThis.ccModule === undefined) {
            // @ts-expect-error TS2307: Cannot find module ./corecrypto.js or its corresponding type declarations.
            ccModule = await import("/corecrypto.js");
            await ccModule.initWasmModule(
                "/autogenerated/wasm-bindgen/index_bg.wasm"
            );
        }
    });
}

export async function sharedTeardown() {
    browser.off("log.entryAdded", logEvents);
}

/**
 * Log entry from the core crypto logger
 */
export interface LogEntry {
    level: number;
    message: string;
    context: string;
}

function logEvents(entry: local.LogEntry) {
    if (logLevel >= 1) {
        console.log(`[${entry.level}] ${entry.text}`);
    }
}

export async function setPlatformHelpers() {
    return await browser.execute(() => {
        class PlatformHelpersImpl implements PlatformHelpers {
            async newDatabase(
                location?: string,
                key?: DatabaseKey
            ): Promise<Database> {
                const finalKey = key ?? helpers.newDatabaseKey();
                const finalLocation = location ?? crypto.randomUUID();
                return ccModule.Database.open(finalLocation, finalKey);
            }
        }
        globalThis.platformHelpers = new PlatformHelpersImpl();
    });
}

type ExecuteScript = Parameters<typeof browser.execute>[0];

export async function runOnPlatform<Args extends unknown[], T>(
    script: (...args: Args) => T,
    ...args: Args
): Promise<T> {
    return browser.execute(script as ExecuteScript, ...args) as Promise<T>;
}
