import {
    Ciphersuite,
    Credential as CredentialInner,
    credentialBasic,
    type ClientIdLike,
} from "../browser/autogenerated/core_crypto_ffi";

/** A cryptographic credential.
 *
 * This is tied to a particular client via either its client id or certificate bundle,
 * depending on its credential type, but is independent of any client instance or storage.
 *
 * To attach to a particular client instance and store, see
 * {@link CoreCryptoContext.add_credential}.
 */
export class Credential extends CredentialInner {
    /** Generate a basic credential.
     *
     * The result is independent of any client instance and the database; it lives in memory only.
     */
    public static basic(
        ciphersuite: Ciphersuite,
        clientId: ClientIdLike
    ): Credential {
        return credentialBasic(ciphersuite, clientId);
    }
}
