use async_trait::async_trait;

use crate::{
    CryptoKeystoreResult,
    connection::idb_migration::legacy::{
        connection::{KeystoreDatabaseConnection, TransactionWrapper},
        traits::{
            Decryptable, Decrypting, EncryptData, Encrypting, EncryptionKey, Entity, EntityBase,
            EntityDatabaseMutation, KeyType as _, UNIQUE_ENTITY_KEY, UniqueEntity, decrypt_unique_entity_data,
        },
    },
    traits::PrimaryKey,
};

/// Consumer data as the legacy IndexedDB schema stores it.
///
/// The live [`ConsumerData`][crate::entities::ConsumerData] is keyed by a `u32`, as v10.0 and v10.1 keyed this row
/// on wasm; the releases before them keyed it by the single byte [`UNIQUE_ENTITY_KEY`]. The key is part of the
/// additional authenticated data, so rows from either generation can only be read with the key they were written
/// under; see [`decrypt_unique_entity_data`].
pub(crate) struct LegacyConsumerData {
    pub(crate) content: Vec<u8>,
}

impl LegacyConsumerData {
    /// Write this row into the `consumer_data` table, whose only row has id 0.
    pub(crate) fn save(&self, tx: &rusqlite::Transaction<'_>) -> CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached("INSERT OR REPLACE INTO consumer_data (id, content) VALUES (0, ?)")?;
        stmt.execute([&self.content])?;
        Ok(())
    }
}

impl PrimaryKey for LegacyConsumerData {
    type PrimaryKey = [u8; 1];

    fn primary_key(&self) -> Self::PrimaryKey {
        Self::KEY
    }
}

impl EntityBase for LegacyConsumerData {
    type ConnectionType = KeystoreDatabaseConnection;
    const TABLE_NAME: &'static str = "consumer_data";
}

impl UniqueEntity for LegacyConsumerData {
    const KEY: [u8; 1] = UNIQUE_ENTITY_KEY;
}

#[async_trait(?Send)]
impl Entity for LegacyConsumerData {
    async fn get(conn: &mut Self::ConnectionType, _key: &Self::PrimaryKey) -> CryptoKeystoreResult<Option<Self>> {
        Ok(Self::load_all(conn).await?.pop())
    }

    async fn count(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<u32> {
        conn.storage().count::<Self>().await
    }

    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        conn.storage().get_all().await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDatabaseMutation<'a> for LegacyConsumerData {
    type Transaction = TransactionWrapper<'a>;
    type AutoGeneratedFields = ();

    async fn save(&'a self, tx: &Self::Transaction) -> CryptoKeystoreResult<()> {
        tx.save(self).await
    }

    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32> {
        tx.count::<Self>().await
    }

    async fn delete(tx: &Self::Transaction, id: &Self::PrimaryKey) -> CryptoKeystoreResult<bool> {
        tx.delete::<Self>(id.bytes().as_ref()).await
    }
}

impl EncryptionKey for LegacyConsumerData {
    fn encryption_key(&self) -> &[u8] {
        &UNIQUE_ENTITY_KEY
    }
}

#[derive(serde::Serialize, serde::Deserialize)]
pub(crate) struct ConsumerDataEncrypted {
    content: Vec<u8>,
}

impl<'a> Encrypting<'a> for LegacyConsumerData {
    type EncryptedForm = ConsumerDataEncrypted;

    fn encrypt(&'a self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::EncryptedForm> {
        let content = <Self as EncryptData>::encrypt_data(self, cipher, &self.content)?;
        Ok(ConsumerDataEncrypted { content })
    }
}

impl Decrypting<'static> for ConsumerDataEncrypted {
    type DecryptedForm = LegacyConsumerData;

    fn decrypt(self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::DecryptedForm> {
        let content = decrypt_unique_entity_data::<LegacyConsumerData>(cipher, &self.content)?;
        Ok(LegacyConsumerData { content })
    }
}

impl Decryptable<'static> for LegacyConsumerData {
    type DecryptableFrom = ConsumerDataEncrypted;
}
