name: Fetch or make the web bindings files and wrappers
inputs:
  gh-token:
    required: true
  artifact-generation:
    description: suffix for artifact names that allows us to easily invalidate artifacts
    required: true

runs:
  using: composite

  steps:
      - name: Set MAKE
        uses: ./.github/actions/make/set-make-executable

      # ensure bun deps are installed freshly before any command using bun is invoked
      - name: install bun deps
        run: |
          $MAKE bun-deps
        shell: bash -euo pipefail {0}

      - name: generate native ts bindings
        uses: ./.github/actions/make
        with:
          key: ts-native
          make-rule: ts-native
          uses-rust: true
          # TODO the node artifact needs to depend on platform
          target-path: |
            crypto-ffi/bindings/js/out/native/corecrypto.d.ts
            crypto-ffi/bindings/js/out/native/corecrypto.js
            crypto-ffi/bindings/js/out/native/linux-x64.node
            crypto-ffi/bindings/js/src/native/autogenerated/core_crypto_ffi.ts
          gh-token: ${{ inputs.gh-token }}
          artifact-generation: ${{ inputs.artifact-generation }}
