name: Fetch or make the web bindings files and wrappers
inputs:
  gh-token:
    required: true
  artifact-generation:
    description: suffix for artifact names that allows us to easily invalidate artifacts
    required: true

runs:
  using: composite

  steps:
      - name: Set MAKE
        uses: ./.github/actions/make/set-make-executable

      # ensure bun deps are installed freshly before any command using bun is invoked
      - name: install bun deps
        run: |
          $MAKE bun-deps
        shell: bash -euo pipefail {0}

      - name: set artifact name based on OS
        id: artifact
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then
            artifact="darwin-arm64"
          else
            artifact="linux-x64"
          fi
          echo "artifact=$artifact" >> "$GITHUB_OUTPUT"

      - name: generate native ts bindings (macOS)
        if: runner.os == 'macOS'
        uses: ./.github/actions/make
        with:
          key: ts-native-${{ steps.artifact.outputs.artifact }}
          make-rule: ts-native
          uses-rust: true
          target-path: |
            crypto-ffi/bindings/js/out/native/corecrypto.js
            crypto-ffi/bindings/js/out/native/corecrypto.d.ts
            crypto-ffi/bindings/js/out/native/libcore_crypto_ffi.dylib
            crypto-ffi/bindings/js/out/native/uniffi-runtime-napi.darwin-arm64.node
            crypto-ffi/bindings/js/packages/native/src/autogenerated/core_crypto_ffi.ts
            crypto-ffi/bindings/js/packages/native/src/autogenerated/core_crypto_ffi-ffi.ts
          gh-token: ${{ inputs.gh-token }}
          artifact-generation: ${{ inputs.artifact-generation }}

      - name: generate native ts bindings (Linux)
        if: runner.os != 'macOS'
        uses: ./.github/actions/make
        with:
          key: ts-native-${{ steps.artifact.outputs.artifact }}
          make-rule: ts-native
          uses-rust: true
          target-path: |
            crypto-ffi/bindings/js/out/native/corecrypto.js
            crypto-ffi/bindings/js/out/native/corecrypto.d.ts
            crypto-ffi/bindings/js/out/native/libcore_crypto_ffi.so
            crypto-ffi/bindings/js/out/native/uniffi-runtime-napi.linux-x64-gnu.node
            crypto-ffi/bindings/js/packages/native/src/autogenerated/core_crypto_ffi.ts
            crypto-ffi/bindings/js/packages/native/src/autogenerated/core_crypto_ffi-ffi.ts
          gh-token: ${{ inputs.gh-token }}
          artifact-generation: ${{ inputs.artifact-generation }}
