[all]
timeout = "10m"
ignore-tests = true
run-types = ["Tests"]
exclude-files = [
    "extras/*",
    # TODO: Un-exclude those when WASM support is added to tarpaulin
    "crypto-ffi/src/wasm.rs",
    "keystore/src/connection/platform/wasm/*",
    "keystore/src/entities/platform/wasm/*",
    # TODO: Find a way to enable the feature to trigger the tests for the C API
    "crypto-ffi/src/c_api/*"
]
