use std::{borrow::Borrow, collections::HashMap};

use openmls_traits::OpenMlsCryptoProvider as _;

use super::{ConversationWithMls, Error, Result};
use crate::{
    ClientIdRef, CredentialType, E2eiConversationState, RecursiveError, Session, UserId, WireIdentity,
    mls::credential::ext::CredentialExt as _,
};

impl super::ImmutableConversation {
    /// Indicates when to mark a conversation as not verified i.e. when not all its members have a X509
    /// Credential generated by Wire's end-to-end identity enrollment
    pub async fn e2ei_conversation_state(&self) -> Result<E2eiConversationState> {
        let backend = self.crypto_provider().await?;
        let inner = self.conversation().await;
        let state = Session::compute_conversation_state(
            inner.ciphersuite(),
            inner.group.members_credentials(),
            CredentialType::X509,
            backend.authentication_service(),
        )
        .await;
        Ok(state)
    }

    /// From a given conversation, get the identity of the members supplied. Identity is only present for
    /// members with a Certificate Credential (after turning on end-to-end identity).
    /// If no member has a x509 certificate, it will return an empty Vec
    pub async fn get_device_identities(
        &self,
        device_ids: &[impl Borrow<ClientIdRef> + Sync],
    ) -> Result<Vec<WireIdentity>> {
        if device_ids.is_empty() {
            return Err(Error::CallerError(
                "This function accepts a list of IDs as a parameter, but that list was empty.",
            ));
        }
        let mls_provider = self.crypto_provider().await?;
        let auth_service = mls_provider.authentication_service();
        let conversation = self.conversation().await;

        let pki_env = auth_service.pki_env().await;

        let mut identities = vec![];
        for (id, credential) in conversation.members_with_key() {
            if device_ids.iter().any(|client_id| client_id.borrow() == id) {
                identities.push(
                    credential
                        .extract_identity(conversation.ciphersuite(), pki_env.as_deref())
                        .await
                        .map_err(RecursiveError::mls_credential("extracting identity"))?,
                );
            }
        }
        Ok(identities)
    }

    /// From a given conversation, get the identity of the users (device holders) supplied.
    /// Identity is only present for devices with a Certificate Credential (after turning on end-to-end identity).
    /// If no member has a x509 certificate, it will return an empty Vec.
    ///
    /// Returns a Map with all the identities for a given users. Consumers are then recommended to
    /// reduce those identities to determine the actual status of a user.
    pub async fn get_user_identities(&self, user_ids: &[String]) -> Result<HashMap<String, Vec<WireIdentity>>> {
        if user_ids.is_empty() {
            return Err(Error::CallerError(
                "This function accepts a list of IDs as a parameter, but that list was empty.",
            ));
        }
        let mls_provider = self.crypto_provider().await?;
        let auth_service = mls_provider.authentication_service();
        let conversation = self.conversation().await;
        let user_ids = user_ids.iter().map(|uid| uid.as_bytes()).collect::<Vec<_>>();

        let pki_env = auth_service.pki_env().await;

        let mut identities = HashMap::new();
        for (id, credential) in conversation.members_with_key() {
            let uid = match UserId::try_from(id.as_slice()) {
                Ok(uid) => uid,
                Err(_) => continue,
            };

            if !user_ids.contains(&uid) {
                continue;
            }

            let uid = String::try_from(uid).map_err(RecursiveError::mls_client("getting user identities"))?;
            let identity = credential
                .extract_identity(conversation.ciphersuite(), pki_env.as_deref())
                .await
                .map_err(RecursiveError::mls_credential("extracting identity"))?;
            let value = identities.entry(uid).or_insert_with(Vec::new);
            value.push(identity);
        }

        Ok(identities)
    }
}
