use async_trait::async_trait;
use web_time::SystemTime;

use crate::{
    CryptoKeystoreError, CryptoKeystoreResult, Sha256Hash,
    connection::{KeystoreDatabaseConnection, TransactionWrapper},
    entities::{CredentialFindFilters, StoredCredential},
    traits::{
        DecryptData, Decryptable, Decrypting, EncryptData, Encrypting, Entity, EntityBase, EntityDatabaseMutation,
        KeyType as _, PrimaryKey, SearchableEntity,
    },
};

impl EntityBase for StoredCredential {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = u64;
    const COLLECTION_NAME: &'static str = "mls_credentials";

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::StoredCredential(self.into())
    }
}

impl PrimaryKey for StoredCredential {
    type PrimaryKey = Sha256Hash;

    fn primary_key(&self) -> Self::PrimaryKey {
        Sha256Hash::hash_from(&self.public_key)
    }
}

#[async_trait(?Send)]
impl Entity for StoredCredential {
    async fn get(conn: &mut Self::ConnectionType, key: &Self::PrimaryKey) -> CryptoKeystoreResult<Option<Self>> {
        conn.storage().get(key.bytes().as_ref()).await
    }

    async fn count(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<u32> {
        conn.storage().count::<Self>().await
    }

    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        conn.storage().get_all().await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDatabaseMutation<'a> for StoredCredential {
    type Transaction = TransactionWrapper<'a>;

    async fn pre_save(&mut self) -> CryptoKeystoreResult<Self::AutoGeneratedFields> {
        let now = SystemTime::now();
        let created_at = now
            .duration_since(SystemTime::UNIX_EPOCH)
            .map_err(|_| CryptoKeystoreError::TimestampError)?
            .as_secs();
        self.created_at = created_at;
        Ok(created_at)
    }

    async fn save(&'a self, tx: &Self::Transaction) -> CryptoKeystoreResult<()> {
        tx.save(self).await
    }

    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32> {
        tx.count::<Self>().await
    }

    async fn delete(tx: &Self::Transaction, id: &Self::PrimaryKey) -> CryptoKeystoreResult<bool> {
        tx.delete::<Self>(id.bytes().as_ref()).await
    }
}

#[derive(serde::Serialize)]
pub struct StoredCredentialEncrypt<'a> {
    // Copy fields
    created_at: u64,
    ciphersuite: u16,
    // borrowed fields
    session_id: &'a [u8],
    public_key: &'a [u8],
    // encrypted fields
    credential: Vec<u8>,
    private_key: Vec<u8>,
}

impl<'a> Encrypting<'a> for StoredCredential {
    type EncryptedForm = StoredCredentialEncrypt<'a>;

    fn encrypt(&'a self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::EncryptedForm> {
        let credential = <StoredCredential as EncryptData>::encrypt_data(self, cipher, &self.credential)?;
        let private_key = <StoredCredential as EncryptData>::encrypt_data(self, cipher, &self.private_key)?;

        Ok(StoredCredentialEncrypt {
            created_at: self.created_at,
            ciphersuite: self.ciphersuite,
            session_id: &self.session_id,
            public_key: &self.public_key,
            credential,
            private_key,
        })
    }
}

/// The encrypted form of a stored credential, which can be decrypted
#[derive(serde::Deserialize)]
pub struct StoredCredentialDecrypt {
    session_id: Vec<u8>,
    credential: Vec<u8>,
    created_at: u64,
    ciphersuite: u16,
    public_key: Vec<u8>,
    private_key: Vec<u8>,
}

impl Decrypting<'static> for StoredCredentialDecrypt {
    type DecryptedForm = StoredCredential;

    fn decrypt(self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::DecryptedForm> {
        let Self {
            session_id,
            credential,
            created_at,
            ciphersuite,
            public_key,
            private_key,
        } = self;

        // we encrypt only two fields here: the serialized form of the credential itself,
        // and the private key
        let primary_key = Sha256Hash::hash_from(&public_key);
        let credential = <StoredCredential as DecryptData>::decrypt_data(cipher, &primary_key, &credential)?;
        let private_key = <StoredCredential as DecryptData>::decrypt_data(cipher, &primary_key, &private_key)?;

        Ok(StoredCredential {
            session_id,
            credential,
            created_at,
            ciphersuite,
            public_key,
            private_key,
        })
    }
}

impl Decryptable<'static> for StoredCredential {
    type DecryptableFrom = StoredCredentialDecrypt;
}

#[async_trait(?Send)]
impl<'a> SearchableEntity<CredentialFindFilters<'a>> for StoredCredential {
    async fn find_all_matching(
        conn: &mut Self::ConnectionType,
        filters: &CredentialFindFilters<'a>,
    ) -> CryptoKeystoreResult<Vec<Self>> {
        // if we know something unique to this credential, use a more-efficient search
        if let Some(hash) = filters.hash.or_else(|| filters.public_key.map(Sha256Hash::hash_from)) {
            return Self::get(conn, &hash).await.map(|optional| {
                optional
                    .into_iter()
                    .filter(|credential| credential.matches(filters))
                    .collect()
            });
        }

        // We intentionally are using a kind of dumb filtering method here.
        // This is OK because we are intentionally not adding big fancy heavy compound indices
        // for this type. But what this means is that we end up doing a linear scan here (just
        // like Sqlite is doing under the hood).
        //
        // It's fine though; at least this lets us skip the cost of deserializing all the credentials
        // which have been filtered out.
        let mut credentials = Self::load_all(conn).await?;
        credentials.retain(|credential| credential.matches(filters));
        Ok(credentials)
    }

    fn matches(
        &self,
        CredentialFindFilters {
            hash,
            public_key,
            ciphersuite,
            earliest_validity,
        }: &CredentialFindFilters<'a>,
    ) -> bool {
        hash.is_none_or(|hash| hash == self.primary_key())
            && public_key.is_none_or(|public_key| public_key == self.public_key)
            && ciphersuite.is_none_or(|ciphersuite| ciphersuite == self.ciphersuite)
            && earliest_validity.is_none_or(|earliest_validity| earliest_validity == self.created_at)
    }
}
