use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::{
    CryptoKeystoreResult, MissingKeyErrorKind,
    connection::{DatabaseConnection, KeystoreDatabaseConnection, TransactionWrapper},
    entities::{Entity, EntityBase, EntityFindParams, EntityTransactionExt, StoredHpkePrivateKey, StringEntityId},
    traits::{
        BorrowPrimaryKey, DecryptData, Decryptable, Decrypting, EncryptData, Encrypting, Entity as NewEntity,
        EntityBase as NewEntityBase, EntityDatabaseMutation, EntityDeleteBorrowed, EntityGetBorrowed, PrimaryKey,
    },
};

#[async_trait::async_trait(?Send)]
impl EntityBase for StoredHpkePrivateKey {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "mls_hpke_private_keys";

    fn to_missing_key_err_kind() -> MissingKeyErrorKind {
        MissingKeyErrorKind::StoredHpkePrivateKey
    }

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::HpkePrivateKey(self.into())
    }
}

#[async_trait::async_trait(?Send)]
impl EntityTransactionExt for StoredHpkePrivateKey {}

#[async_trait::async_trait(?Send)]
impl Entity for StoredHpkePrivateKey {
    fn id_raw(&self) -> &[u8] {
        self.pk.as_slice()
    }

    async fn find_all(conn: &mut Self::ConnectionType, params: EntityFindParams) -> CryptoKeystoreResult<Vec<Self>> {
        let storage = conn.storage();
        storage
            .get_all(<Self as EntityBase>::COLLECTION_NAME, Some(params))
            .await
    }

    async fn find_one(
        conn: &mut Self::ConnectionType,
        id: &StringEntityId,
    ) -> crate::CryptoKeystoreResult<Option<Self>> {
        conn.storage()
            .get(<Self as EntityBase>::COLLECTION_NAME, id.as_slice())
            .await
    }

    async fn count(conn: &mut Self::ConnectionType) -> crate::CryptoKeystoreResult<usize> {
        conn.storage().count(<Self as EntityBase>::COLLECTION_NAME).await
    }

    fn encrypt(&mut self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<()> {
        self.sk = <Self as Entity>::encrypt_data(self, cipher, self.sk.as_slice())?;
        Self::ConnectionType::check_buffer_size(self.sk.len())?;

        Ok(())
    }

    fn decrypt(&mut self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<()> {
        self.sk = self.decrypt_data(cipher, self.sk.as_slice())?;

        Ok(())
    }
}

impl NewEntityBase for StoredHpkePrivateKey {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "mls_hpke_private_keys";

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::HpkePrivateKey(self.into())
    }
}

impl PrimaryKey for StoredHpkePrivateKey {
    type PrimaryKey = Vec<u8>;

    fn primary_key(&self) -> Vec<u8> {
        self.pk.clone()
    }
}

impl BorrowPrimaryKey for StoredHpkePrivateKey {
    type BorrowedPrimaryKey = [u8];

    fn borrow_primary_key(&self) -> &Self::BorrowedPrimaryKey {
        &self.pk
    }
}

#[async_trait(?Send)]
impl NewEntity for StoredHpkePrivateKey {
    async fn get(conn: &mut Self::ConnectionType, id: &Vec<u8>) -> CryptoKeystoreResult<Option<Self>> {
        Self::get_borrowed(conn, id.as_slice()).await
    }

    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        conn.storage().new_get_all().await
    }

    async fn count(conn: &mut Self::ConnectionType) -> crate::CryptoKeystoreResult<u32> {
        conn.storage().new_count::<Self>().await
    }
}

#[async_trait(?Send)]
impl EntityGetBorrowed for StoredHpkePrivateKey {
    async fn get_borrowed(
        conn: &mut <Self as NewEntityBase>::ConnectionType,
        id: &[u8],
    ) -> CryptoKeystoreResult<Option<Self>> {
        conn.storage().new_get(id).await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDatabaseMutation<'a> for StoredHpkePrivateKey {
    type Transaction = TransactionWrapper<'a>;

    async fn save(&'a self, tx: &Self::Transaction) -> CryptoKeystoreResult<()> {
        tx.new_save(self).await
    }

    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32> {
        tx.new_count::<Self>().await
    }

    async fn delete(tx: &Self::Transaction, id: &Vec<u8>) -> CryptoKeystoreResult<bool> {
        Self::delete_borrowed(tx, id.as_slice()).await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDeleteBorrowed<'a> for StoredHpkePrivateKey {
    async fn delete_borrowed(
        tx: &<Self as EntityDatabaseMutation<'a>>::Transaction,
        id: &[u8],
    ) -> CryptoKeystoreResult<bool> {
        tx.new_delete::<Self>(id).await
    }
}

#[derive(Serialize)]
pub struct StoredHpkePrivateKeyEncrypt<'a> {
    sk: Vec<u8>,
    pk: &'a [u8],
}

impl<'a> Encrypting<'a> for StoredHpkePrivateKey {
    type EncryptedForm = StoredHpkePrivateKeyEncrypt<'a>;

    fn encrypt(&'a self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::EncryptedForm> {
        let sk = <Self as EncryptData>::encrypt_data(self, cipher, &self.sk)?;
        Ok(StoredHpkePrivateKeyEncrypt { sk, pk: &self.pk })
    }
}

#[derive(Deserialize)]
pub struct StoredHpkePrivateKeyDecrypt {
    sk: Vec<u8>,
    pk: Vec<u8>,
}

impl Decrypting<'static> for StoredHpkePrivateKeyDecrypt {
    type DecryptedForm = StoredHpkePrivateKey;

    fn decrypt(self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::DecryptedForm> {
        let sk = <StoredHpkePrivateKey as DecryptData>::decrypt_data(cipher, &self.pk, &self.sk)?;
        Ok(StoredHpkePrivateKey { sk, pk: self.pk })
    }
}

impl Decryptable<'static> for StoredHpkePrivateKey {
    type DecryptableFrom = StoredHpkePrivateKeyDecrypt;
}
