use std::borrow::Borrow;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::{
    CryptoKeystoreResult, MissingKeyErrorKind,
    connection::{KeystoreDatabaseConnection, TransactionWrapper},
    entities::{Entity, EntityBase, EntityFindParams, EntityTransactionExt, PersistedMlsPendingGroup, StringEntityId},
    traits::{
        BorrowPrimaryKey, DecryptData, Decryptable, Decrypting, EncryptData, Encrypting, Entity as NewEntity,
        EntityBase as NewEntityBase, EntityDatabaseMutation, EntityDeleteBorrowed, KeyType,
    },
};

impl EntityBase for PersistedMlsPendingGroup {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "mls_pending_groups";

    fn to_missing_key_err_kind() -> MissingKeyErrorKind {
        MissingKeyErrorKind::MlsPendingGroup
    }

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::PersistedMlsPendingGroup(self)
    }
}

#[async_trait::async_trait(?Send)]
impl EntityTransactionExt for PersistedMlsPendingGroup {}

#[async_trait::async_trait(?Send)]
impl Entity for PersistedMlsPendingGroup {
    fn id_raw(&self) -> &[u8] {
        self.id.as_slice()
    }

    async fn find_all(conn: &mut Self::ConnectionType, params: EntityFindParams) -> CryptoKeystoreResult<Vec<Self>> {
        let storage = conn.storage();
        storage
            .get_all(<Self as EntityBase>::COLLECTION_NAME, Some(params))
            .await
    }

    async fn find_one(
        conn: &mut Self::ConnectionType,
        id: &StringEntityId,
    ) -> crate::CryptoKeystoreResult<Option<Self>> {
        conn.storage()
            .get(<Self as EntityBase>::COLLECTION_NAME, id.as_slice())
            .await
    }

    async fn find_many(
        conn: &mut Self::ConnectionType,
        _ids: &[StringEntityId],
    ) -> crate::CryptoKeystoreResult<Vec<Self>> {
        // Plot twist: we always select ALL the persisted groups. Unsure if we want to make it a real API with selection
        conn.storage()
            .get_all(<Self as EntityBase>::COLLECTION_NAME, None)
            .await
    }

    async fn count(conn: &mut Self::ConnectionType) -> crate::CryptoKeystoreResult<usize> {
        conn.storage().count(<Self as EntityBase>::COLLECTION_NAME).await
    }

    fn id(&self) -> CryptoKeystoreResult<wasm_bindgen::JsValue> {
        Ok(js_sys::Uint8Array::from(self.id.as_slice()).into())
    }

    fn encrypt(&mut self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<()> {
        self.state = <Self as Entity>::encrypt_data(self, cipher, self.state.as_slice())?;

        Ok(())
    }

    fn decrypt(&mut self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<()> {
        self.state = self.decrypt_data(cipher, self.state.as_slice())?;

        Ok(())
    }
}

impl NewEntityBase for PersistedMlsPendingGroup {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();

    const COLLECTION_NAME: &'static str = "mls_pending_groups";

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::PersistedMlsPendingGroup(self)
    }
}

#[async_trait(?Send)]
impl NewEntity for PersistedMlsPendingGroup {
    type PrimaryKey = Vec<u8>;

    fn primary_key(&self) -> Self::PrimaryKey {
        self.id.clone()
    }

    async fn get(conn: &mut Self::ConnectionType, key: &Self::PrimaryKey) -> CryptoKeystoreResult<Option<Self>> {
        Self::get_borrowed(conn, key).await
    }

    async fn count(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<u32> {
        conn.storage().new_count::<Self>().await
    }

    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        conn.storage().new_get_all().await
    }
}

#[async_trait(?Send)]
impl BorrowPrimaryKey for PersistedMlsPendingGroup {
    type BorrowedPrimaryKey = [u8];

    fn borrow_primary_key(&self) -> &[u8] {
        &self.id
    }

    async fn get_borrowed<Q>(conn: &mut Self::ConnectionType, key: &Q) -> CryptoKeystoreResult<Option<Self>>
    where
        Self::PrimaryKey: Borrow<Q>,
        Q: KeyType,
    {
        conn.storage().new_get(key.bytes().as_ref()).await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDatabaseMutation<'a> for PersistedMlsPendingGroup {
    type Transaction = TransactionWrapper<'a>;

    async fn save(&'a self, tx: &TransactionWrapper<'a>) -> CryptoKeystoreResult<()> {
        tx.new_save(self).await
    }

    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32> {
        tx.new_count::<Self>().await
    }

    async fn delete(tx: &Self::Transaction, id: &Self::PrimaryKey) -> CryptoKeystoreResult<bool> {
        Self::delete_borrowed(tx, id).await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDeleteBorrowed<'a> for PersistedMlsPendingGroup {
    async fn delete_borrowed<Q>(tx: &Self::Transaction, id: &Q) -> CryptoKeystoreResult<bool>
    where
        Self::PrimaryKey: Borrow<Q>,
        Q: KeyType,
    {
        tx.new_delete::<Self>(id.bytes().as_ref()).await
    }
}

#[derive(Serialize)]
pub struct PersistedMlsPendingGroupEncrypt<'a> {
    id: &'a [u8],
    state: Vec<u8>,
    parent_id: &'a Option<Vec<u8>>,
    custom_configuration: &'a Vec<u8>,
}

impl<'a> Encrypting<'a> for PersistedMlsPendingGroup {
    type EncryptedForm = PersistedMlsPendingGroupEncrypt<'a>;

    fn encrypt(&'a self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::EncryptedForm> {
        let state = <Self as EncryptData>::encrypt_data(self, cipher, &self.state)?;

        Ok(PersistedMlsPendingGroupEncrypt {
            state,
            id: &self.id,
            parent_id: &self.parent_id,
            custom_configuration: &self.custom_configuration,
        })
    }
}

#[derive(Deserialize)]
pub struct PersistedMlsPendingGroupDecrypt {
    id: Vec<u8>,
    state: Vec<u8>,
    parent_id: Option<Vec<u8>>,
    custom_configuration: Vec<u8>,
}

impl Decrypting<'static> for PersistedMlsPendingGroupDecrypt {
    type DecryptedForm = PersistedMlsPendingGroup;

    fn decrypt(self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::DecryptedForm> {
        let state = <PersistedMlsPendingGroup as DecryptData>::decrypt_data(cipher, &self.id, &self.state)?;

        Ok(PersistedMlsPendingGroup {
            state,
            id: self.id,
            parent_id: self.parent_id,
            custom_configuration: self.custom_configuration,
        })
    }
}

impl Decryptable<'static> for PersistedMlsPendingGroup {
    type DecryptableFrom = PersistedMlsPendingGroupDecrypt;
}
