use std::sync::OnceLock;

use async_trait::async_trait;
use js_sys::Uint8Array;
use serde::{Deserialize, Serialize};
use wasm_bindgen::JsValue;

use crate::{
    CryptoKeystoreResult,
    connection::{KeystoreDatabaseConnection, TransactionWrapper},
    entities::{ConversationId, MlsPendingMessage},
    traits::{
        DecryptWithExplicitEncryptionKey as _, Decryptable, Decrypting, DeletableBySearchKey,
        EncryptWithExplicitEncryptionKey as _, Encrypting, EncryptionKey, Entity, EntityBase, EntityDatabaseMutation,
        SearchableEntity,
    },
    transaction::InMemoryTable,
};

impl EntityBase for MlsPendingMessage {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "mls_pending_messages";

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::MlsPendingMessage(self.into())
    }

    fn get_in_memory_table() -> InMemoryTable<Self> {
        static IN_MEMORY_TABLE: OnceLock<InMemoryTable<MlsPendingMessage>> = OnceLock::new();
        IN_MEMORY_TABLE.get_or_init(Default::default).clone()
    }
}

#[async_trait(?Send)]
impl Entity for MlsPendingMessage {
    async fn get(_conn: &mut Self::ConnectionType, _key: &Self::PrimaryKey) -> CryptoKeystoreResult<Option<Self>> {
        panic!("cannot get `MlsPendingMessage` by primary key as it has no distinct primary key")
    }

    async fn count(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<u32> {
        conn.storage().count::<Self>().await
    }

    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        conn.storage().get_all::<Self>().await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDatabaseMutation<'a> for MlsPendingMessage {
    type Transaction = TransactionWrapper<'a>;

    async fn save(&'a self, tx: &Self::Transaction) -> CryptoKeystoreResult<()> {
        tx.save(self).await
    }

    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32> {
        tx.count::<Self>().await
    }

    async fn delete(_tx: &Self::Transaction, _id: &Self::PrimaryKey) -> CryptoKeystoreResult<bool> {
        panic!("cannot delete `MlsPendingMessage` by primary key as it has no distinct primary key")
    }
}

impl EncryptionKey for MlsPendingMessage {
    fn encryption_key(&self) -> &[u8] {
        &self.foreign_id
    }
}

#[derive(Serialize)]
pub struct MlsPendingMessageEncrypt<'a> {
    foreign_id: &'a [u8],
    message: Vec<u8>,
}

impl<'a> Encrypting<'a> for MlsPendingMessage {
    type EncryptedForm = MlsPendingMessageEncrypt<'a>;

    fn encrypt(&'a self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::EncryptedForm> {
        let message = self.encrypt_data_with_encryption_key(cipher, &self.message)?;
        Ok(MlsPendingMessageEncrypt {
            foreign_id: &self.foreign_id,
            message,
        })
    }
}

#[derive(Deserialize)]
pub struct MlsPendingMessageDecrypt {
    foreign_id: Vec<u8>,
    message: Vec<u8>,
}

impl Decrypting<'static> for MlsPendingMessageDecrypt {
    type DecryptedForm = MlsPendingMessage;

    fn decrypt(self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::DecryptedForm> {
        let message = MlsPendingMessage::decrypt_data_with_encryption_key(cipher, &self.foreign_id, &self.message)?;
        Ok(MlsPendingMessage {
            foreign_id: self.foreign_id,
            message,
        })
    }
}

impl Decryptable<'static> for MlsPendingMessage {
    type DecryptableFrom = MlsPendingMessageDecrypt;
}

#[async_trait(?Send)]
impl<'a> SearchableEntity<ConversationId<'a>> for MlsPendingMessage {
    async fn find_all_matching(
        conn: &mut Self::ConnectionType,
        conversation_id: &ConversationId<'a>,
    ) -> CryptoKeystoreResult<Vec<Self>> {
        let conversation_id = *conversation_id.as_ref();
        let storage = conn.storage();
        let id = JsValue::from(Uint8Array::from(conversation_id));
        storage.get_all_with_query(Some(id.into())).await
    }

    fn matches(&self, conversation_id: &ConversationId<'a>) -> bool {
        *conversation_id.as_ref() == self.foreign_id.as_slice()
    }
}

#[async_trait(?Send)]
impl<'a> DeletableBySearchKey<'a, ConversationId<'a>> for MlsPendingMessage {
    async fn delete_all_matching(
        tx: &Self::Transaction,
        conversation_id: &ConversationId<'a>,
    ) -> CryptoKeystoreResult<()> {
        tx.delete::<Self>(*conversation_id.as_ref()).await?;
        Ok(())
    }
}
