use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::{
    CryptoKeystoreResult, MissingKeyErrorKind, Sha256Hash,
    connection::{DatabaseConnection, KeystoreDatabaseConnection, TransactionWrapper},
    entities::{Entity, EntityBase, EntityFindParams, EntityTransactionExt, StoredPskBundle, StringEntityId},
    traits::{
        DecryptData, Decryptable, Decrypting, EncryptData, Encrypting, Entity as NewEntity,
        EntityBase as NewEntityBase, EntityDatabaseMutation, KeyType as _,
    },
};

#[async_trait::async_trait(?Send)]
impl EntityBase for StoredPskBundle {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "mls_psk_bundles";

    fn to_missing_key_err_kind() -> MissingKeyErrorKind {
        MissingKeyErrorKind::StoredPskBundle
    }

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::PskBundle(self.into())
    }
}

#[async_trait::async_trait(?Send)]
impl EntityTransactionExt for StoredPskBundle {}

#[async_trait::async_trait(?Send)]
impl Entity for StoredPskBundle {
    fn id_raw(&self) -> &[u8] {
        self.psk_id.as_slice()
    }

    async fn find_all(conn: &mut Self::ConnectionType, params: EntityFindParams) -> CryptoKeystoreResult<Vec<Self>> {
        let storage = conn.storage();
        storage
            .get_all(<Self as EntityBase>::COLLECTION_NAME, Some(params))
            .await
    }

    async fn find_one(
        conn: &mut Self::ConnectionType,
        id: &StringEntityId,
    ) -> crate::CryptoKeystoreResult<Option<Self>> {
        conn.storage()
            .get(<Self as EntityBase>::COLLECTION_NAME, id.as_slice())
            .await
    }

    async fn count(conn: &mut Self::ConnectionType) -> crate::CryptoKeystoreResult<usize> {
        conn.storage().count(<Self as EntityBase>::COLLECTION_NAME).await
    }

    fn encrypt(&mut self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<()> {
        self.psk = <Self as Entity>::encrypt_data(self, cipher, self.psk.as_slice())?;
        Self::ConnectionType::check_buffer_size(self.psk.len())?;

        Ok(())
    }

    fn decrypt(&mut self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<()> {
        self.psk = self.decrypt_data(cipher, self.psk.as_slice())?;

        Ok(())
    }
}

impl NewEntityBase for StoredPskBundle {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "mls_psk_bundles";

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::PskBundle(self.into())
    }
}

#[async_trait(?Send)]
impl NewEntity for StoredPskBundle {
    type PrimaryKey = Sha256Hash;

    fn primary_key(&self) -> Self::PrimaryKey {
        Sha256Hash::hash_from(&self.psk_id)
    }

    async fn get(conn: &mut Self::ConnectionType, key: &Self::PrimaryKey) -> CryptoKeystoreResult<Option<Self>> {
        conn.storage().new_get(key.bytes().as_ref()).await
    }

    async fn count(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<u32> {
        conn.storage().new_count::<Self>().await
    }

    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        conn.storage().new_get_all().await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDatabaseMutation<'a> for StoredPskBundle {
    type Transaction = TransactionWrapper<'a>;

    async fn save(&'a self, tx: &Self::Transaction) -> CryptoKeystoreResult<()> {
        tx.new_save(self).await
    }

    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32> {
        tx.new_count::<Self>().await
    }

    async fn delete(tx: &Self::Transaction, id: &Self::PrimaryKey) -> CryptoKeystoreResult<bool> {
        tx.new_delete::<Self>(id.bytes().as_ref()).await
    }
}

#[derive(Serialize)]
pub struct StoredPskBundleEncrypt<'a> {
    psk_id: &'a [u8],
    psk: Vec<u8>,
}

impl<'a> Encrypting<'a> for StoredPskBundle {
    type EncryptedForm = StoredPskBundleEncrypt<'a>;

    fn encrypt(&'a self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::EncryptedForm> {
        let psk = <Self as EncryptData>::encrypt_data(self, cipher, &self.psk)?;
        Ok(StoredPskBundleEncrypt {
            psk_id: &self.psk_id,
            psk,
        })
    }
}

#[derive(Deserialize)]
pub struct StoredPskBundleDecrypt {
    psk_id: Vec<u8>,
    psk: Vec<u8>,
}

impl Decrypting<'static> for StoredPskBundleDecrypt {
    type DecryptedForm = StoredPskBundle;

    fn decrypt(self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::DecryptedForm> {
        let primary_key = Sha256Hash::hash_from(&self.psk_id);
        let psk = <StoredPskBundle as DecryptData>::decrypt_data(cipher, &primary_key, &self.psk)?;
        Ok(StoredPskBundle {
            psk_id: self.psk_id,
            psk,
        })
    }
}

impl Decryptable<'static> for StoredPskBundle {
    type DecryptableFrom = StoredPskBundleDecrypt;
}
