use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::{
    CryptoKeystoreResult,
    connection::idb_migration::legacy::{
        connection::{KeystoreDatabaseConnection, TransactionWrapper},
        traits::{
            DecryptData, Decryptable, Decrypting, EncryptData, Encrypting, Entity, EntityBase, EntityDatabaseMutation,
            EntityDeleteBorrowed, EntityGetBorrowed, KeyType as _,
        },
    },
    entities::PersistedMlsPendingGroup,
};

impl EntityBase for PersistedMlsPendingGroup {
    type ConnectionType = KeystoreDatabaseConnection;

    const TABLE_NAME: &'static str = "mls_pending_groups";
}

#[async_trait(?Send)]
impl Entity for PersistedMlsPendingGroup {
    async fn get(conn: &mut Self::ConnectionType, key: &Self::PrimaryKey) -> CryptoKeystoreResult<Option<Self>> {
        Self::get_borrowed(conn, key.as_ref()).await
    }

    async fn count(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<u32> {
        conn.storage().count::<Self>().await
    }

    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        conn.storage().get_all().await
    }
}

#[async_trait(?Send)]
impl EntityGetBorrowed for PersistedMlsPendingGroup {
    async fn get_borrowed(
        conn: &mut Self::ConnectionType,
        key: Self::BorrowedPrimaryKey<'_>,
    ) -> CryptoKeystoreResult<Option<Self>> {
        conn.storage().get(key.bytes().as_ref()).await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDatabaseMutation<'a> for PersistedMlsPendingGroup {
    type Transaction = TransactionWrapper<'a>;
    type AutoGeneratedFields = ();

    async fn save(&'a self, tx: &TransactionWrapper<'a>) -> CryptoKeystoreResult<()> {
        tx.save(self).await
    }

    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32> {
        tx.count::<Self>().await
    }

    async fn delete(tx: &Self::Transaction, id: &Self::PrimaryKey) -> CryptoKeystoreResult<bool> {
        Self::delete_borrowed(tx, id.as_ref()).await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDeleteBorrowed<'a> for PersistedMlsPendingGroup {
    async fn delete_borrowed(tx: &Self::Transaction, id: Self::BorrowedPrimaryKey<'_>) -> CryptoKeystoreResult<bool> {
        tx.delete::<Self>(id.bytes().as_ref()).await
    }
}

#[derive(Serialize)]
pub(crate) struct PersistedMlsPendingGroupEncrypt<'a> {
    id: &'a [u8],
    state: Vec<u8>,
    parent_id: &'a Option<Vec<u8>>,
    custom_configuration: &'a Vec<u8>,
}

impl<'a> Encrypting<'a> for PersistedMlsPendingGroup {
    type EncryptedForm = PersistedMlsPendingGroupEncrypt<'a>;

    fn encrypt(&'a self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::EncryptedForm> {
        let state = <Self as EncryptData>::encrypt_data(self, cipher, &self.state)?;

        Ok(PersistedMlsPendingGroupEncrypt {
            state,
            id: self.id.bytes(),
            parent_id: &self.parent_id,
            custom_configuration: &self.custom_configuration,
        })
    }
}

#[derive(Deserialize)]
pub(crate) struct PersistedMlsPendingGroupDecrypt {
    id: Vec<u8>,
    state: Vec<u8>,
    parent_id: Option<Vec<u8>>,
    custom_configuration: Vec<u8>,
}

impl Decrypting<'static> for PersistedMlsPendingGroupDecrypt {
    type DecryptedForm = PersistedMlsPendingGroup;

    fn decrypt(self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::DecryptedForm> {
        let id = self.id.as_slice().into();
        let state = <PersistedMlsPendingGroup as DecryptData>::decrypt_data(cipher, &id, &self.state)?;

        Ok(PersistedMlsPendingGroup {
            state,
            id,
            parent_id: self.parent_id,
            custom_configuration: self.custom_configuration,
        })
    }
}

impl Decryptable<'static> for PersistedMlsPendingGroup {
    type DecryptableFrom = PersistedMlsPendingGroupDecrypt;
}
