use async_trait::async_trait;
use js_sys::Uint8Array;
use serde::{Deserialize, Serialize};
use wasm_bindgen::JsValue;

use crate::{
    CryptoKeystoreResult, Sha256Hash,
    ancillary::ConversationId,
    connection::idb_migration::legacy::{
        connection::{KeystoreDatabaseConnection, TransactionWrapper},
        traits::{
            DecryptWithExplicitEncryptionKey as _, Decryptable, Decrypting, DeletableBySearchKey,
            EncryptWithExplicitEncryptionKey as _, Encrypting, EncryptionKey, Entity, EntityBase,
            EntityDatabaseMutation, SearchableEntity,
        },
    },
    traits::PrimaryKey,
};

/// A buffered message as stored by the final legacy IndexedDB schema and SQL schema V22.
///
/// V31 rebuilt `mls_pending_messages` around a hash primary key, and
/// [`MlsPendingMessage`][crate::entities::MlsPendingMessage] writes that shape. The import targets V22, where
/// the table is still `(id, message)`, so it needs a writer of its own.
#[derive(core_crypto_macros::Debug)]
pub(crate) struct LegacyMlsPendingMessage {
    pub(crate) conversation_id: Vec<u8>,
    #[sensitive]
    pub(crate) message: Vec<u8>,
}

impl LegacyMlsPendingMessage {
    /// Write this message into the V22 `mls_pending_messages` table.
    ///
    /// At V22 the conversation id lives in the column named `id`, and there is no primary key to conflict on.
    pub(crate) fn save(&self, tx: &rusqlite::Transaction<'_>) -> CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached("INSERT INTO mls_pending_messages (id, message) VALUES (?, ?)")?;
        stmt.execute((&self.conversation_id, &self.message))?;
        Ok(())
    }
}

impl PrimaryKey for LegacyMlsPendingMessage {
    type PrimaryKey = Sha256Hash;

    /// Derived as [`MlsPendingMessage`][crate::entities::MlsPendingMessage] derives its key.
    fn primary_key(&self) -> Self::PrimaryKey {
        let conversation_id_len = (self.conversation_id.len() as u64).to_be_bytes();
        Sha256Hash::hash_from_many([conversation_id_len.as_slice(), &self.conversation_id, &self.message])
    }
}

impl EntityBase for LegacyMlsPendingMessage {
    type ConnectionType = KeystoreDatabaseConnection;
    const TABLE_NAME: &'static str = "mls_pending_messages";
}

#[async_trait(?Send)]
impl Entity for LegacyMlsPendingMessage {
    async fn get(_conn: &mut Self::ConnectionType, _key: &Self::PrimaryKey) -> CryptoKeystoreResult<Option<Self>> {
        panic!("cannot get `LegacyMlsPendingMessage` by primary key as it has no distinct primary key")
    }

    async fn count(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<u32> {
        conn.storage().count::<Self>().await
    }

    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        conn.storage().get_all::<Self>().await
    }
}

#[async_trait(?Send)]
impl<'a> EntityDatabaseMutation<'a> for LegacyMlsPendingMessage {
    type Transaction = TransactionWrapper<'a>;
    type AutoGeneratedFields = ();

    async fn save(&'a self, tx: &Self::Transaction) -> CryptoKeystoreResult<()> {
        tx.save(self).await
    }

    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32> {
        tx.count::<Self>().await
    }

    async fn delete(_tx: &Self::Transaction, _id: &Self::PrimaryKey) -> CryptoKeystoreResult<bool> {
        panic!("cannot delete `LegacyMlsPendingMessage` by primary key as it has no distinct primary key")
    }
}

impl EncryptionKey for LegacyMlsPendingMessage {
    fn encryption_key(&self) -> &[u8] {
        &self.conversation_id
    }
}

/// The stored form of a pending message.
///
/// The conversation id is stored under the property name `foreign_id`: that is what every IndexedDB-writing
/// release called it, and rows in the field carry that name. The Rust-side field was renamed later, but the
/// serialized shape must stay as it was written.
#[derive(Serialize)]
pub(crate) struct MlsPendingMessageEncrypt<'a> {
    foreign_id: &'a [u8],
    message: Vec<u8>,
}

impl<'a> Encrypting<'a> for LegacyMlsPendingMessage {
    type EncryptedForm = MlsPendingMessageEncrypt<'a>;

    fn encrypt(&'a self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::EncryptedForm> {
        let message = self.encrypt_data_with_encryption_key(cipher, &self.message)?;
        Ok(MlsPendingMessageEncrypt {
            foreign_id: &self.conversation_id,
            message,
        })
    }
}

/// The stored form of a pending message, as read back; see [`MlsPendingMessageEncrypt`] for the property name.
#[derive(Deserialize)]
pub(crate) struct MlsPendingMessageDecrypt {
    foreign_id: Vec<u8>,
    message: Vec<u8>,
}

impl Decrypting<'static> for MlsPendingMessageDecrypt {
    type DecryptedForm = LegacyMlsPendingMessage;

    fn decrypt(self, cipher: &aes_gcm::Aes256Gcm) -> CryptoKeystoreResult<Self::DecryptedForm> {
        let message =
            LegacyMlsPendingMessage::decrypt_data_with_encryption_key(cipher, &self.foreign_id, &self.message)?;
        Ok(LegacyMlsPendingMessage {
            conversation_id: self.foreign_id,
            message,
        })
    }
}

impl Decryptable<'static> for LegacyMlsPendingMessage {
    type DecryptableFrom = MlsPendingMessageDecrypt;
}

#[async_trait(?Send)]
impl SearchableEntity<ConversationId> for LegacyMlsPendingMessage {
    async fn find_all_matching(
        conn: &mut Self::ConnectionType,
        conversation_id: &ConversationId,
    ) -> CryptoKeystoreResult<Vec<Self>> {
        let conversation_id = conversation_id.bytes();
        let storage = conn.storage();
        let id = JsValue::from(Uint8Array::from(conversation_id));
        storage.get_all_with_query(Some(id.into())).await
    }

    fn matches(&self, conversation_id: &ConversationId) -> bool {
        conversation_id.bytes() == self.conversation_id
    }
}

#[async_trait(?Send)]
impl<'a> DeletableBySearchKey<'a, ConversationId> for LegacyMlsPendingMessage {
    async fn delete_all_matching(tx: &Self::Transaction, conversation_id: &ConversationId) -> CryptoKeystoreResult<()> {
        tx.delete::<Self>(conversation_id.bytes()).await?;
        Ok(())
    }
}
