use async_trait::async_trait;
use rusqlite::params;

use crate::{
    CryptoKeystoreResult,
    connection::{KeystoreDatabaseConnection, TransactionWrapper},
    entities::{ConsumerData, count_helper, count_helper_tx, delete_helper, get_helper, load_all_helper},
    traits::{
        EncryptData, Encrypting, Entity as NewEntity, EntityBase as NewEntityBase, EntityDatabaseMutation,
        UniqueEntity as NewUniqueEntity, UniqueEntityImplementationHelper,
    },
};

impl NewEntityBase for ConsumerData {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "consumer_data";

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::ConsumerData(self.into())
    }
}

impl UniqueEntityImplementationHelper for ConsumerData {
    fn new(content: Vec<u8>) -> Self {
        Self { content }
    }

    fn content(&self) -> &[u8] {
        &self.content
    }
}
