// Wire
// Copyright (C) 2022 Wire Swiss GmbH

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.

export * from "../../shared/src/CoreCrypto";

import * as core_crypto_ffi from "./autogenerated/core_crypto_ffi";
import initWasm from "./autogenerated/wasm-bindgen/index";

/**
 * Initialises the wasm module necessary for running core crypto.
 *
 * @param path to the wasm module, e.g., on the local file system or a remote URL.
 *   If omitted the module is assumed be located at the root of the core crypto module.
 */
export async function initWasmModule(path: string | undefined = undefined) {
    if (typeof window !== "undefined") {
        if (typeof path === "string") {
            await initWasm({ module_or_path: path });
        } else {
            await initWasm({});
        }
    } else {
        throw Error(
            "initializing the wasm module of `@wireapp/core-crypto/browser` package outside the browser\
            isn't currently supported. Consider using the `@wireapp/core-crypto/native` package."
        );
    }
    // UBRN initialization
    // Initialize the generated bindings: mostly checksums, but also callbacks.
    // - the boolean flag ensures this loads exactly once, even if the JS code
    //   is reloaded (e.g. during development with metro).
    core_crypto_ffi.default.initialize();
}
