import { globalIgnores } from "eslint/config";
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-plugin-prettier/recommended";
import { configs as wdioConfig } from "eslint-plugin-wdio";

export default tseslint.config(
    globalIgnores([
        "packages/**/src/*.js",
        "packages/**/src*.d.ts",
        "packages/browser/src/autogenerated",
        "packages/browser/src/index.web.ts",
        "packages/native/src/autogenerated",
        "typedoc-ignore-warnings.cjs",
        "out",
    ]),
    eslint.configs.recommended,
    tseslint.configs.recommended,
    prettier,
    // @ts-expect-error TS2345
    wdioConfig["flat/recommended"],
    {
        rules: {
            "@typescript-eslint/no-unused-vars": [
                "error",
                {
                    // ignore vars, errors, etc which begin with an underscore
                    args: "all",
                    argsIgnorePattern: "^_",
                    caughtErrors: "all",
                    caughtErrorsIgnorePattern: "^_",
                    destructuredArrayIgnorePattern: "^_",
                    varsIgnorePattern: "^_",
                    // ignore `...rest` params when destructuring
                    ignoreRestSiblings: true,
                },
            ],
            "max-len": [
                "error",
                {
                    code: 120,
                    comments: 120,
                    ignoreUrls: true,
                    ignoreStrings: true,
                    ignoreTemplateLiterals: true,
                },
            ],
        },
    }
);
