[env]
EMCC_CFLAGS = "-Os --no-entry -lembind -s ENVIRONMENT=web -mbulk-memory -matomics -sEXPORTED_RUNTIME_METHODS=UTF8ArrayToString"

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=./support/wasm/gxx_personality_v0_stub.o",
    "-C", "link-args=--bind,--export-dynamic,-gsource-map,-Wl,--no-entry,--bulk-memory,--atomics",
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-ocorecrypto.html",
    "-C", "link-arg=-lidbfs.js",
    "-C", "link-arg=-lembind",
]
