use async_trait::async_trait;
use rusqlite::{Row, params};

use crate::{
    CryptoKeystoreResult, MissingKeyErrorKind,
    connection::{KeystoreDatabaseConnection, TransactionWrapper},
    entities::{
        Entity, EntityBase, EntityFindParams, EntityTransactionExt, ProteusPrekey, StringEntityId, count_helper,
        count_helper_tx, delete_helper, get_helper, load_all_helper,
    },
    traits::{Entity as NewEntity, EntityBase as NewEntityBase, EntityDatabaseMutation},
};

#[async_trait::async_trait]
impl Entity for ProteusPrekey {
    fn id_raw(&self) -> &[u8] {
        self.id_bytes()
    }

    async fn find_all(
        conn: &mut Self::ConnectionType,
        params: EntityFindParams,
    ) -> crate::CryptoKeystoreResult<Vec<Self>> {
        let mut conn = conn.conn().await;
        let transaction = conn.transaction()?;
        let query: String = format!("SELECT rowid, id FROM proteus_prekeys {}", params.to_sql());

        let mut stmt = transaction.prepare_cached(&query)?;
        let mut rows = stmt.query_map([], |r| Ok((r.get::<_, i64>(0)?, r.get::<_, u16>(1)?)))?;
        let entities = rows.try_fold(Vec::new(), |mut acc, query_result| {
            use std::io::Read as _;
            let (rowid, id) = query_result?;

            let mut blob = transaction.blob_open(rusqlite::MAIN_DB, "proteus_prekeys", "key", rowid, true)?;

            let mut buf = vec![];
            blob.read_to_end(&mut buf)?;
            blob.close()?;

            acc.push(Self::from_raw(id, buf));
            crate::CryptoKeystoreResult::Ok(acc)
        })?;

        Ok(entities)
    }

    async fn find_one(
        conn: &mut Self::ConnectionType,
        id: &StringEntityId,
    ) -> crate::CryptoKeystoreResult<Option<Self>> {
        let id = ProteusPrekey::id_from_slice(id.as_slice());

        let mut conn = conn.conn().await;
        let transaction = conn.transaction()?;

        use rusqlite::OptionalExtension as _;
        let maybe_row_id = transaction
            .query_row("SELECT rowid FROM proteus_prekeys WHERE id = ?", [id], |r| {
                r.get::<_, i64>(0)
            })
            .optional()?;

        if let Some(row_id) = maybe_row_id {
            let mut blob = transaction.blob_open(rusqlite::MAIN_DB, "proteus_prekeys", "key", row_id, true)?;

            use std::io::Read as _;
            let mut buf = Vec::with_capacity(blob.len());
            blob.read_to_end(&mut buf)?;
            blob.close()?;

            Ok(Some(Self::from_raw(id, buf)))
        } else {
            Ok(None)
        }
    }

    async fn count(conn: &mut Self::ConnectionType) -> crate::CryptoKeystoreResult<usize> {
        let conn = conn.conn().await;
        Ok(conn.query_row("SELECT COUNT(*) FROM proteus_prekeys", [], |r| r.get(0))?)
    }
}

#[async_trait::async_trait]
impl EntityBase for ProteusPrekey {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "proteus_prekeys";

    fn to_missing_key_err_kind() -> MissingKeyErrorKind {
        MissingKeyErrorKind::ProteusPrekey
    }

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::ProteusPrekey(self)
    }
}

#[async_trait::async_trait]
impl EntityTransactionExt for ProteusPrekey {
    async fn save(&self, transaction: &TransactionWrapper<'_>) -> crate::CryptoKeystoreResult<()> {
        use rusqlite::ToSql as _;

        // Use UPSERT (ON CONFLICT DO UPDATE)
        let sql = "
        INSERT INTO proteus_prekeys (id, key)
        VALUES (?, ?)
        ON CONFLICT(id) DO UPDATE SET key = excluded.key
        RETURNING rowid";

        // Create a zeroed blob for the key
        let zb_key = rusqlite::blob::ZeroBlob(self.prekey.len() as i32);

        // Execute the UPSERT and get the row_id of the affected row
        let row_id: i64 = transaction.query_row(sql, [self.id.to_sql()?, zb_key.to_sql()?], |r| r.get(0))?;

        // Write the actual prekey data into the blob
        let mut blob = transaction.blob_open(rusqlite::MAIN_DB, "proteus_prekeys", "key", row_id, false)?;

        use std::io::Write as _;
        blob.write_all(&self.prekey)?;
        blob.close()?;

        Ok(())
    }

    async fn delete_fail_on_missing_id(
        transaction: &TransactionWrapper<'_>,
        id: StringEntityId<'_>,
    ) -> crate::CryptoKeystoreResult<()> {
        let id = ProteusPrekey::id_from_slice(id.as_slice());
        let updated = transaction.execute("DELETE FROM proteus_prekeys WHERE id = ?", [id])?;
        if updated > 0 {
            Ok(())
        } else {
            Err(Self::to_missing_key_err_kind().into())
        }
    }
}

impl ProteusPrekey {
    fn from_row(row: &Row<'_>) -> rusqlite::Result<Self> {
        let id = row.get("id")?;
        let prekey = row.get("key")?;
        Ok(Self::from_raw(id, prekey))
    }
}

impl NewEntityBase for ProteusPrekey {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "proteus_prekeys";

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::ProteusPrekey(self)
    }
}

#[async_trait]
impl NewEntity for ProteusPrekey {
    type PrimaryKey = u16;

    fn primary_key(&self) -> u16 {
        self.id
    }

    async fn get(conn: &mut Self::ConnectionType, key: &u16) -> CryptoKeystoreResult<Option<Self>> {
        get_helper::<Self, _>(conn, "id", *key, Self::from_row).await
    }

    async fn count(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<u32> {
        count_helper::<Self>(conn).await
    }

    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        load_all_helper::<Self, _>(conn, Self::from_row).await
    }
}

#[async_trait]
impl<'a> EntityDatabaseMutation<'a> for ProteusPrekey {
    type Transaction = TransactionWrapper<'a>;

    async fn save(&'a self, tx: &Self::Transaction) -> CryptoKeystoreResult<()> {
        let mut stmt = tx.prepare_cached("INSERT INTO proteus_prekeys (id, key) VALUES (?, ?)")?;
        stmt.execute(params![self.id, self.prekey])?;
        Ok(())
    }

    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32> {
        count_helper_tx::<Self>(tx).await
    }

    async fn delete(tx: &Self::Transaction, id: &u16) -> CryptoKeystoreResult<bool> {
        delete_helper::<Self>(tx, "id", *id).await
    }
}
