use crate::{
    CryptoKeystoreResult, Entity, EntityBase, EntityTransactionExt,
    connection::{KeystoreDatabaseConnection, TransactionWrapper},
    entities::ProteusPrekey,
};

use rusqlite::{OptionalExtension as _, ToSql};

#[async_trait::async_trait]
impl EntityBase for ProteusPrekey {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "proteus_prekeys";

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::ProteusPrekey(self)
    }
}

#[async_trait::async_trait]
impl Entity for ProteusPrekey {
    /// Each distinct [`PrimaryKey`] uniquely identifies either 0 or 1 instance.
    ///
    /// This constraint should be enforced at the DB level.
    type PrimaryKey = u16;

    /// Get this entity's primary key.
    fn primary_key(&self) -> Self::PrimaryKey {
        self.id
    }

    /// Get an entity by its primary key.
    async fn get(conn: &mut Self::ConnectionType, id: &u16) -> CryptoKeystoreResult<Option<Self>> {
        let id = *id;

        let conn = conn.conn().await;
        let mut statement = conn.prepare_cached("SELECT key FROM proteus_prekeys WHERE id = ?")?;
        statement
            .query_row([id], |row| {
                let prekey = row.get(0)?;
                Ok(Self::from_raw(id, prekey))
            })
            .optional()
            .map_err(Into::into)
    }

    /// Count the number of entities of this type in the database.
    async fn count(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<u32> {
        let conn = conn.conn().await;
        let mut statement = conn.prepare_cached("SELECT count(*) FROM proteus_prekeys")?;
        statement.query_one([], |row| row.get(0)).map_err(Into::into)
    }

    /// Retrieve all entities of this type from the database.
    async fn load_all(conn: &mut Self::ConnectionType) -> CryptoKeystoreResult<Vec<Self>> {
        let mut conn = conn.conn().await;
        let transaction = conn.transaction()?;

        let mut statement = transaction.prepare_cached("SELECT id, key FROM proteus_prekeys")?;
        statement
            .query_map([], |row| {
                let id = row.get(0)?;
                let prekey = row.get(1)?;
                Ok(Self::from_raw(id, prekey))
            })?
            .collect::<Result<_, _>>()
            .map_err(Into::into)
    }
}

#[async_trait::async_trait]
impl<'a> EntityTransactionExt<'a> for ProteusPrekey {
    type Transaction = TransactionWrapper<'a>;

    /// Use the transaction's interface to save this entity to the database
    async fn save(&self, tx: &Self::Transaction) -> CryptoKeystoreResult<()> {
        // Use UPSERT (ON CONFLICT DO UPDATE)
        let sql = "
        INSERT INTO proteus_prekeys (id, key)
        VALUES (?, ?)
        ON CONFLICT(id) DO UPDATE SET key = excluded.key";

        let mut statement = tx.prepare_cached(sql)?;
        statement.execute([self.id.to_sql()?, self.prekey.to_sql()?])?;
        Ok(())
    }

    /// Use the transaction's inteface to delete this entity from the database.
    ///
    /// Returns `true` if at least one entity was deleted, or `false` if the id was not found in the database.
    async fn delete(tx: &Self::Transaction, id: &u16) -> CryptoKeystoreResult<bool> {
        let id = *id;
        let mut statement = tx.prepare_cached("DELETE FROM proteus_prekeys WHERE id = ?")?;
        let updated = statement.execute([id])?;
        Ok(updated > 0)
    }
}
