import { browser } from "@wdio/globals";
import type { Bench } from "tinybench";
import type { local } from "webdriver";
import {
    Ciphersuite,
    CoreCrypto,
    CoreCryptoLogLevel,
    type CommitBundle,
    type HistorySecret,
    type MlsTransport,
    type MlsTransportData,
} from "@wireapp/core-crypto/browser";
import { isNumberObject } from "node:util/types";
import { mkdir } from "node:fs/promises";
import { writeFile } from "node:fs/promises";
type ccModuleType = typeof import("@wireapp/core-crypto/browser");
declare global {
    interface Window {
        ccModule: ccModuleType;
        deliveryService: DeliveryService;
        _latestCommitBundle: CommitBundle;
        tinybench: typeof import("tinybench");
        benchRunning: boolean;
        bench: Bench;
        helpers: BenchmarkHelpers;
    }
}

const logLevel = Number(process.env["CC_TEST_LOG_LEVEL"] || "0");

export async function setup() {
    if ((await browser.getUrl()) === "about:blank") {
        await browser.url("/html/index.html");
    }

    browser.on("log.entryAdded", logEvents);
    await browser.execute(async (loglevel) => {
        if (window.tinybench === undefined) {
            window.tinybench =
                // @ts-expect-error TS2307: Cannot find module ./corecrypto.js or its corresponding type declarations.
                await import("/node_modules/tinybench/dist/index.js");
        }
        if (window.ccModule === undefined) {
            // @ts-expect-error TS2307: Cannot find module ./corecrypto.js or its corresponding type declarations.
            window.ccModule = await import("/corecrypto.js");
            await window.ccModule.initWasmModule(
                "/autogenerated/wasm-bindgen/"
            );

            if (loglevel >= 2) {
                window.ccModule.setLogger({
                    log: (
                        _level: CoreCryptoLogLevel,
                        message: string,
                        context: string | undefined
                    ) => {
                        console.log(message, context);
                    },
                });
                window.ccModule.setMaxLogLevel(
                    window.ccModule.CoreCryptoLogLevel.Debug
                );
            }
        }

        if (window.deliveryService === undefined) {
            window.deliveryService = {
                async sendCommitBundle(commitBundle: CommitBundle) {
                    window._latestCommitBundle = commitBundle;
                },
                async prepareForTransport(
                    secret: HistorySecret
                ): Promise<MlsTransportData> {
                    return Promise.resolve(secret.clientId.copyBytes());
                },
                async getLatestCommitBundle() {
                    return window._latestCommitBundle;
                },
            };
        }

        class BenchmarkHelpers {
            static async setupCc(
                cipherSuite: Ciphersuite,
                clientIdStr?: string
            ): Promise<CoreCrypto> {
                if (clientIdStr === undefined) {
                    clientIdStr = window.crypto.randomUUID();
                }

                const encoder = new TextEncoder();
                const clientId = new window.ccModule.ClientId(
                    encoder.encode(clientIdStr).buffer
                );

                const key = new Uint8Array(32);
                crypto.getRandomValues(key);

                const db = await window.ccModule.Database.open(
                    clientIdStr,
                    new window.ccModule.DatabaseKey(key.buffer)
                );

                const cc = window.ccModule.CoreCrypto.new(db);

                await cc.transaction(async (ctx) => {
                    await ctx.mlsInit(clientId, window.deliveryService);
                    await ctx.addCredential(
                        window.ccModule.Credential.basic(cipherSuite, clientId)
                    );
                });
                return cc;
            }
        }
        window.helpers = BenchmarkHelpers;
    }, logLevel);
}

interface DeliveryService extends MlsTransport {
    getLatestCommitBundle: () => Promise<CommitBundle>;
}

interface BenchmarkHelpers {
    setupCc: (
        cipherSuite: Ciphersuite,
        clientIdStr?: string
    ) => Promise<CoreCrypto>;
}

export type CustomBenchmarkEntry = {
    name: string;
    unit: string;
    value: number;
    range?: string;
    extra?: string;
};

function parseMetric(metric?: string | number) {
    if (!metric) return null;

    if (isNumberObject(metric)) {
        return {
            metric,
            range: undefined,
        };
    } else {
        const [rawValue, rawRange] = metric
            .split("±")
            .map((part) => part.trim());

        const value =
            rawValue !== undefined ? Number.parseFloat(rawValue) : undefined;

        if (Number.isNaN(value)) return null;

        return {
            value,
            range: rawRange,
        };
    }
}

export function toCustomBenchmarkEntries(
    benchmarkName: string | undefined,
    rows: (Record<string, string | number | undefined> | null)[]
): CustomBenchmarkEntry[] {
    return rows.map((row) => {
        const throughput = parseMetric(row?.["Throughput avg (ops/s)"]);
        const extra = [
            row?.["Latency avg (ns)"]
                ? `Average Latency (ns): ${row["Latency avg (ns)"]}`
                : null,
            row?.["Latency med (ns)"]
                ? `Median Latency (ns): ${row["Latency med (ns)"]}`
                : null,
            row?.["Throughput med (ops/s)"]
                ? `Median Throughput (ops/s): ${row["Throughput med (ops/s)"]}`
                : null,
            row?.["Samples"] !== undefined
                ? `Samples: ${row["Samples"]}`
                : null,
        ]
            .filter(Boolean)
            .join("\n");

        return {
            name: `${benchmarkName} - ${row?.["Task name"]}`,
            unit: "ops/s",
            value: throughput?.value ?? 0,
            range: throughput?.range,
            extra: extra || undefined,
        };
    });
}

function logEvents(entry: local.LogEntry) {
    if (logLevel >= 1) {
        console.log(`[${entry.level}] ${entry.text}`);
    }
}

/*
Helper method to:
1. Poll until the benchmark is done
2. Retrieve the results
3. Print results and save them to file if in CI
*/
export async function collect_benchmark_results() {
    // 2. Poll until benchmark is done
    await browser.waitUntil(
        async () => {
            return !(await browser.execute(() => window.benchRunning));
        },
        {
            timeout: 1_800_000, // 30 min
            timeoutMsg: "Benchmark did not finish in time",
        }
    );

    // 3. Retrieve results
    const results = await browser.execute(() => {
        return { name: window.bench.name, table: window.bench.table() };
    });

    console.log(results.name);
    console.log(results.table);

    if (!process.env["CI"]) return;

    const customResults = toCustomBenchmarkEntries(results.name, results.table);

    await mkdir("benches_result", { recursive: true });
    await writeFile(
        `benches_result/${results.name}.json`,
        JSON.stringify(customResults, null, 2)
    );
}
