const path = require("path");


// config.set({
//     logLevel: config.LOG_DEBUG,
//
//     browserConsoleLogOptions: {
//         level: "debug",
//         terminal: true,
//         format: "%b %T: %m",
//     },
//
//     // Optional: use non-headless Chrome while debugging
//     singleRun: false,
//     autoWatch: true,
//     browsers: ["Chrome"],
// });

config.plugins = config.plugins || [];

config.plugins.push({
    "middleware:requestLogger": ["factory", function () {
        return function (req, res, next) {
            console.log(`${req.method} ${req.url}`);
            next();
        };
    }],
});

config.webpackCopy = config.webpackCopy || [];
config.webpackCopy.push(
    path.resolve(
        __dirname,
        "../../node_modules/@wireapp/core-crypto/dist/browser/autogenerated/wasm-bindgen/index_bg.wasm"
    )
);

config.set({
    beforeMiddleware: ["requestLogger"],
});


const wasmPath = path.resolve(
    __dirname,
    "../../node_modules/@wireapp/core-crypto/dist/browser/autogenerated/wasm-bindgen/index_bg.wasm"
);

config.files = config.files || [];
config.files.push({
    pattern: wasmPath,
    included: false,
    served: true,
    watched: false,
    nocache: true,
});

config.proxies = Object.assign(config.proxies || {}, {
    "/index_bg.wasm": "/absolute" + wasmPath,
});
