use proc_macro2::TokenStream;
use quote::{ToTokens, quote};
use syn::{Type, parse_quote};

fn string_types() -> [Type; 3] {
    [
        parse_quote!(String),
        parse_quote!(std::string::String),
        parse_quote!(core::string::String),
    ]
}

fn bytes_types() -> [Type; 3] {
    [
        parse_quote!(Vec<u8>),
        parse_quote!(std::vec::Vec<u8>),
        parse_quote!(core::vec::Vec<u8>),
    ]
}

fn optional_types(ty: &Type) -> [Type; 3] {
    [
        parse_quote!(Option<#ty>),
        parse_quote!(std::option::Option<#ty>),
        parse_quote!(core::option::Option<#ty>),
    ]
}

fn u32_types() -> [Type; 3] {
    [
        parse_quote!(u32),
        parse_quote!(std::primitive::u32),
        parse_quote!(core::primitive::u32),
    ]
}

/// Legal types for an ID column
#[derive(PartialEq, Eq)]
pub(super) enum IdColumnType {
    String,
    Bytes,
}

impl TryFrom<Type> for IdColumnType {
    type Error = syn::Error;

    fn try_from(ty: Type) -> Result<Self, Self::Error> {
        if string_types().contains(&ty) {
            Ok(Self::String)
        } else if bytes_types().contains(&ty) {
            Ok(Self::Bytes)
        } else {
            let type_string = ty.to_token_stream().to_string();
            Err(syn::Error::new_spanned(
                ty,
                format!("Expected `String` or `Vec<u8>`, not `{type_string}`"),
            ))
        }
    }
}

impl IdColumnType {
    /// emit the owned form of this type
    pub(super) fn owned(&self) -> TokenStream {
        match self {
            Self::String => quote!(String),
            Self::Bytes => quote!(Vec<u8>),
        }
    }

    /// emit the borrowed form of this type
    ///
    /// Note that this is emitted _without_ a leading `&`.
    ///
    /// This is convenient for deriving `BorrowPrimaryKey`.
    pub(super) fn borrowed(&self) -> TokenStream {
        match self {
            Self::String => quote!(str),
            Self::Bytes => quote!([u8]),
        }
    }

    /// emit statements rebinding a borrowed primary key into a form suitable for SQL binding
    ///
    /// This assumes that a variable `key: &Self::BorrowedPrimaryKey` is in scope, and leaves a
    /// variable of the same name in scope holding a value implementing [`rusqlite::ToSql`].
    ///
    /// The emitted binding must produce the same SQLite storage class as the insert statement
    /// generated by `store_expression`, which binds the id field directly. SQLite never compares a
    /// `BLOB` equal to a `TEXT` value, and column affinity does not coerce a `BLOB` argument, so
    /// binding a string key as bytes would silently match zero rows.
    pub(super) fn bind_key(&self) -> TokenStream {
        match self {
            // already a `&str`, which binds as `TEXT` just like the insert does
            Self::String => quote!(),
            Self::Bytes => quote! {
                let key = <&<Self as crate::traits::BorrowPrimaryKey>::BorrowedPrimaryKey
                    as crate::traits::KeyType>::bytes(&key);
                let key = key.as_ref();
            },
        }
    }
}

/// Legal types for any other column
#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum ColumnType {
    String,
    Bytes,
    OptionalBytes,
    U32,
}

impl TryFrom<Type> for ColumnType {
    type Error = syn::Error;

    fn try_from(ty: Type) -> Result<Self, Self::Error> {
        if string_types().contains(&ty) {
            Ok(Self::String)
        } else if bytes_types().contains(&ty) {
            Ok(Self::Bytes)
        } else if bytes_types().iter().flat_map(optional_types).any(|o_type| o_type == ty) {
            Ok(Self::OptionalBytes)
        } else if u32_types().contains(&ty) {
            Ok(Self::U32)
        } else {
            let type_string = ty.to_token_stream().to_string();
            Err(syn::Error::new_spanned(
                ty,
                format!("Expected `String`, `Vec<u8>`, `Option<Vec<u8>>`, or `u32`, not `{type_string}`"),
            ))
        }
    }
}

pub(super) trait EmitGetExpression {
    /// Emit an expression with the rust type which should be used in the rusqlite `get` expression
    fn get_as_type(&self) -> TokenStream;
}

impl EmitGetExpression for IdColumnType {
    fn get_as_type(&self) -> TokenStream {
        match self {
            IdColumnType::Bytes => quote!(Vec<u8>),
            IdColumnType::String => quote!(String),
        }
    }
}

impl EmitGetExpression for ColumnType {
    fn get_as_type(&self) -> TokenStream {
        match self {
            ColumnType::Bytes => quote!(Vec<u8>),
            ColumnType::String => quote!(String),
            ColumnType::OptionalBytes => quote!(Option<Vec<u8>>),
            ColumnType::U32 => quote! {u32},
        }
    }
}
