use crate::{
    MissingKeyErrorKind,
    connection::KeystoreDatabaseConnection,
    entities::{ConsumerData, EntityBase, UniqueEntity},
};

#[async_trait::async_trait(?Send)]
impl EntityBase for ConsumerData {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "consumer_data";

    fn to_missing_key_err_kind() -> MissingKeyErrorKind {
        MissingKeyErrorKind::ConsumerData
    }

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::ConsumerData(self)
    }
}

#[async_trait::async_trait(?Send)]
impl UniqueEntity for ConsumerData {
    fn content(&self) -> &[u8] {
        &self.content
    }

    fn set_content(&mut self, content: Vec<u8>) {
        self.content = content;
    }
}
