name: Setup rust and cache artifacts
description: Sets up rust, and caches build artifacts. Runs scripts/clean.sh post action.
inputs:
  target:
    description: Rust target
    required: false
  rustflags:
    description: Set the value of RUSTFLAGS (set to empty string to avoid overwriting existing flags)
    required: false
    default: -D warnings
  components:
    description: Additional components to install that don't come with the toolchain by default.
    required: false
    default: ''
  cache-key-prefix:
    description: A custom cache key prefix to be used instead of the rust target. Must be used if there are
      multiple rust targets because keys cannot contain commas.
    required: false
runs:
  using: composite
  steps:
    - name: no brew auto update
      shell: bash
      run: |
        echo HOMEBREW_NO_AUTO_UPDATE=1 >> $GITHUB_ENV
        echo HOMEBREW_NO_INSTALL_UPGRADE=1 >> $GITHUB_ENV
    - name:
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ inputs.target }}
        rustflags: ${{ inputs.rustflags }}
        components: ${{ inputs.components }}
        cache: false
    - name: Cleanup on post
      uses: gacts/run-and-post-run@v1
      with:
          post: |
            sh ./scripts/clean.sh
    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ inputs.cache-key-prefix || format('{0}', inputs.target) }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
