name: Fetch or make ffi library

inputs:
  gh-token:
    required: true

runs:
  using: composite

  steps:
    - name: ffi library extension
      run: |
        os="$(uname -s)"
        echo "ARTIFACT_NAME=uniffi-${os}" >> $GITHUB_ENV
        if [ "$os" = "Linux" ]; then
          library_extension="so"
        elif [ "$os" = "Darwin" ]; then
          library_extension="dylib"
        fi
        echo "LIBRARY_EXTENSION=${library_extension}" >> $GITHUB_ENV
      shell: bash -euo pipefail {0}

    - uses: ./.github/actions/make
      with:
        key: libcore_crypto_ffi.${{ env.LIBRARY_EXTENSION }}
        make-rule: ffi-library
        target-path: target/release/libcore_crypto_ffi.${{ env.LIBRARY_EXTENSION }}
        gh-token: ${{ inputs.gh-token }}
        uses-rust: true
        rust-target: x86_64-unknown-linux-gnu
