[advisories]
ignore = [
    # ? `sodiumoxide` is only used in tests
    "RUSTSEC-2021-0137",
    # ? There's no fix currently for the Marvin attack
    # - https://github.com/RustCrypto/RSA/issues/390
    # -https://github.com/RustCrypto/RSA/pull/394
    "RUSTSEC-2023-0071",
    # ? Only used in wasm-browser-run
    "RUSTSEC-2023-0072"
]
