use std::{
    io::{Read, Write},
    time::SystemTime,
};

use rusqlite::Transaction;

use crate::{
    CryptoKeystoreError, CryptoKeystoreResult, MissingKeyErrorKind,
    connection::{DatabaseConnection, KeystoreDatabaseConnection, TransactionWrapper},
    entities::{
        Entity, EntityBase, EntityFindParams, EntityTransactionExt, MlsCredentialExt, StoredCredential, StringEntityId,
    },
};

impl StoredCredential {
    fn load(
        transaction: &Transaction<'_>,
        rowid: i64,
        created_at: u64,
        ciphersuite: u16,
    ) -> CryptoKeystoreResult<Self> {
        let mut blob = transaction.blob_open(rusqlite::MAIN_DB, Self::COLLECTION_NAME, "id", rowid, true)?;
        let mut id = vec![];
        blob.read_to_end(&mut id)?;
        blob.close()?;

        let mut blob = transaction.blob_open(rusqlite::MAIN_DB, Self::COLLECTION_NAME, "credential", rowid, true)?;
        let mut credential = vec![];
        blob.read_to_end(&mut credential)?;
        blob.close()?;

        let mut blob = transaction.blob_open(rusqlite::MAIN_DB, Self::COLLECTION_NAME, "secret_key", rowid, true)?;
        let mut secret_key = vec![];
        blob.read_to_end(&mut secret_key)?;
        blob.close()?;

        let mut blob = transaction.blob_open(rusqlite::MAIN_DB, Self::COLLECTION_NAME, "public_key", rowid, true)?;
        let mut public_key = vec![];
        blob.read_to_end(&mut public_key)?;
        blob.close()?;

        Ok(Self {
            id,
            credential,
            ciphersuite,
            created_at,
            public_key,
            secret_key,
        })
    }
}

#[async_trait::async_trait]
impl Entity for StoredCredential {
    fn id_raw(&self) -> &[u8] {
        self.id.as_slice()
    }

    fn merge_key(&self) -> Vec<u8> {
        // Credentials are unique by id and type, the type is contained in the bytes
        // inside self.credential.
        self.id_raw().iter().chain(self.credential.iter()).cloned().collect()
    }
    async fn find_all(
        conn: &mut Self::ConnectionType,
        params: EntityFindParams,
    ) -> crate::CryptoKeystoreResult<Vec<Self>> {
        let mut conn = conn.conn().await;
        let transaction = conn.transaction()?;
        let query: String = format!(
            "SELECT rowid, unixepoch(created_at), ciphersuite FROM mls_credentials {}",
            params.to_sql()
        );

        transaction
            .prepare_cached(&query)?
            .query_map([], |row| {
                let rowid = row.get(0)?;
                let created_at = row.get(1)?;
                let ciphersuite = row.get(2)?;
                Ok((rowid, created_at, ciphersuite))
            })?
            .map(|rowid_result| -> CryptoKeystoreResult<_> {
                let (rowid, created_at, ciphersuite) = rowid_result?;
                Self::load(&transaction, rowid, created_at, ciphersuite)
            })
            .collect()
    }

    async fn find_one(
        conn: &mut Self::ConnectionType,
        id: &StringEntityId,
    ) -> crate::CryptoKeystoreResult<Option<Self>> {
        let mut conn = conn.conn().await;
        let transaction = conn.transaction()?;
        use rusqlite::OptionalExtension as _;
        transaction
            .query_row(
                "SELECT rowid, unixepoch(created_at), ciphersuite FROM mls_credentials WHERE id = ?",
                [id.as_slice()],
                |r| Ok((r.get::<_, i64>(0)?, r.get(1)?, r.get(2)?)),
            )
            .optional()?
            .map(|(rowid, created_at, ciphersuite)| Self::load(&transaction, rowid, created_at, ciphersuite))
            .transpose()
    }

    async fn count(conn: &mut Self::ConnectionType) -> crate::CryptoKeystoreResult<usize> {
        let conn = conn.conn().await;
        conn.query_row("SELECT COUNT(*) FROM mls_credentials", [], |r| r.get(0))
            .map_err(Into::into)
    }
}

#[async_trait::async_trait]
impl EntityBase for StoredCredential {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = u64;
    const COLLECTION_NAME: &'static str = "mls_credentials";

    fn to_missing_key_err_kind() -> MissingKeyErrorKind {
        MissingKeyErrorKind::StoredCredential
    }

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::StoredCredential(self)
    }
}

#[async_trait::async_trait]
impl EntityTransactionExt for StoredCredential {
    async fn save(&self, transaction: &TransactionWrapper<'_>) -> crate::CryptoKeystoreResult<()> {
        Self::ConnectionType::check_buffer_size(self.id.len())?;
        Self::ConnectionType::check_buffer_size(self.credential.len())?;
        Self::ConnectionType::check_buffer_size(self.secret_key.len())?;
        Self::ConnectionType::check_buffer_size(self.public_key.len())?;

        let zb_id = rusqlite::blob::ZeroBlob(self.id.len() as i32);
        let zb_cred = rusqlite::blob::ZeroBlob(self.credential.len() as i32);
        let zb_pk = rusqlite::blob::ZeroBlob(self.public_key.len() as i32);
        let zb_sk = rusqlite::blob::ZeroBlob(self.secret_key.len() as i32);

        use rusqlite::ToSql as _;
        let params: [rusqlite::types::ToSqlOutput; 6] = [
            zb_id.to_sql()?,
            zb_cred.to_sql()?,
            self.created_at.to_sql()?,
            self.ciphersuite.to_sql()?,
            zb_pk.to_sql()?,
            zb_sk.to_sql()?,
        ];

        let sql = "INSERT INTO mls_credentials (id, credential, created_at, ciphersuite, public_key, secret_key) VALUES (?, ?, datetime(?, 'unixepoch'), ?, ?, ?)";
        transaction.execute(sql, params)?;
        let row_id = transaction.last_insert_rowid();

        let mut blob = transaction.blob_open(rusqlite::MAIN_DB, Self::COLLECTION_NAME, "id", row_id, false)?;

        blob.write_all(&self.id)?;
        blob.close()?;

        let mut blob = transaction.blob_open(rusqlite::MAIN_DB, Self::COLLECTION_NAME, "credential", row_id, false)?;

        blob.write_all(&self.credential)?;
        blob.close()?;

        let mut blob = transaction.blob_open(rusqlite::MAIN_DB, Self::COLLECTION_NAME, "public_key", row_id, false)?;

        blob.write_all(&self.public_key)?;
        blob.close()?;

        let mut blob = transaction.blob_open(rusqlite::MAIN_DB, Self::COLLECTION_NAME, "secret_key", row_id, false)?;

        blob.write_all(&self.secret_key)?;
        blob.close()?;

        Ok(())
    }

    async fn pre_save<'a>(&'a mut self) -> CryptoKeystoreResult<Self::AutoGeneratedFields> {
        let now = SystemTime::now();
        let created_at = now
            .duration_since(SystemTime::UNIX_EPOCH)
            .map_err(|_| CryptoKeystoreError::TimestampError)?
            .as_secs();
        self.created_at = created_at;
        Ok(created_at)
    }

    async fn delete_fail_on_missing_id(
        transaction: &TransactionWrapper<'_>,
        id: StringEntityId<'_>,
    ) -> crate::CryptoKeystoreResult<()> {
        let updated = transaction.execute("DELETE FROM mls_credentials WHERE id = ?", [id.as_slice()])?;

        if updated > 0 {
            Ok(())
        } else {
            Err(Self::to_missing_key_err_kind().into())
        }
    }
}

#[async_trait::async_trait]
impl MlsCredentialExt for StoredCredential {
    async fn delete_by_credential(
        transaction: &TransactionWrapper<'_>,
        credential: Vec<u8>,
    ) -> CryptoKeystoreResult<()> {
        // we do not have an index on this since we'll never have more than a handful of credentials in the sotre (~40 max)
        transaction.execute("DELETE FROM mls_credentials WHERE credential = ?", [&credential[..]])?;
        Ok(())
    }
}
