use async_trait::async_trait;
use rusqlite::params;

use crate::{
    CryptoKeystoreResult, MissingKeyErrorKind,
    connection::{KeystoreDatabaseConnection, TransactionWrapper},
    entities::{
        ConsumerData, E2eiAcmeCA, EntityBase, UniqueEntity, count_helper, count_helper_tx, delete_helper, get_helper,
        load_all_helper,
    },
    traits::{
        EncryptData, Encrypting, Entity as NewEntity, EntityBase as NewEntityBase, EntityDatabaseMutation,
        UniqueEntity as NewUniqueEntity, UniqueEntityImplementationHelper,
    },
};

impl UniqueEntity for E2eiAcmeCA {
    fn new(content: Vec<u8>) -> Self {
        Self { content }
    }
    fn content(&self) -> &[u8] {
        &self.content
    }
}

impl EntityBase for E2eiAcmeCA {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();

    const COLLECTION_NAME: &'static str = "e2ei_acme_ca";

    fn to_missing_key_err_kind() -> MissingKeyErrorKind {
        MissingKeyErrorKind::E2eiAcmeCA
    }

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::E2eiAcmeCA(self.into())
    }
}

impl NewEntityBase for E2eiAcmeCA {
    type ConnectionType = KeystoreDatabaseConnection;
    type AutoGeneratedFields = ();
    const COLLECTION_NAME: &'static str = "e2ei_acme_ca";

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity {
        crate::transaction::dynamic_dispatch::Entity::E2eiAcmeCA(self.into())
    }
}

impl UniqueEntityImplementationHelper for E2eiAcmeCA {
    fn new(content: Vec<u8>) -> Self {
        Self { content }
    }
    fn content(&self) -> &[u8] {
        &self.content
    }
}
