use std::{borrow::Borrow, collections::HashMap};

use openmls_traits::OpenMlsCryptoProvider as _;
use uuid::Uuid;

use super::{Error, Result};
use crate::{
    ClientIdRef, CredentialType, E2eiConversationState, RecursiveError, Session, WireIdentity,
    mls::credential::ext::CredentialExt as _,
};

impl super::Conversation {
    /// Indicates when to mark a conversation as not verified i.e. when not all its members have a X509
    /// Credential generated by Wire's end-to-end identity enrollment
    pub async fn e2ei_conversation_state(&self) -> Result<E2eiConversationState> {
        let backend = &self.session.crypto_provider;

        let state = Session::compute_conversation_state(
            self.cipher_suite(),
            self.group().await.members_credentials(),
            CredentialType::X509,
            backend.authentication_service(),
        )
        .await;
        Ok(state)
    }

    /// From a given conversation, get the identity of the members supplied.
    ///
    /// An identity is returned for every requested member which is in the conversation, whatever
    /// its credential type. Members with an X509 credential (i.e. after turning on end-to-end
    /// identity) additionally carry a [`WireIdentity::x509_identity`]; members with a basic
    /// credential do not, and their `status` is always `Valid`, which on its own is no evidence of
    /// end-to-end identity enrolment.
    pub async fn get_device_identities(
        &self,
        device_ids: &[impl Borrow<ClientIdRef> + Sync],
    ) -> Result<Vec<WireIdentity>> {
        if device_ids.is_empty() {
            return Err(Error::CallerError(
                "This function accepts a list of IDs as a parameter, but that list was empty.",
            ));
        }
        let mls_provider = &self.session.crypto_provider;
        let auth_service = mls_provider.authentication_service();

        let pki_env = auth_service.pki_env().await;

        let mut identities = vec![];
        for (id, credential) in self.members_with_key().await? {
            if device_ids.iter().any(|client_id| client_id.borrow() == id.as_slice()) {
                identities.push(
                    credential
                        .extract_identity(self.cipher_suite(), pki_env.as_deref())
                        .await
                        .map_err(RecursiveError::context("extracting identity"))?,
                );
            }
        }
        Ok(identities)
    }

    /// From a given conversation, get the identity of the users (device holders) supplied.
    ///
    /// As with [`Self::get_device_identities`], an identity is returned for every device of every
    /// requested user, whatever its credential type; only devices with an X509 credential carry a
    /// [`WireIdentity::x509_identity`].
    ///
    /// Returns a Map with all the identities for a given users. Consumers are then recommended to
    /// reduce those identities to determine the actual status of a user.
    pub async fn get_user_identities(&self, user_ids: &[Uuid]) -> Result<HashMap<Uuid, Vec<WireIdentity>>> {
        if user_ids.is_empty() {
            return Err(Error::CallerError(
                "This function accepts a list of IDs as a parameter, but that list was empty.",
            ));
        }
        let mls_provider = &self.session.crypto_provider;
        let auth_service = mls_provider.authentication_service();

        let pki_env = auth_service.pki_env().await;

        let mut identities = HashMap::new();
        for (id, credential) in self.members_with_key().await? {
            let user_id = &id.deserialize().user_id;

            if !user_ids.contains(user_id) {
                continue;
            }

            let identity = credential
                .extract_identity(self.cipher_suite(), pki_env.as_deref())
                .await
                .map_err(RecursiveError::context("extracting identity"))?;
            let value = identities.entry(*user_id).or_insert_with(Vec::new);
            value.push(identity);
        }

        Ok(identities)
    }
}
