use std::borrow::Borrow;

use async_trait::async_trait;
use rusqlite::Transaction;

use crate::{
    CryptoKeystoreResult,
    traits::{BorrowPrimaryKey, Entity, KeyType, PrimaryKey, UnifiedEntity},
};

/// Extend an [`Entity`] with db-mutating operations which can be performed when provided with a transaction.
#[cfg_attr(target_os = "unknown", async_trait(?Send))]
#[cfg_attr(not(target_os = "unknown"), async_trait)]
pub trait EntityDatabaseMutation<'a>: Entity<ConnectionType = crate::connection::KeystoreDatabaseConnection> {
    type Transaction: 'a;

    /// The `pre_save` method might generate or update some fields of the item. The canonical example is an `updated_at`
    /// field.
    ///
    /// This type must contain a copy of each modification to the item, so that the caller of a `.save(entity)`
    /// function can know what has changed and what the new values are.
    ///
    /// For types which are not edited on save, `()` is perfectly acceptable for this type.
    type AutoGeneratedFields: Default + Send;

    /// Adjust self before saving.
    ///
    /// This will be called by the transaction's implementation of `save_mut` and should not be called
    /// as part of the `save` implementation.
    ///
    /// Returns, in a format specific to the entity, all the data which has been generated or updated
    /// within this method.
    async fn pre_save(&mut self) -> CryptoKeystoreResult<Self::AutoGeneratedFields> {
        Ok(Default::default())
    }

    /// Use the transaction's interface to save this entity to the database
    async fn save(&'a self, tx: &Self::Transaction) -> CryptoKeystoreResult<()>;

    /// Use the transaction's interface to count the number of entities of this type in the database.
    async fn count(tx: &Self::Transaction) -> CryptoKeystoreResult<u32>;

    /// Use the transaction's inteface to delete this entity from the database.
    ///
    /// Returns `true` if at least one entity was deleted, or `false` if the id was not found in the database.
    ///
    /// For entites whose primary key has a distinct borrowed type, it is best to implement this as a direct
    /// passthrough:
    ///
    /// ```rust,ignore
    /// async fn delete(tx: &Self::Transaction, key: &Self::PrimaryKey) -> CoreCryptoKeystoreResult<bool> {
    ///     <Self as EntityTransactionDeleteBorrowed<'a>>::delete_borrowed(tx, id).await
    /// }
    /// ```
    async fn delete(tx: &Self::Transaction, id: &Self::PrimaryKey) -> CryptoKeystoreResult<bool>;
}

/// Extend an [`Entity`] with db-mutating operations which can be performed when provided with a transaction.
#[cfg_attr(target_os = "unknown", async_trait(?Send))]
#[cfg_attr(not(target_os = "unknown"), async_trait)]
pub trait EntityDeleteBorrowed<'a>: EntityDatabaseMutation<'a> + BorrowPrimaryKey {
    /// Delete an entity by a borrowed form of its primary key.
    async fn delete_borrowed(tx: &Self::Transaction, id: &Self::BorrowedPrimaryKey) -> CryptoKeystoreResult<bool>
    where
        for<'pk> &'pk Self::BorrowedPrimaryKey: KeyType;
}

/// Extend an [`Entity`] with db-mutating operations which can be performed when provided with a transaction.
pub trait UnifiedEntityDatabaseMutation: UnifiedEntity {
    /// The `pre_save` method might generate or update some fields of the item. The canonical example is an `updated_at`
    /// field.
    ///
    /// This type must contain a copy of each modification to the item, so that the caller of a `.save(entity)`
    /// function can know what has changed and what the new values are.
    ///
    /// For types which are not edited on save, `()` is perfectly acceptable for this type.
    type AutoGeneratedFields: Default;

    /// Adjust self before saving.
    ///
    /// This will be called by the transaction's implementation of `save_mut` and should not be called
    /// as part of the `save` implementation.
    ///
    /// Returns, in a format specific to the entity, all the data which has been generated or updated
    /// within this method.
    fn pre_save(&mut self) -> CryptoKeystoreResult<Self::AutoGeneratedFields> {
        Ok(Default::default())
    }

    /// Use the transaction's interface to save this entity to the database
    fn save(&self, tx: &Transaction) -> CryptoKeystoreResult<()>;

    /// Use the transaction's interface to count the number of entities of this type in the database.
    fn count(tx: &Transaction) -> CryptoKeystoreResult<u32>;

    /// Use the transaction's inteface to delete this entity from the database.
    ///
    /// Returns `true` if at least one entity was deleted, or `false` if the id was not found in the database.
    ///
    /// For entites whose primary key has a distinct borrowed type, it is best to implement this as a direct
    /// passthrough:
    ///
    /// ```rust,ignore
    /// fn delete(tx: &Self::Transaction, key: &Self::PrimaryKey) -> CoreCryptoKeystoreResult<bool> {
    ///     <Self as EntityTransactionDeleteBorrowed<'a>>::delete_borrowed(tx, id).await
    /// }
    /// ```
    fn delete(tx: &Transaction, id: &Self::PrimaryKey) -> CryptoKeystoreResult<bool>;
}

/// Extend an [`Entity`] with db-mutating operations which can be performed when provided with a transaction.
pub trait UnifiedEntityDeleteBorrowed: UnifiedEntityDatabaseMutation + BorrowPrimaryKey {
    /// Delete an entity by a borrowed form of its primary key.
    fn delete_borrowed(tx: &Transaction, id: &Self::BorrowedPrimaryKey) -> CryptoKeystoreResult<bool>
    where
        for<'pk> &'pk Self::BorrowedPrimaryKey: KeyType;
}
