use std::{any::Any, sync::Arc};

use crate::{
    CryptoKeystoreResult,
    connection::DatabaseConnection,
    transaction::{InMemoryTable, InMemoryTableGuard, TRANSACTION_CACHES},
};

/// A supertrait that all entities must implement. This handles multiplexing over the two different database backends.
///
/// This trait should be removed once the persistence layers are unified. See WPB-16241.
#[cfg_attr(target_family = "wasm", async_trait::async_trait(?Send))]
#[cfg_attr(not(target_family = "wasm"), async_trait::async_trait)]
pub trait EntityBase: 'static + Sized + Send + Sync {
    type ConnectionType: for<'a> DatabaseConnection<'a>;

    /// Entities which implement `EntityDatabaseMutation` have a `pre_save` method which might generate or
    /// update some fields of the item. The canonical example is an `updated_at` field.
    ///
    /// This type must contain a copy of each modification to the item, so that the caller of a `.save(entity)`
    /// function can know what has changed and what the new values are.
    type AutoGeneratedFields: Default;

    /// Beware: if you change the value of this constant on any WASM entity, you'll need to do a data migration
    ///     not only because it is used as reference to the object store names but also for the value of the aad.
    const COLLECTION_NAME: &'static str;

    fn downcast<T: EntityBase>(&self) -> Option<&T> {
        let as_dyn_any: &dyn std::any::Any = self;
        as_dyn_any.downcast_ref()
    }

    fn is<T: EntityBase>(self: &mut Arc<Self>) -> bool {
        let option_dyn_any: &dyn Any = self;
        option_dyn_any.is::<Arc<T>>()
    }

    async fn get_in_memory_table() -> InMemoryTableGuard<Self>
    where
        Self: Send + Sync + 'static,
    {
        let table = TRANSACTION_CACHES.table::<Self>().await;
        table.upgradable_read_arc().await
    }

    fn downcast_arc<T>(self: Arc<Self>) -> Option<Arc<T>>
    where
        Self: Send + Sync,
        T: EntityBase + Send + Sync,
    {
        let as_dyn_any = self as Arc<dyn Any + Send + Sync>;
        as_dyn_any.downcast().ok()
    }

    fn to_transaction_entity(self) -> crate::transaction::dynamic_dispatch::Entity;
}
