name: Fetch or make kotlin bindings for android
inputs:
  gh-token:
    required: true

runs:
  using: composite
  steps:
    - name: fetch ffi library
      uses: ./.github/actions/make/ffi-library
      with:
        gh-token: ${{ inputs.gh-token }}

    - name: fetch uniffi bindgen artifact
      uses: ./.github/actions/make/uniffi-bindgen
      with:
        gh-token: ${{ inputs.gh-token }}

    - name: make android bindings
      uses: ./.github/actions/make
      with:
        key: bindings-kotlin-android
        make-rule: bindings-kotlin-android
        target-path: |
          crypto-ffi/bindings/android/src/main/uniffi/com/wire/crypto/core_crypto_ffi.kt
        gh-token: ${{ inputs.gh-token }}
