#-------------------------------------------------------------------------------
# Rust file-based heuristics
#-------------------------------------------------------------------------------

# Relevant crates for FFI builds
CRATES := crypto crypto-ffi keystore crypto-macros

# Directory with language specific bindings
BINDINGS_DIR= ./crypto-ffi/bindings

# Workspace-level Cargo config
WORKSPACE_CARGO_FILES := Cargo.toml Cargo.lock

# Per-crate manifests
CRATE_MANIFESTS := $(addsuffix /Cargo.toml,$(CRATES))

# Enumerate all .rs files in relevant crates
RUST_RS_FILES := $(shell fd --type f --extension rs --exclude '$(BINDINGS_DIR)' . $(CRATES) | LC_ALL=C sort)

# Files relevant to build interop
INTEROP_RS_FILES := $(shell fd --type f --extension rs . interop | LC_ALL=C sort)
INTEROP_TS_FILES := $(shell fd --type f --extension ts . interop | LC_ALL=C sort)
INTEROP_MANIFEST := interop/Cargo.toml
INTEROP_SOURCES := $(INTEROP_RS_FILES) $(INTEROP_TS_FILES) $(INTEROP_MANIFEST)

# Complete dependency set for FFI-related Cargo builds
RUST_SOURCES := $(WORKSPACE_CARGO_FILES) $(CRATE_MANIFESTS) $(RUST_RS_FILES)

# Used by CI to calculate a hash of prerequisite files of a make rule
%-hash-deps:
	@if [ -z "$($*-deps)" ]; then \
	  echo "ERROR: The \"$*-deps\" variable doesn't exist in the Makefile."; exit 1; \
	fi
	@set -euo pipefail; \
	hash=$$(sha256sum $($*-deps) | sha256sum | awk '{print $$1}'); \
	echo "$$hash"

#-------------------------------------------------------------------------------
# Kotlin file-based heuristics
#-------------------------------------------------------------------------------
KT_WRAPPER = $(BINDINGS_DIR)/shared/src/commonMain/kotlin
KT_TESTS = $(BINDINGS_DIR)/shared/src/commonTest
KT_BENCHMARKS = $(BINDINGS_DIR)/jvm/src/jmh/
KT_FILES := $(shell fd --type f --extension kt . | LC_ALL=C sort)
KT_GRADLE_FILES = $(shell fd --type f --extension kts . | LC_ALL=C sort)

#-------------------------------------------------------------------------------
# Swift file-based heuristics
#-------------------------------------------------------------------------------

SWIFT_INTEROP = ./interop/src/clients/InteropClient
SWIFT_WRAPPER = ./crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto
SWIFT_TESTS = ./crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCryptoTests
SWIFT_FILES := $(shell fd --type f --extension swift . | LC_ALL=C sort)

#-------------------------------------------------------------------------------
# TypeScript file-based heuristics
#-------------------------------------------------------------------------------

JS_DIR := crypto-ffi/bindings/js
TS_SHARED_DIR := $(JS_DIR)/packages/shared
TS_BROWSER_DIR := $(JS_DIR)/packages/browser
TS_NATIVE_DIR := $(JS_DIR)/packages/native
TS_SHARED_SRC_DIR := $(TS_SHARED_DIR)/src
BROWSER_SRC_DIR := $(TS_BROWSER_DIR)/src
TS_NATIVE_SRC_DIR := $(TS_NATIVE_DIR)/src
PACKAGE_JSON := $(JS_DIR)/package.json
BUN_LOCK := $(JS_DIR)/bun.lock
BUNFIG := $(JS_DIR)/bunfig.toml

BROWSER_GEN_DIR := $(BROWSER_SRC_DIR)/autogenerated
TS_NATIVE_GEN_DIR := $(TS_NATIVE_SRC_DIR)/autogenerated

# find all .ts source files under src/ except `*.d.ts`
TS_SHARED_SRCS := $(shell fd --type f --extension ts --exclude '*.d.ts' . $(TS_SHARED_SRC_DIR) | LC_ALL=C sort)
TS_NATIVE_SRCS := $(TS_SHARED_SRCS) $(shell fd --type f --extension ts --exclude '*.d.ts' --exclude '*autogenerated*' . $(TS_NATIVE_SRC_DIR) | LC_ALL=C sort)
TS_BROWSER_SRCS := $(TS_SHARED_SRCS) $(shell fd --type f --extension ts --exclude '*.d.ts' --exclude '*autogenerated*' . $(BROWSER_SRC_DIR) | LC_ALL=C sort)
TS_SRCS := $(TS_SHARED_SRCS) $(TS_NATIVE_SRCS) $(TS_BROWSER_SRCS)

TS_NATIVE_TEST_FILES := $(shell fd --type f --extension ts . $(TS_NATIVE_DIR)/test | LC_ALL=C sort)
TS_BROWSER_TEST_FILES := $(shell fd --type f --extension ts . $(TS_BROWSER_DIR)/test | LC_ALL=C sort)
TS_TEST_FILES := $(sort $(TS_NATIVE_TEST_FILES) $(TS_BROWSER_TEST_FILES))
TS_NATIVE_BENCH_FILES := $(shell fd --type f --extension ts . $(TS_NATIVE_DIR)/benches | LC_ALL=C sort)
TS_BROWSER_BENCH_FILES := $(shell fd --type f --extension ts . $(TS_BROWSER_DIR)/benches | LC_ALL=C sort)

TS_BENCH_FILES := $(sort $(TS_NATIVE_BENCH_FILES) $(TS_BROWSER_BENCH_FILES))
JSON_FILES := $(shell fd --type f --extension json . $(JS_DIR) | LC_ALL=C sort)
