#-------------------------------------------------------------------------------
# Rust file-based heuristics
#-------------------------------------------------------------------------------

# Relevant crates for FFI builds
CRATES := crypto crypto-ffi keystore crypto-macros

# Workspace-level Cargo config
WORKSPACE_CARGO_FILES := Cargo.toml Cargo.lock

# Per-crate manifests
CRATE_MANIFESTS := $(addsuffix /Cargo.toml,$(CRATES))

# Enumerate all .rs files in relevant crates
RUST_RS_FILES := $(shell find $(CRATES) \( -type d -name rust_modules -o -type d -name node_modules -o -type d -name autogenerated \) -prune -o \
    -type f -name '*.rs' -print 2>/dev/null | LC_ALL=C sort)

# Files relevant to build interop
INTEROP_RS_FILES := $(shell find interop -type f -name '*.rs' 2>/dev/null | LC_ALL=C sort)
INTEROP_TS_FILES := $(shell find interop -type f -name '*.ts' -not -path "*/node_modules/*" 2>/dev/null | LC_ALL=C sort)
INTEROP_MANIFEST := interop/Cargo.toml
INTEROP_SOURCES := $(INTEROP_RS_FILES) $(INTEROP_TS_FILES) $(INTEROP_MANIFEST)

# Complete dependency set for FFI-related Cargo builds
RUST_SOURCES := $(WORKSPACE_CARGO_FILES) $(CRATE_MANIFESTS) $(RUST_RS_FILES)

# Used by CI to calculate a hash of prerequisite files of a make rule
%-hash-deps:
	@if [ -z "$($*-deps)" ]; then \
	  echo "ERROR: The \"$*-deps\" variable doesn't exist in the Makefile."; exit 1; \
	fi
	@set -euo pipefail; \
	hash=$$(sha256sum $($*-deps) | sha256sum | awk '{print $$1}'); \
	echo "$$hash"

#-------------------------------------------------------------------------------
# Kotlin file-based heuristics
#-------------------------------------------------------------------------------

KT_WRAPPER = ./crypto-ffi/bindings/shared/src/commonMain/kotlin
KT_TESTS = ./crypto-ffi/bindings/shared/src/commonTest
KT_BENCHMARKS = ./crypto-ffi/bindings/jvm/src/jmh/
KT_INTEROP = ./interop/src/clients/android-interop/src/main/java
KT_FILES := $(shell find $(KT_WRAPPER) $(KT_TESTS) $(KT_INTEROP) $(KT_BENCHMARKS) -type f -name '*.kt')
KT_GRADLE_FILES = $(shell find . -type f -name '*.kts')

#-------------------------------------------------------------------------------
# Swift file-based heuristics
#-------------------------------------------------------------------------------

SWIFT_INTEROP = ./interop/src/clients/InteropClient
SWIFT_WRAPPER = ./crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto
SWIFT_TESTS = ./crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCryptoTests
SWIFT_FILES := $(shell find $(SWIFT_WRAPPER) $(SWIFT_TESTS) $(SWIFT_INTEROP) -type f -name '*.swift')

#-------------------------------------------------------------------------------
# TypeScript file-based heuristics
#-------------------------------------------------------------------------------

JS_DIR := crypto-ffi/bindings/js
JS_SRC_DIR := $(JS_DIR)/src
TS_SHARED_SRC_DIR := $(JS_SRC_DIR)/shared
BROWSER_SRC_DIR := $(JS_SRC_DIR)/browser
TS_NATIVE_SRC_DIR := $(JS_SRC_DIR)/native
PACKAGE_JSON := $(JS_DIR)/package.json
BUN_LOCK := $(JS_DIR)/bun.lock
BUNFIG := $(JS_DIR)/bunfig.toml

BROWSER_GEN_DIR := $(BROWSER_SRC_DIR)/autogenerated
TS_NATIVE_GEN_DIR := $(TS_NATIVE_SRC_DIR)/autogenerated

# find all .ts source files under src/ except `*.d.ts`
TS_SHARED_SRCS := $(shell find $(TS_SHARED_SRC_DIR) -type f -name '*.ts' -not -name '*.d.ts' 2>/dev/null | LC_ALL=C sort)
TS_NATIVE_SRCS := $(TS_SHARED_SRCS) $(shell find $(JS_SRC_DIR)/native -type f -name '*.ts' -not -name '*.d.ts' -not -path '*autogenerated*' 2>/dev/null | LC_ALL=C sort)
TS_BROWSER_SRCS := $(TS_SHARED_SRCS) $(shell find $(JS_SRC_DIR)/browser -type f -name '*.ts' -not -name '*.d.ts' -not -path '*autogenerated*' 2>/dev/null | LC_ALL=C sort)
TS_SRCS := $(TS_SHARED_SRCS) $(TS_NATIVE_SRCS) $(TS_BROWSER_SRCS)

TS_NATIVE_TEST_FILES := $(shell find $(JS_DIR)/test/bun/napi -type f -name '*.ts' 2>/dev/null | LC_ALL=C sort)
TS_BROWSER_TEST_FILES := $(sort \
	$(shell find $(JS_DIR)/test/bun/wasm -type f -name '*.ts' 2>/dev/null | LC_ALL=C sort) \
	$(shell find $(JS_DIR)/test/wdio -type f -name '*.ts' 2>/dev/null | LC_ALL=C sort))
TS_TEST_FILES := $(sort $(TS_NATIVE_TEST_FILES) $(TS_BROWSER_TEST_FILES))
TS_BENCH_FILES := $(shell find $(JS_DIR)/benches -type f -name '*.ts' 2>/dev/null | LC_ALL=C sort)
