#-------------------------------------------------------------------------------
# TypeScript / JS tasks
#-------------------------------------------------------------------------------

TS_OUT_DIR := $(JS_DIR)/out
WASM_TARGET_DIR := target/wasm
WASM_BUILD_ENV := CARGO_TARGET_DIR=$(abspath $(WASM_TARGET_DIR))
WASM_TARGET_TRIPLE := wasm32-unknown-unknown
WASM_BUILD_RUSTFLAGS := --cfg getrandom_backend=\"wasm_js\" -Awarnings
WASM_FFI_LIB := $(WASM_TARGET_DIR)/debug/libcore_crypto_ffi.$(LIBRARY_EXTENSION)
BROWSER_TS_IMPL := $(BROWSER_GEN_DIR)/core_crypto_ffi.ts
BROWSER_OUT_DIR := $(TS_OUT_DIR)/browser
TS_NATIVE_OUT_DIR := $(TS_OUT_DIR)/native
BROWSER_OUT := $(BROWSER_OUT_DIR)/corecrypto.d.ts $(BROWSER_OUT_DIR)/corecrypto.js
TS_NATIVE_TARGET_DIR := target/napi
TS_NATIVE_BUILD_ENV := CARGO_TARGET_DIR=$(abspath $(TS_NATIVE_TARGET_DIR))
ifeq ($(UNAME_S),Linux)
TS_NATIVE_TARGET_TRIPLE ?= x86_64-unknown-linux-gnu
TS_NATIVE_NODE ?= linux-x64.node
else ifeq ($(UNAME_S),Darwin)
TS_NATIVE_TARGET_TRIPLE ?= aarch64-apple-darwin
TS_NATIVE_NODE ?= darwin-arm64.node
else
$(error Unsupported host platform for ts-native: $(UNAME_S))
endif

TS_NATIVE_OUT := $(TS_NATIVE_GEN_DIR)/core_crypto_ffi.ts $(TS_NATIVE_OUT_DIR)/corecrypto.d.ts $(TS_NATIVE_OUT_DIR)/corecrypto.js $(TS_NATIVE_OUT_DIR)/$(TS_NATIVE_NODE)

TS_OUT := $(BROWSER_OUT) $(TS_NATIVE_OUT)

# In release mode, fail if the lockfile does not match
BUN_FROZEN_LOCKFILE := $(if $(RELEASE),--frozen-lockfile)

# Install JS deps with Bun
# We want the `node_modules` directory to exist, and we want never to manually create it,
# and we want to ensure that this runs if the directory does not exist. So:
NODE_MODULES := $(JS_DIR)/node_modules/.stamp
$(BUN_LOCK) $(NODE_MODULES) &: $(PACKAGE_JSON)
	bun install $(BUN_FROZEN_LOCKFILE) --cwd $(JS_DIR)
# if the lockfile is unchanged, bun reports "no changes" and does not update the lock file
# which would be fine, bun is fast, except that every step thereafter is dirty
# so we update the mtime manually here
	@touch $(BUN_LOCK)
# also ensure the `NODE_MODULES` stamp file exists / is current
	@touch $(NODE_MODULES)

.PHONY: bun-deps
bun-deps: $(BUN_LOCK) $(NODE_MODULES) ## Install JS dependencies using bun

# always remove old outputs
.PHONY: ts-clean
ts-clean: ## Cleanup old TypeScript build outputs
	@rm -rf $(TS_OUT_DIR) \
	&& rm -rf $(BROWSER_GEN_DIR) \
	&& rm -rf $(TS_NATIVE_GEN_DIR) \
	&& rm -rf $(WASM_TARGET_DIR) \
	&& rm -rf $(JS_DIR)/rust_modules

ubrn-deps := $(RUST_SOURCES)
$(WASM_FFI_LIB) $(BROWSER_TS_IMPL) &: $(ubrn-deps)
	cd $(JS_DIR) && \
	$(WASM_BUILD_ENV) bun ubrn build web --no-wasm-pack

WASM_GEN := \
	$(BROWSER_GEN_DIR)/wasm-bindgen/index_bg.wasm \
	$(BROWSER_GEN_DIR)/wasm-bindgen/index_bg.wasm.d.ts \
	$(BROWSER_GEN_DIR)/wasm-bindgen/index.d.ts \
	$(BROWSER_GEN_DIR)/wasm-bindgen/index.js

# As soon as ubrn allows reusage of an existing ffi lib, we need to depend on it here.
wasm-build-deps := $(WASM_FFI_LIB) $(BROWSER_TS_IMPL) $(BUN_LOCK) $(NODE_MODULES) $(PACKAGE_JSON) $(BUNFIG)
# index.web.ts is generated but unused so we remove it
# Build the temporary host library in a dedicated target dir so we do not mix
# the shared target outputs used by ios/jvm builds.
#
# We are accepting warnings on the generated code when running `cargo check`, this is consistent with the ubrn config.
$(WASM_GEN) &: $(wasm-build-deps)
	cp Cargo.lock $(JS_DIR)/rust_modules/wasm/Cargo.lock
	cd $(JS_DIR)/rust_modules/wasm && \
	RUSTFLAGS="$(WASM_BUILD_RUSTFLAGS)" cargo build --target $(WASM_TARGET_TRIPLE) $(CARGO_BUILD_ARGS)
	cd $(JS_DIR) && \
	wasm-bindgen --target web \
	  --omit-default-module-path \
	  --out-name index \
	  --out-dir packages/browser/src/autogenerated/wasm-bindgen \
	  rust_modules/wasm/target/$(WASM_TARGET_TRIPLE)/$(RELEASE_MODE)/core_crypto_ffi_wasm.wasm && \
	rm src/index.web.ts
.PHONY: wasm-build
wasm-build: $(WASM_GEN)

# generate TypeScript defs only when corecrypto.js changed
ts-browser-deps := $(TS_BROWSER_SRCS) $(WASM_GEN)
$(BROWSER_OUT) &: $(ts-browser-deps)
	cd $(JS_DIR) && \
	bun build packages/browser/src/CoreCrypto.ts \
	  --conditions=cc-browser \
	  --target browser \
	  --format esm \
	  --outdir out/browser \
	  --entry-naming "corecrypto.[ext]" && \
	mkdir -p out/browser/autogenerated/ && \
	mkdir -p out/browser/autogenerated/wasm-bindgen && \
	cp packages/browser/src/autogenerated/wasm-bindgen/index_bg.wasm out/browser/autogenerated/wasm-bindgen/ && \
	cp packages/browser/src/autogenerated/wasm-bindgen/index_bg.wasm.d.ts out/browser/autogenerated/wasm-bindgen/ && \
	bun x dts-bundle-generator \
	  --project packages/browser/tsconfig.json \
	  -o out/browser/corecrypto.d.ts \
	  --no-check \
	  --export-referenced-types false \
	  packages/browser/src/CoreCrypto.ts
	@touch $@

.PHONY: ts-browser
ts-browser: $(BROWSER_OUT) ## Build the TypeScript wrapper for the browser

ts-native-deps := $(TS_NATIVE_SRCS) $(RUST_SOURCES) $(BUN_LOCK) $(NODE_MODULES) $(PACKAGE_JSON) $(BUNFIG)
$(TS_NATIVE_OUT) &: $(ts-native-deps)
	cd $(JS_DIR) && \
	rm -rf out/native && \
	mkdir -p out/native/autogenerated && \
	$(TS_NATIVE_BUILD_ENV) RUSTFLAGS="$(RUSTFLAGS) -Awarnings" bun ubrn generate napi build \
		--crate ../../../crypto-ffi/ \
		--ts-dir packages/native/src/autogenerated \
		--abi-dir rust_modules/napi \
		--targets $(TS_NATIVE_TARGET_TRIPLE) && \
	rm -f out/native/*.node && \
	cp packages/native/src/autogenerated/napi-bindings/$(TS_NATIVE_NODE) out/native && \
	bun build packages/native/src/CoreCrypto.ts \
	  --conditions=cc-native \
	  --target node \
	  --format esm \
	  --outdir out/native \
	  --entry-naming "corecrypto.[ext]" && \
	bun x dts-bundle-generator \
	  --project packages/native/tsconfig.json \
	  -o out/native/corecrypto.d.ts \
	  --no-check \
	  --export-referenced-types false \
	  packages/native/src/CoreCrypto.ts

ts-native-darwin-deps := $(ts-native-deps)
.PHONY: ts-native-darwin
ts-native-darwin: ## Build the native TypeScript wrapper for aarch64-apple-darwin
	$(MAKE) TS_NATIVE_TARGET_TRIPLE=$(TS_NATIVE_DARWIN_TARGET) TS_NATIVE_NODE=$(TS_NATIVE_DARWIN_NODE) ts-native

ts-native-linux-deps := $(ts-native-deps)
.PHONY: ts-native-linux
ts-native-linux: ## Build the native TypeScript wrapper for x86_64-unknown-linux-gnu
	$(MAKE) TS_NATIVE_TARGET_TRIPLE=$(TS_NATIVE_LINUX_TARGET) TS_NATIVE_NODE=$(TS_NATIVE_LINUX_NODE) ts-native

.PHONY: ts-native
ts-native: $(TS_NATIVE_OUT) ## Build the native TypeScript wrapper (automatically select the target based on the host machine)

ts-browser-test-deps := $(BROWSER_OUT) $(TS_BROWSER_TEST_FILES)

# run browser-oriented TypeScript tests (WebDriver + Bun wasm)
$(STAMPS)/ts-browser-test: $(ts-browser-test-deps)
	@set -euo pipefail; \
	cd $(JS_DIR) && \
	if [ -n "$(TEST)" ]; then \
		bun x wdio run ./packages/browser/test/wdio.test.conf.ts --mochaOpts.grep "$(TEST)"; \
		bun --conditions=cc-browser test --filter "$(TEST)" ./packages/native/test/wasm; \
	else \
		bun x wdio run ./packages/browser/test/wdio.test.conf.ts; \
		bun --conditions=cc-browser test ./packages/native/test/wasm; \
	fi
	$(TOUCH_STAMP)

ts-native-test-deps := $(TS_NATIVE_OUT) $(TS_NATIVE_TEST_FILES)

# run native TypeScript tests (Bun napi)
$(STAMPS)/ts-native-test: $(ts-native-test-deps)
	@set -euo pipefail; \
	cd $(JS_DIR) && \
	if [ -n "$(TEST)" ]; then \
		bun --conditions=cc-native test --filter "$(TEST)" ./packages/native/test/napi; \
	else \
		bun --conditions=cc-native test ./packages/native/test/napi; \
	fi
	$(TOUCH_STAMP)

$(STAMPS)/ts-test:
	@$(MAKE) LAZY_MAKE= ts-browser-test TEST="$(TEST)"
	@$(MAKE) LAZY_MAKE= ts-native-test TEST="$(TEST)"
	$(TOUCH_STAMP)

# run WebDriver benches
.PHONY: ts-bench
ts-bench: $(BROWSER_OUT) ## Run TypeScript wrapper benches in Chrome via wdio
	@set -euo pipefail; \
	cd $(JS_DIR) && \
	if [ -n "$(BENCH)" ]; then \
		bun x wdio run ./packages/browser/wdio.bench.conf.ts --mochaOpts.grep "$(BENCH)"; \
	else \
		bun x wdio run ./packages/browser/wdio.bench.conf.ts --log-level warn; \
	fi

.PHONY: ts-package
ts-package: $(TS_OUT)  ## Package the ready-to-release tarball
	@cd $(JS_DIR) && \
	bun pm pack --quiet
