#!/usr/bin/env bash

## Populate this folder with the necessary files from elsewhere in the build tree
## ! These are generated files; ensure they exist first!
##
## This is necessary for Typescript to give helpful hints about `mls.ts`, but not
## necessary for interop to actually run.

set -e

target="$(dirname "$(realpath "$0")")"
root="$(git rev-parse --show-toplevel)"
src="$root/crypto-ffi/bindings/js/src"

mkdir -p "$target/autogenerated"
cp "$src/corecrypto.js" "$target/"
cp "$src/corecrypto.d.ts" "$target/"
cp "$src/autogenerated/core-crypto-ffi_bg.wasm" "$target/autogenerated/"
