== CoreCrypto Instantiation

. The `CoreCrypto` constructor now takes a `Database` instance instead of a `DatabaseKey` and a path.
  To instantiate a database, call
ifeval::[{platform} == browser]
  `openDatabase()`
endif::[]
ifeval::[{platform} != browser]
  the `Database.new()` static method.
endif::[]

. Deferred init is now the only way to instantiate `CoreCrypto`.
ifeval::[{platform} == browser]
  We *replaced* `CoreCrypto.init(database: Database)` with the static function `CoreCrypto.new(database: Database)`
  Instead of calling `CoreCrypto.deferredInit()`, call `CoreCrypto.new()`.
endif::[]
ifeval::[{platform} != browser]
  Instead of calling `deferredInit()`, call the `CoreCrypto` constructor.
endif::[]
  As before with `deferredInit()`, call `mlsInit()` in a transaction to initialize MLS.

== MLS Initialization

. `mlsInit()` was decoupled from key package creation.
  To create key packages after initializing MLS, call `CoreCryptoContext.generateKeypackage()` in a transaction.

. removed `CoreCrypto.provideTransport()`, added `transport` parameter to `CoreCryptoContext.mlsInit()`
  Instead of providing transport separately from MLS initialization provide it when calling `mlsInit()`.

== Key Packages

. We *removed* `CoreCryptoContext.clientKeypackages()`. To generate a desired amount of key packages, make repeated calls to `CoreCryptoContext.generateKeypackage()`.

. We *removed* `CoreCryptoContext.clientValidKeypackagesCount()`. To count remaining key packages, call `CoreCryptoContext.getKeypackages()`, and filter the results as desired, and count the remaining items.

. We aligned key package spelling to KeyPackage
.. renamed `Keypackage` -> `KeyPackage`
.. renamed `KeypackageRef` -> `KeyPackageRef`
.. renamed `generateKeypackage` -> `generateKeyPackage`
.. renamed `getKeypackages` -> `getKeyPackages`
.. renamed `removeKeypackage` -> `removeKeyPackage`
.. renamed `removeKeypackagesFor` -> `removeKeyPackagesFor`

== Logging

. We *removed* `CoreCrypto.setLogger(logger: CoreCryptoLogger, level: CoreCryptoLogLevel)`
ifeval::[{platform} != jvm]
  and `CoreCrypto.setMaxLogLevel(level: CoreCryptoLogLevel)`.
endif::[]
  as logging is configured globally and not tied to a `CoreCrypto` instance.
  To set the log level use the free function `setMaxLogLevel(level: CoreCryptoLogLevel)`.
. We *renamed* `setLoggerOnly(logger: CoreCryptoLogger)` to `setLogger(logger: CoreCryptoLogger)`.

== MlsTransport interface
. Instead of returning an `MlsTransportResponse` to communicate the reason why a
  message was rejected by the DS, now throw an `MlsTransportError` instead.
 `MlsTransportResponse` was removed.

== No more buffering of unmerged changes while decrypting
. During decryption, core-crypto would previously automatically replay previously executed but unmerged (i.e., not yet acceped by the delivery service) operations.
This behavior has changed: the responsibility of replaying any unmerged operations is delegated to the consumer.
