name: TestHost
packages:
  WireCoreCrypto:
    path: ../../WireCoreCrypto
targets:
  TestHost:
    scheme:
      testTargets:
      - HostAppTests
    type: application
    platform: iOS
    sources: [.]
    dependencies:
      - package: WireCoreCrypto
    info:
      path: Info.plist
      properties:
        CFBundleIdentifier: com.wire.TestHost
    entitlements:
      path: TestHost.entitlements
      keychain-access-groups:
        - $(AppIdentifierPrefix)com.wire.TestHost
  
  HostAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: [../Tests]
    dependencies:
      - target: TestHost
    settings:
      GENERATE_INFOPLIST_FILE: YES
