name: Fetch or make kotlin bindings for jvm
inputs:
  gh-token:
    required: true

runs:
  using: composite

  steps:
    - name: fetch uniffi bindgen artifact
      uses: ./.github/actions/make/uniffi-bindgen
      with:
        gh-token: ${{ inputs.gh-token }}

    - name: fetch ffi library
      uses: ./.github/actions/make/ffi-library
      with:
        gh-token: ${{ inputs.gh-token }}

    - uses: ./.github/actions/make
      with:
        key: bindings-kotlin-jvm
        make-rule: bindings-kotlin-jvm
        target-path: crypto-ffi/bindings
        gh-token: ${{ inputs.gh-token }}
        uses-rust: true
        rust-target: x86_64-unknown-linux-gnu
