//! The methods in this module handle keystore transactions.
//!
//! Keystore transactions are "fake", in-memory persistence of database operations over time.
//! They're required because actual [`rusqlite::Transaction`] is `!Send + !Sync`, and we need
//! `Send` at a minimum in order to keep the transaction around and manipulate it concurrently
//! from various tasks.

use std::sync::Arc;

use crate::{
    CryptoKeystoreError, CryptoKeystoreResult, Database, UniqueArc,
    traits::{BorrowPrimaryKey, Entity, EntityDatabaseMutation, EntityDeleteBorrowed},
    transaction::KeystoreTransaction,
};

/// These impls control the keystore transaction lifecycle.
impl Database {
    /// Waits for the current transaction to be committed or rolled back, then starts a new one.
    pub async fn new_transaction(self: &Arc<Self>) -> CryptoKeystoreResult<UniqueArc<KeystoreTransaction>> {
        let semaphore = self.transaction_semaphore.acquire_arc().await;
        KeystoreTransaction::new(semaphore, self.clone()).await
    }

    /// Start a new transaction if no other transaction is currently in progress.
    ///
    /// If a transaction is currently in progress, this will produce a `TransactionInProgress` error.
    pub async fn try_new_immediate_transaction(
        self: &Arc<Self>,
    ) -> CryptoKeystoreResult<UniqueArc<KeystoreTransaction>> {
        let semaphore = self
            .transaction_semaphore
            .try_acquire_arc()
            .ok_or(CryptoKeystoreError::TransactionInProgress)?;
        KeystoreTransaction::new(semaphore, self.clone()).await
    }

    /// Do an operation on a keystore transaction on this database.
    ///
    /// This is a convenience method abstracting over the transaction lifecycle;
    /// it creates a new transaction (including waiting for any existing transaction to finish),
    /// then performs its operation.
    ///
    /// If the operation succeeds, the transaction is committed.
    /// Otherwise, it is rolled back.
    pub async fn transactionally<R>(
        self: &Arc<Self>,
        operation: impl AsyncFnOnce(&KeystoreTransaction) -> CryptoKeystoreResult<R>,
    ) -> CryptoKeystoreResult<R> {
        let semaphore = self.transaction_semaphore.acquire_arc().await;
        let transaction = KeystoreTransaction::new(semaphore, self.clone()).await?;

        let result = operation(&transaction).await;
        if result.is_ok() {
            transaction.commit().await?;
        }
        // otherwise implicit abort on tx drop

        result
    }

    /// Do an operation on an existing keystore transaction.
    ///
    /// This does not create, commit, or abort an existing transaction; it just provides a standardized
    /// helper to acquire it while creating appropriate errors.
    pub(crate) async fn with_transaction<R>(
        &self,
        operation: impl AsyncFnOnce(&KeystoreTransaction) -> CryptoKeystoreResult<R>,
    ) -> CryptoKeystoreResult<R> {
        let guard = self.transaction.lock().await;
        let transaction = guard
            .as_ref()
            .ok_or(CryptoKeystoreError::MutatingOperationWithoutTransaction)?
            .upgrade()
            .await
            .ok_or(CryptoKeystoreError::MutatingOperationWithoutTransaction)?;

        operation(&transaction).await
    }

    /// Merge database records with the active transaction's view of them.
    ///
    /// If no transaction is in progress, the database records are returned unchanged.
    pub(super) async fn merge_with_transaction<E>(
        &self,
        persisted_records: Vec<E>,
        merge: impl AsyncFnOnce(&KeystoreTransaction, Vec<E>) -> CryptoKeystoreResult<Vec<E>>,
    ) -> CryptoKeystoreResult<Vec<E>> {
        let guard = self.transaction.lock().await;
        let Some(weak) = guard.as_ref() else {
            return Ok(persisted_records);
        };
        let Some(tx) = weak.upgrade().await else {
            return Ok(persisted_records);
        };
        merge(&tx, persisted_records).await
    }
}

/// These impls are convenience methods to modify the keystore transaction.
///
/// Be aware that we are likely to remove these in the future: WPB-23951
impl Database {
    pub async fn save<E>(&self, entity: E) -> CryptoKeystoreResult<E::AutoGeneratedFields>
    where
        E: Entity + EntityDatabaseMutation + Send + Sync,
    {
        self.with_transaction(async |transaction| transaction.save(entity).await)
            .await
    }

    pub async fn remove<E>(&self, id: &E::PrimaryKey) -> CryptoKeystoreResult<()>
    where
        E: Entity + EntityDatabaseMutation,
    {
        self.with_transaction(async |transaction| transaction.remove::<E>(id).await)
            .await
    }

    pub async fn remove_borrowed<E>(&self, id: &E::BorrowedPrimaryKey) -> CryptoKeystoreResult<()>
    where
        E: Entity + EntityDatabaseMutation + BorrowPrimaryKey + EntityDeleteBorrowed,
    {
        self.with_transaction(async |transaction| transaction.remove_borrowed::<E>(id).await)
            .await
    }

    /// Restore an entity that was deleted in this transaction by removing it from the deleted list. This is
    /// idempotent: if the entity doesn't exist in the deleted list, do nothing.
    ///
    /// NOTE: This will only work if the entity has been added in an earlier transaction, because otherwise,
    /// removing its id from the deleted list wouldn't suffice: we'd need to replay its insertion.
    pub async fn restore<E>(&self, id: &E::BorrowedPrimaryKey) -> CryptoKeystoreResult<()>
    where
        E: Entity + EntityDatabaseMutation + BorrowPrimaryKey + EntityDeleteBorrowed,
    {
        self.with_transaction(async |transaction| transaction.restore::<E>(id).await)
            .await
    }
}
