concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-benchmark-ts-browser"
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      benchmark_message_counts:
        required: false
        type: string
      benchmark_message_sizes:
        required: false
        type: string
      benchmark_user_counts:
        required: false
        type: string
      benchmark_cipher_suites:
        required: false
        type: string
      publish:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      benchmark_message_counts:
        description: Comma-separated benchmark message counts
        required: false
        type: string
      benchmark_message_sizes:
        description: Comma-separated benchmark message sizes
        required: false
        type: string
      benchmark_user_counts:
        description: Comma-separated benchmark user counts
        required: false
        type: string
      benchmark_cipher_suites:
        description: Comma-separated benchmark cipher suite names
        required: false
        type: string
      publish:
        description: Publish benchmark results
        required: false
        type: boolean
        default: true

env:
  RELEASE: 1

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: [self-hosted, benchmark]
    env:
      BENCHMARK_MESSAGE_COUNTS: ${{ inputs.benchmark_message_counts }}
      BENCHMARK_MESSAGE_SIZES: ${{ inputs.benchmark_message_sizes }}
      BENCHMARK_USER_COUNTS: ${{ inputs.benchmark_user_counts }}
      BENCHMARK_CIPHER_SUITES: ${{ inputs.benchmark_cipher_suites }}
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install chrome-headless-shell
        run: |
          bun x @puppeteer/browsers install chrome-headless-shell@latest --path $PWD
          echo "CHROME_PATH=$(echo $PWD/chrome-headless-shell/*/*/chrome-headless-shell)" >> $GITHUB_ENV

      - name: Install chromedriver
        run: |
          bun x @puppeteer/browsers install chromedriver@latest --path $PWD
          echo "CHROMEDRIVER_PATH=$(echo $PWD/chromedriver/*/*/chromedriver)" >> $GITHUB_ENV

      - name: download web files
        uses: ./.github/actions/make/ts/browser
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-generation: ${{ vars.ARTIFACT_GENERATION }}

      - name: Run benchmark
        run: make ts-browser-bench

      # Merge all benchmark results into one file
      - name: Process results
        run: jq -s add crypto-ffi/bindings/js/benches_result/*.json > benches_result.json

      - name: Upload benchmark result
        uses: actions/upload-artifact@v7.0.1
        with:
          name: benchmark-ts-browser-results
          path: benches_result.json

  publish:
    if: ${{ inputs.publish }}
    needs:
      - benchmark
    uses: ./.github/workflows/benchmark-ts-browser-publish.yml
