name: benchmarks
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  benchmark-jvm:
    uses: ./.github/workflows/benchmark-jvm.yml
    with:
      runs_on: '["self-hosted", "benchmark"]'

  benchmark-ts-browser:
    uses: ./.github/workflows/benchmark-ts-browser.yml
    with:
      runs_on: '["self-hosted", "benchmark"]'

  benchmark-ts-native:
    uses: ./.github/workflows/benchmark-ts-native.yml
    with:
      runs_on: '["self-hosted", "benchmark"]'
