name: benchmarks
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  benchmark-jvm:
    uses: ./.github/workflows/benchmark-jvm.yml

  benchmark-ts-browser:
    uses: ./.github/workflows/benchmark-ts-browser.yml

  benchmark-ts-native:
    uses: ./.github/workflows/benchmark-ts-native.yml
