concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-check-cc-book"
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "cc-book/**"
      - ".github/workflows/check-cc-book.yml"
      - ".github/workflows/docs-cc-book.yml"
      - ".github/actions/build-cc-book/action.yml"

jobs:
  check-cc-book:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/build-cc-book
