concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-check-ts"
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:

env:
  RELEASE: 1

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/make/setup

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest

      - name: download web files
        uses: ./.github/actions/make/ts/browser
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-generation: ${{ vars.ARTIFACT_GENERATION }}

      - name: download native files
        uses: ./.github/actions/make/ts/native
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-generation: ${{ vars.ARTIFACT_GENERATION }}

      - name: lint
        run: make ts-check
