concurrency:
  group: deploy-docs-gh-pages
  cancel-in-progress: false

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  deploy-docs:
    if: github.repository == 'wireapp/core-crypto' && (github.ref == 'refs/heads/main' || (github.ref_type == 'tag' && startsWith(github.ref_name, 'v')))
    runs-on: ubuntu-latest

    env:
      GIT_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}

    steps:
    - name: checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: download pre-rendered docs
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: '{cc-book,typescript,swift,kotlin,rust}'
        path: "./target/doc/${{ env.GIT_TAG }}"
        merge-multiple: false

    - name: prepare static files
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p target/static-doc
        cp docs/*.md target/static-doc/

    - name: deploy static files
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: target/static-doc
        keep_files: true
        force_orphan: false
        enable_jekyll: true

    - name: deploy versioned docs
      uses: peaceiris/actions-gh-pages@v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: target/doc/${{ env.GIT_TAG }}
        destination_dir: ${{ env.GIT_TAG }}
        keep_files: false
        force_orphan: false
        enable_jekyll: true
