concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-docs-ts"
  cancel-in-progress: true

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  docs-ts:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: ./.github/actions/make/setup

    - name: setup bun
      uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      with:
        bun-version: latest

    - name: download web files
      uses: ./.github/actions/make/ts/browser
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        artifact-generation: ${{ vars.ARTIFACT_GENERATION }}

    - name: download native files
      uses: ./.github/actions/make/ts/native
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        artifact-generation: ${{ vars.ARTIFACT_GENERATION }}

    - name: make ts docs
      run: make docs-ts

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: typescript
        path: target/typescript/doc
        retention-days: 1
        overwrite: true
        include-hidden-files: true
        if-no-files-found: error
