concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-docs-swift"
  cancel-in-progress: true

on:
  workflow_call:

defaults:
  run:
    shell: bash -euo pipefail {0}

env:
  RELEASE: 1

jobs:
  docs-swift:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: download swift bindings
        uses: ./.github/actions/make/bindings-swift
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-generation: ${{ vars.ARTIFACT_GENERATION }}

      - name: download artifacts for ios device
        uses: ./.github/actions/make/ios/build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-generation: ${{ vars.ARTIFACT_GENERATION }}

          task: ios-device
      - name: download artifacts for ios simulator
        uses: ./.github/actions/make/ios/build
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          task: ios-simulator-arm
          artifact-generation: ${{ vars.ARTIFACT_GENERATION }}

      - name: setup Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: '26.3.0'
      - name: Set up Ruby environment
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '3.3'

      - name: install jazzy
        run: gem install jazzy

      - uses: swift-actions/setup-swift@v3
        with:
          swift-version: "6.0"

      - name: swift docs
        run: |
          mkdir -p target/doc/core_crypto_ffi/bindings/swift
          cd crypto-ffi/bindings/swift/WireCoreCrypto
          jazzy \
          	  --modules WireCoreCrypto,WireCoreCryptoUniffi \
          	  --build-tool-arguments -project,WireCoreCrypto.xcodeproj,-scheme,WireCoreCrypto,-configuration,Release \
          	  -o ../../../../target/swift/doc

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: swift
          path: target/swift/doc
          retention-days: 1
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error
