concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-docs-cc-book"
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  docs-cc-book:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0

      - uses: ./.github/actions/build-cc-book

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: cc-book
          path: cc-book/book
          retention-days: 1
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error
