concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.7.0/ktlint
          chmod a+x ktlint
          echo "$PWD" >> $GITHUB_PATH
      - name: gradle setup
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: download kotlin bindings
        uses: ./.github/actions/make/bindings-kotlin-jvm
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-generation: ${{ vars.ARTIFACT_GENERATION }}

      - name: lint
        run: |
          make kotlin-check
