name: markdown

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup fd
        uses: taiki-e/install-action@v2
        with:
          tool: fd-find
      - name: install mdformat
        run: |
          pip3 install mdformat mdformat-gfm mdformat-frontmatter mdformat-footnote mdformat-gfm-alerts mdformat-toc
      - run: fd --glob '*.md' -X mdformat --check
