concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-package-android"
  cancel-in-progress: true

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  package-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: set up jdk 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: adopt
      - name: gradle setup
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup android sdk
        uses: android-actions/setup-android@v4
      - name: install ndk and set up environment
        run: |
          ndk_version=$(cat crypto-ffi/bindings/android/ndk.version)
          echo "y" | sdkmanager --install "ndk;$ndk_version"
          echo ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$ndk_version >> $GITHUB_ENV
      - uses: ./.github/actions/make/android/package
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-generation: ${{ vars.ARTIFACT_GENERATION }}
