name: Publish Node packages

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

on:
  push:
    tags:
      - "**"

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  prepare_wasm:
    if: github.repository == 'wireapp/core-crypto'
    uses: ./.github/workflows/rust-build.yml

  publish-wasm:
    if: github.repository == 'wireapp/core-crypto'
    runs-on: ubuntu-latest
    needs: prepare_wasm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: retrieve artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-wasm-${{ github.run_id }}
          path: crypto-ffi/bindings/js

      - name: Build WASM package
        run: |
          cd crypto-ffi/bindings/js
          bun run build

      - name: Publishes package to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: "crypto-ffi/bindings/js/package.json"
